#ifndef CONF_H
#define CONF_H
#include "hal.h"

#define LEFT_MOTOR_PWM_TIMER     TIM8
#define LEFT_MOTOR_PWM_CHANNEL   TIM_CHANNEL_1
#define LEFT_MOTOR_DMA_STREAM    DMA1_Stream0
#define LEFT_MOTOR_DMA_REQUEST   DMA_REQUEST_TIM8_CH1

#define LEFT_SERVO_PWM_TIMER     TIM13
#define LEFT_SERVO_PWM_CHANNEL   TIM_CHANNEL_1
#define LEFT_SERVO_PWM_FREQUENCY 50 // 50 Hz

// #define USE_SERVOS_ONLY

#endif // CONF_H