"""Generated protobuf stubs (single home).

Regenerated by ``board.py`` from ``Firmware/msgs/proto/defs/*.proto`` (the source
of truth). All tools import from here: ``from proto import sim_pb2`` /
``from proto import flapjack_pb2``.
"""
