# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sim.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tsim.proto\"\x19\n\x08ServoCmd\x12\r\n\x05\x61ngle\x18\x01 \x03(\x02\"\x1c\n\x08MotorCmd\x12\x10\n\x08throttle\x18\x01 \x03(\x02\"\xaa\x02\n\tTelemetry\x12\r\n\x05\x65uler\x18\x01 \x03(\x02\x12\r\n\x05\x61rmed\x18\x02 \x01(\x08\x12\x11\n\timu_count\x18\x03 \x01(\r\x12\x12\n\nrc_link_up\x18\x04 \x01(\x08\x12\x0f\n\x07\x62\x61ro_pa\x18\x05 \x01(\x02\x12\x12\n\nbaro_count\x18\x06 \x01(\r\x12\x0f\n\x07gps_lat\x18\x07 \x01(\x01\x12\x0f\n\x07gps_lon\x18\x08 \x01(\x01\x12\x0f\n\x07gps_alt\x18\t \x01(\x02\x12\x10\n\x08gps_sats\x18\n \x01(\r\x12\x11\n\tgps_count\x18\x0b \x01(\r\x12\x13\n\x0bnav_pos_ned\x18\x0c \x03(\x02\x12\x13\n\x0bnav_vel_ned\x18\r \x03(\x02\x12\x11\n\tnav_valid\x18\x0e \x01(\r\x12\x1e\n\x16nav_accel_residual_deg\x18\x0f \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVOCMD']._serialized_start=13
  _globals['_SERVOCMD']._serialized_end=38
  _globals['_MOTORCMD']._serialized_start=40
  _globals['_MOTORCMD']._serialized_end=68
  _globals['_TELEMETRY']._serialized_start=71
  _globals['_TELEMETRY']._serialized_end=369
# @@protoc_insertion_point(module_scope)
