/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STM32H7XX_HAL_HSEM_H
#define _MOCK_STM32H7XX_HAL_HSEM_H

#include "unity.h"
#include "hal_stub.h"
#include "stm32h7xx_hal_hsem.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_stm32h7xx_hal_hsem_Init(void);
void mock_stm32h7xx_hal_hsem_Destroy(void);
void mock_stm32h7xx_hal_hsem_Verify(void);




#define HAL_HSEM_Take_ExpectAndReturn(SemID, ProcessID, cmock_retval) HAL_HSEM_Take_CMockExpectAndReturn(__LINE__, SemID, ProcessID, cmock_retval)
void HAL_HSEM_Take_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t SemID, uint32_t ProcessID, HAL_StatusTypeDef cmock_to_return);
#define HAL_HSEM_FastTake_ExpectAndReturn(SemID, cmock_retval) HAL_HSEM_FastTake_CMockExpectAndReturn(__LINE__, SemID, cmock_retval)
void HAL_HSEM_FastTake_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t SemID, HAL_StatusTypeDef cmock_to_return);
#define HAL_HSEM_Release_Expect(SemID, ProcessID) HAL_HSEM_Release_CMockExpect(__LINE__, SemID, ProcessID)
void HAL_HSEM_Release_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemID, uint32_t ProcessID);
#define HAL_HSEM_ReleaseAll_Expect(Key, CoreID) HAL_HSEM_ReleaseAll_CMockExpect(__LINE__, Key, CoreID)
void HAL_HSEM_ReleaseAll_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t Key, uint32_t CoreID);
#define HAL_HSEM_IsSemTaken_ExpectAndReturn(SemID, cmock_retval) HAL_HSEM_IsSemTaken_CMockExpectAndReturn(__LINE__, SemID, cmock_retval)
void HAL_HSEM_IsSemTaken_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t SemID, uint32_t cmock_to_return);
#define HAL_HSEM_SetClearKey_Expect(Key) HAL_HSEM_SetClearKey_CMockExpect(__LINE__, Key)
void HAL_HSEM_SetClearKey_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t Key);
#define HAL_HSEM_GetClearKey_ExpectAndReturn(cmock_retval) HAL_HSEM_GetClearKey_CMockExpectAndReturn(__LINE__, cmock_retval)
void HAL_HSEM_GetClearKey_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define HAL_HSEM_ActivateNotification_Expect(SemMask) HAL_HSEM_ActivateNotification_CMockExpect(__LINE__, SemMask)
void HAL_HSEM_ActivateNotification_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemMask);
#define HAL_HSEM_DeactivateNotification_Expect(SemMask) HAL_HSEM_DeactivateNotification_CMockExpect(__LINE__, SemMask)
void HAL_HSEM_DeactivateNotification_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemMask);
#define HAL_HSEM_FreeCallback_Expect(SemMask) HAL_HSEM_FreeCallback_CMockExpect(__LINE__, SemMask)
void HAL_HSEM_FreeCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemMask);
#define HAL_HSEM_IRQHandler_Expect() HAL_HSEM_IRQHandler_CMockExpect(__LINE__)
void HAL_HSEM_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
