/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_IMU_H
#define _MOCK_IMU_H

#include "hal_stub.h"
#include "imu.h"
#include "unity.h"


/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || \
(__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_imu_Init (void);
void mock_imu_Destroy (void);
void mock_imu_Verify (void);


#define IMUSendCmd_ExpectAndReturn(pIMU, cmd, cmock_retval) \
    IMUSendCmd_CMockExpectAndReturn (__LINE__, pIMU, cmd, cmock_retval)
void IMUSendCmd_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, uint16_t cmd, eSTATUS_t cmock_to_return);
#define IMUGetFeatureStatus_ExpectAndReturn(pIMU, featureRegAddr, pOutStatus, cmock_retval) \
    IMUGetFeatureStatus_CMockExpectAndReturn (__LINE__, pIMU, featureRegAddr, pOutStatus, cmock_retval)
void IMUGetFeatureStatus_CMockExpectAndReturn (
UNITY_LINE_TYPE cmock_line,
vIMU_t const* pIMU,
uint16_t featureRegAddr,
IMU_FeatureReg_t* pOutStatus,
eSTATUS_t cmock_to_return
);
#define IMUGetINTStatus_ExpectAndReturn(pIMU, cmock_arg1, cmock_retval) \
    IMUGetINTStatus_CMockExpectAndReturn (__LINE__, pIMU, cmock_arg1, cmock_retval)
void IMUGetINTStatus_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, IMU_INTStatusReg_t* cmock_arg1, eSTATUS_t cmock_to_return);
#define IMUGetSysStatus_ExpectAndReturn(pIMU, pOutStatus, cmock_retval) \
    IMUGetSysStatus_CMockExpectAndReturn (__LINE__, pIMU, pOutStatus, cmock_retval)
void IMUGetSysStatus_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, IMU_SysStatusReg_t* pOutStatus, eSTATUS_t cmock_to_return);
#define IMUReadReg_ExpectAndReturn(pIMU, reg, pBuf, len, cmock_retval) \
    IMUReadReg_CMockExpectAndReturn (__LINE__, pIMU, reg, pBuf, len, cmock_retval)
void IMUReadReg_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len, eSTATUS_t cmock_to_return);
#define IMUWriteReg_ExpectAndReturn(pIMU, reg, pBuf, len, cmock_retval) \
    IMUWriteReg_CMockExpectAndReturn (__LINE__, pIMU, reg, pBuf, len, cmock_retval)
void IMUWriteReg_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len, eSTATUS_t cmock_to_return);
#define IMUUpdateRawGyro_ExpectAndReturn(pIMU, cmock_retval) \
    IMUUpdateRawGyro_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUUpdateRawGyro_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return);
#define IMUUpdateRawAccel_ExpectAndReturn(pIMU, cmock_retval) \
    IMUUpdateRawAccel_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUUpdateRawAccel_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return);
#define IMUSetAxesRemap_ExpectAndReturn(pIMU, remap, cmock_retval) \
    IMUSetAxesRemap_CMockExpectAndReturn (__LINE__, pIMU, remap, cmock_retval)
void IMUSetAxesRemap_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAxesRemapConf remap, eSTATUS_t cmock_to_return);
#define IMUSoftReset_ExpectAndReturn(pIMU, cmock_retval) \
    IMUSoftReset_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUSoftReset_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return);
#define IMUGetConf__ExpectAndReturn(pIMU, pAConf, pGConf, altConfFlag, cmock_retval) \
    IMUGetConf__CMockExpectAndReturn (__LINE__, pIMU, pAConf, pGConf, altConfFlag, cmock_retval)
void IMUGetConf__CMockExpectAndReturn (
UNITY_LINE_TYPE cmock_line,
vIMU_t* pIMU,
IMUAccConf* pAConf,
IMUGyroConf* pGConf,
uint8_t altConfFlag,
eSTATUS_t cmock_to_return
);
#define IMUSetConf__ExpectAndReturn(pIMU, pAConf, pGConf, altConfFlag, cmock_retval) \
    IMUSetConf__CMockExpectAndReturn (__LINE__, pIMU, pAConf, pGConf, altConfFlag, cmock_retval)
void IMUSetConf__CMockExpectAndReturn (
UNITY_LINE_TYPE cmock_line,
vIMU_t* pIMU,
IMUAccConf const* pAConf,
IMUGyroConf const* pGConf,
uint8_t altConfFlag,
eSTATUS_t cmock_to_return
);
#define IMUCalibrate_ExpectAndReturn(pIMU, calibSelection, applyCorrection, cmock_retval) \
    IMUCalibrate_CMockExpectAndReturn (__LINE__, pIMU, calibSelection, applyCorrection, cmock_retval)
void IMUCalibrate_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, uint8_t calibSelection, uint8_t applyCorrection, eSTATUS_t cmock_to_return);
#define IMUSetupInterrupts_ExpectAndReturn(pIMU, cmock_retval) \
    IMUSetupInterrupts_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUSetupInterrupts_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, eSTATUS_t cmock_to_return);
#define IMUEnableInterrupts_ExpectAndReturn(pIMU, cmock_retval) \
    IMUEnableInterrupts_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUEnableInterrupts_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, eSTATUS_t cmock_to_return);
#define IMUDisableInterrupts_ExpectAndReturn(pIMU, cmock_retval) \
    IMUDisableInterrupts_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUDisableInterrupts_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, eSTATUS_t cmock_to_return);
#define IMUConvertRaw_ExpectAndReturn(aRange, ra, gRange, rg, pAccelOut, pGyroOut, cmock_retval) \
    IMUConvertRaw_CMockExpectAndReturn (__LINE__, aRange, ra, gRange, rg, pAccelOut, pGyroOut, cmock_retval)
void IMUConvertRaw_CMockExpectAndReturn (
UNITY_LINE_TYPE cmock_line,
IMU_ACC_RANGE aRange,
Vec3i ra,
IMU_GYRO_RANGE gRange,
Vec3i rg,
Vec3f* pAccelOut,
Vec3f* pGyroOut,
eSTATUS_t cmock_to_return
);
#define IMUInit_ExpectAndReturn(conf, pOutIMU, pBusOverride, cmock_retval) \
    IMUInit_CMockExpectAndReturn (__LINE__, conf, pOutIMU, pBusOverride, cmock_retval)
void IMUInit_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, IMUInitConf_t conf, IMU_t* pOutIMU, Bus_t* pBusOverride, eSTATUS_t cmock_to_return);
#define IMUStart_ExpectAndReturn(pIMU, cmock_retval) \
    IMUStart_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUStart_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return);
#define IMUStop_ExpectAndReturn(pIMU, cmock_retval) \
    IMUStop_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUStop_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return);
#define IMUHandleErr_ExpectAndReturn(pIMU, cmock_retval) \
    IMUHandleErr_CMockExpectAndReturn (__LINE__, pIMU, cmock_retval)
void IMUHandleErr_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return);
#define IMU_Update_ExpectAndReturn(pIMU, forcePolling, pOutputAccel, pOutputGyro, cmock_retval) \
    IMU_Update_CMockExpectAndReturn (__LINE__, pIMU, forcePolling, pOutputAccel, pOutputGyro, cmock_retval)
void IMU_Update_CMockExpectAndReturn (
UNITY_LINE_TYPE cmock_line,
vIMU_t* pIMU,
bool forcePolling,
Vec3f* pOutputAccel,
Vec3f* pOutputGyro,
eSTATUS_t cmock_to_return
);
#define IMUGetConf_ExpectAndReturn(pIMU, pAConf, pGConf, cmock_retval) \
    IMUGetConf_CMockExpectAndReturn (__LINE__, pIMU, pAConf, pGConf, cmock_retval)
void IMUGetConf_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, eSTATUS_t cmock_to_return);
#define IMUGetAltConf_ExpectAndReturn(pIMU, pAConf, pGConf, cmock_retval) \
    IMUGetAltConf_CMockExpectAndReturn (__LINE__, pIMU, pAConf, pGConf, cmock_retval)
void IMUGetAltConf_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, eSTATUS_t cmock_to_return);
#define IMUSetConf_ExpectAndReturn(pIMU, pAConf, pGConf, cmock_retval) \
    IMUSetConf_CMockExpectAndReturn (__LINE__, pIMU, pAConf, pGConf, cmock_retval)
void IMUSetConf_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf, eSTATUS_t cmock_to_return);
#define IMUSetAltConf_ExpectAndReturn(pIMU, pAConf, pGConf, cmock_retval) \
    IMUSetAltConf_CMockExpectAndReturn (__LINE__, pIMU, pAConf, pGConf, cmock_retval)
void IMUSetAltConf_CMockExpectAndReturn (
UNITY_LINE_TYPE cmock_line,
vIMU_t* pIMU,
IMUAccConf const* pAConf,
IMUGyroConf const* pGConf,
eSTATUS_t cmock_to_return
);
#define IMUCompareConfs_ExpectAndReturn(aconf, gconf, aconf2, gconf2, cmock_retval) \
    IMUCompareConfs_CMockExpectAndReturn (__LINE__, aconf, gconf, aconf2, gconf2, cmock_retval)
void IMUCompareConfs_CMockExpectAndReturn (
UNITY_LINE_TYPE cmock_line,
IMUAccConf aconf,
IMUGyroConf gconf,
IMUAccConf aconf2,
IMUGyroConf gconf2,
eSTATUS_t cmock_to_return
);
#define IMUGetActiveDevice_ExpectAndReturn(cmock_retval) \
    IMUGetActiveDevice_CMockExpectAndReturn (__LINE__, cmock_retval)
void IMUGetActiveDevice_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t const* cmock_to_return);
#define IMU_GetMutableActiveDevice_ExpectAndReturn(cmock_retval) \
    IMU_GetMutableActiveDevice_CMockExpectAndReturn (__LINE__, cmock_retval)
void IMU_GetMutableActiveDevice_CMockExpectAndReturn (UNITY_LINE_TYPE cmock_line, vIMU_t* cmock_to_return);
#define IMU2CPUInterruptHandler_Expect(pIMU) IMU2CPUInterruptHandler_CMockExpect (__LINE__, pIMU)
void IMU2CPUInterruptHandler_CMockExpect (UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || \
(__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
