/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_stm32h7xx_hal_dma_ex.h"

static const char* CMockString_Address = "Address";
static const char* CMockString_DataLength = "DataLength";
static const char* CMockString_DstAddress = "DstAddress";
static const char* CMockString_HAL_DMAEx_ChangeMemory = "HAL_DMAEx_ChangeMemory";
static const char* CMockString_HAL_DMAEx_ConfigMuxRequestGenerator = "HAL_DMAEx_ConfigMuxRequestGenerator";
static const char* CMockString_HAL_DMAEx_ConfigMuxSync = "HAL_DMAEx_ConfigMuxSync";
static const char* CMockString_HAL_DMAEx_DisableMuxRequestGenerator = "HAL_DMAEx_DisableMuxRequestGenerator";
static const char* CMockString_HAL_DMAEx_EnableMuxRequestGenerator = "HAL_DMAEx_EnableMuxRequestGenerator";
static const char* CMockString_HAL_DMAEx_MUX_IRQHandler = "HAL_DMAEx_MUX_IRQHandler";
static const char* CMockString_HAL_DMAEx_MultiBufferStart = "HAL_DMAEx_MultiBufferStart";
static const char* CMockString_HAL_DMAEx_MultiBufferStart_IT = "HAL_DMAEx_MultiBufferStart_IT";
static const char* CMockString_SecondMemAddress = "SecondMemAddress";
static const char* CMockString_SrcAddress = "SrcAddress";
static const char* CMockString_hdma = "hdma";
static const char* CMockString_memory = "memory";
static const char* CMockString_pRequestGeneratorConfig = "pRequestGeneratorConfig";
static const char* CMockString_pSyncConfig = "pSyncConfig";

typedef struct _CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  uint32_t Expected_SrcAddress;
  uint32_t Expected_DstAddress;
  uint32_t Expected_SecondMemAddress;
  uint32_t Expected_DataLength;

} CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  uint32_t Expected_SrcAddress;
  uint32_t Expected_DstAddress;
  uint32_t Expected_SecondMemAddress;
  uint32_t Expected_DataLength;

} CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  uint32_t Expected_Address;
  HAL_DMA_MemoryTypeDef Expected_memory;

} CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  HAL_DMA_MuxSyncConfigTypeDef* Expected_pSyncConfig;

} CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  HAL_DMA_MuxRequestGeneratorConfigTypeDef* Expected_pRequestGeneratorConfig;

} CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE;

static struct mock_stm32h7xx_hal_dma_exInstance
{
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_MultiBufferStart_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_MultiBufferStart_IT_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_ChangeMemory_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_ConfigMuxSync_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_ConfigMuxRequestGenerator_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_EnableMuxRequestGenerator_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_DisableMuxRequestGenerator_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMAEx_MUX_IRQHandler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_stm32h7xx_hal_dma_ex_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HAL_DMAEx_MultiBufferStart_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_MultiBufferStart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMAEx_MultiBufferStart_IT_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_MultiBufferStart_IT);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMAEx_ChangeMemory_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_ChangeMemory);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMAEx_ConfigMuxSync_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_ConfigMuxSync);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMAEx_ConfigMuxRequestGenerator_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_ConfigMuxRequestGenerator);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMAEx_EnableMuxRequestGenerator_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_EnableMuxRequestGenerator);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMAEx_DisableMuxRequestGenerator_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_DisableMuxRequestGenerator);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMAEx_MUX_IRQHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMAEx_MUX_IRQHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_stm32h7xx_hal_dma_ex_Init(void)
{
  mock_stm32h7xx_hal_dma_ex_Destroy();
}

void mock_stm32h7xx_hal_dma_ex_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

HAL_StatusTypeDef HAL_DMAEx_MultiBufferStart(DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_MultiBufferStart);
  cmock_call_instance = (CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_MultiBufferStart_CallInstance);
  Mock.HAL_DMAEx_MultiBufferStart_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_MultiBufferStart_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart,CMockString_SrcAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SrcAddress, SrcAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart,CMockString_DstAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DstAddress, DstAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart,CMockString_SecondMemAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SecondMemAddress, SecondMemAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart,CMockString_DataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DataLength, DataLength, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMAEx_MultiBufferStart(CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength);
void CMockExpectParameters_HAL_DMAEx_MultiBufferStart(CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength)
{
  cmock_call_instance->Expected_hdma = hdma;
  cmock_call_instance->Expected_SrcAddress = SrcAddress;
  cmock_call_instance->Expected_DstAddress = DstAddress;
  cmock_call_instance->Expected_SecondMemAddress = SecondMemAddress;
  cmock_call_instance->Expected_DataLength = DataLength;
}

void HAL_DMAEx_MultiBufferStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_MultiBufferStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_MultiBufferStart_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_MultiBufferStart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_MultiBufferStart(cmock_call_instance, hdma, SrcAddress, DstAddress, SecondMemAddress, DataLength);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMAEx_MultiBufferStart_IT(DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_MultiBufferStart_IT);
  cmock_call_instance = (CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_MultiBufferStart_IT_CallInstance);
  Mock.HAL_DMAEx_MultiBufferStart_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_MultiBufferStart_IT_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart_IT,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart_IT,CMockString_SrcAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SrcAddress, SrcAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart_IT,CMockString_DstAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DstAddress, DstAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart_IT,CMockString_SecondMemAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SecondMemAddress, SecondMemAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MultiBufferStart_IT,CMockString_DataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DataLength, DataLength, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMAEx_MultiBufferStart_IT(CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength);
void CMockExpectParameters_HAL_DMAEx_MultiBufferStart_IT(CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength)
{
  cmock_call_instance->Expected_hdma = hdma;
  cmock_call_instance->Expected_SrcAddress = SrcAddress;
  cmock_call_instance->Expected_DstAddress = DstAddress;
  cmock_call_instance->Expected_SecondMemAddress = SecondMemAddress;
  cmock_call_instance->Expected_DataLength = DataLength;
}

void HAL_DMAEx_MultiBufferStart_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_MultiBufferStart_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_MultiBufferStart_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_MultiBufferStart_IT_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_MultiBufferStart_IT(cmock_call_instance, hdma, SrcAddress, DstAddress, SecondMemAddress, DataLength);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMAEx_ChangeMemory(DMA_HandleTypeDef* hdma, uint32_t Address, HAL_DMA_MemoryTypeDef memory)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_ChangeMemory);
  cmock_call_instance = (CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_ChangeMemory_CallInstance);
  Mock.HAL_DMAEx_ChangeMemory_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_ChangeMemory_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_ChangeMemory,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_ChangeMemory,CMockString_Address);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Address, Address, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_ChangeMemory,CMockString_memory);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_memory), (void*)(&memory), sizeof(HAL_DMA_MemoryTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMAEx_ChangeMemory(CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t Address, HAL_DMA_MemoryTypeDef memory);
void CMockExpectParameters_HAL_DMAEx_ChangeMemory(CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t Address, HAL_DMA_MemoryTypeDef memory)
{
  cmock_call_instance->Expected_hdma = hdma;
  cmock_call_instance->Expected_Address = Address;
  memcpy((void*)(&cmock_call_instance->Expected_memory), (void*)(&memory),
         sizeof(HAL_DMA_MemoryTypeDef[sizeof(memory) == sizeof(HAL_DMA_MemoryTypeDef) ? 1 : -1])); /* add HAL_DMA_MemoryTypeDef to :treat_as_array if this causes an error */
}

void HAL_DMAEx_ChangeMemory_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t Address, HAL_DMA_MemoryTypeDef memory, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_ChangeMemory_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_ChangeMemory_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_ChangeMemory_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_ChangeMemory(cmock_call_instance, hdma, Address, memory);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMAEx_ConfigMuxSync(DMA_HandleTypeDef* hdma, HAL_DMA_MuxSyncConfigTypeDef* pSyncConfig)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_ConfigMuxSync);
  cmock_call_instance = (CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_ConfigMuxSync_CallInstance);
  Mock.HAL_DMAEx_ConfigMuxSync_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_ConfigMuxSync_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_ConfigMuxSync,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_ConfigMuxSync,CMockString_pSyncConfig);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pSyncConfig), (void*)(pSyncConfig), sizeof(HAL_DMA_MuxSyncConfigTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMAEx_ConfigMuxSync(CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_MuxSyncConfigTypeDef* pSyncConfig);
void CMockExpectParameters_HAL_DMAEx_ConfigMuxSync(CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_MuxSyncConfigTypeDef* pSyncConfig)
{
  cmock_call_instance->Expected_hdma = hdma;
  cmock_call_instance->Expected_pSyncConfig = pSyncConfig;
}

void HAL_DMAEx_ConfigMuxSync_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_MuxSyncConfigTypeDef* pSyncConfig, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_ConfigMuxSync_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_ConfigMuxSync_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_ConfigMuxSync_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_ConfigMuxSync(cmock_call_instance, hdma, pSyncConfig);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMAEx_ConfigMuxRequestGenerator(DMA_HandleTypeDef* hdma, HAL_DMA_MuxRequestGeneratorConfigTypeDef* pRequestGeneratorConfig)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_ConfigMuxRequestGenerator);
  cmock_call_instance = (CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_ConfigMuxRequestGenerator_CallInstance);
  Mock.HAL_DMAEx_ConfigMuxRequestGenerator_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_ConfigMuxRequestGenerator_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_ConfigMuxRequestGenerator,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_ConfigMuxRequestGenerator,CMockString_pRequestGeneratorConfig);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pRequestGeneratorConfig), (void*)(pRequestGeneratorConfig), sizeof(HAL_DMA_MuxRequestGeneratorConfigTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMAEx_ConfigMuxRequestGenerator(CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_MuxRequestGeneratorConfigTypeDef* pRequestGeneratorConfig);
void CMockExpectParameters_HAL_DMAEx_ConfigMuxRequestGenerator(CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_MuxRequestGeneratorConfigTypeDef* pRequestGeneratorConfig)
{
  cmock_call_instance->Expected_hdma = hdma;
  cmock_call_instance->Expected_pRequestGeneratorConfig = pRequestGeneratorConfig;
}

void HAL_DMAEx_ConfigMuxRequestGenerator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_MuxRequestGeneratorConfigTypeDef* pRequestGeneratorConfig, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_ConfigMuxRequestGenerator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_ConfigMuxRequestGenerator_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_ConfigMuxRequestGenerator_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_ConfigMuxRequestGenerator(cmock_call_instance, hdma, pRequestGeneratorConfig);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMAEx_EnableMuxRequestGenerator(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_EnableMuxRequestGenerator);
  cmock_call_instance = (CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_EnableMuxRequestGenerator_CallInstance);
  Mock.HAL_DMAEx_EnableMuxRequestGenerator_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_EnableMuxRequestGenerator_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_EnableMuxRequestGenerator,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMAEx_EnableMuxRequestGenerator(CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMAEx_EnableMuxRequestGenerator(CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMAEx_EnableMuxRequestGenerator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_EnableMuxRequestGenerator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_EnableMuxRequestGenerator_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_EnableMuxRequestGenerator_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_EnableMuxRequestGenerator(cmock_call_instance, hdma);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMAEx_DisableMuxRequestGenerator(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_DisableMuxRequestGenerator);
  cmock_call_instance = (CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_DisableMuxRequestGenerator_CallInstance);
  Mock.HAL_DMAEx_DisableMuxRequestGenerator_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_DisableMuxRequestGenerator_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_DisableMuxRequestGenerator,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMAEx_DisableMuxRequestGenerator(CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMAEx_DisableMuxRequestGenerator(CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMAEx_DisableMuxRequestGenerator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_DisableMuxRequestGenerator_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_DisableMuxRequestGenerator_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_DisableMuxRequestGenerator_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_DisableMuxRequestGenerator(cmock_call_instance, hdma);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_DMAEx_MUX_IRQHandler(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMAEx_MUX_IRQHandler);
  cmock_call_instance = (CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMAEx_MUX_IRQHandler_CallInstance);
  Mock.HAL_DMAEx_MUX_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMAEx_MUX_IRQHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMAEx_MUX_IRQHandler,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_DMAEx_MUX_IRQHandler(CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMAEx_MUX_IRQHandler(CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMAEx_MUX_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE));
  CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMAEx_MUX_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMAEx_MUX_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMAEx_MUX_IRQHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMAEx_MUX_IRQHandler(cmock_call_instance, hdma);
}

