/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_filter.h"

static const char* CMockString_FilterGetActiveFilter = "FilterGetActiveFilter";
static const char* CMockString_FilterInit = "FilterInit";
static const char* CMockString_FilterMadgwickInit = "FilterMadgwickInit";
static const char* CMockString_FilterMadgwickUpdate = "FilterMadgwickUpdate";
static const char* CMockString_FilterMadgwickUpdate_6DOF = "FilterMadgwickUpdate_6DOF";
static const char* CMockString_FilterMadgwickUpdate_9DOF = "FilterMadgwickUpdate_9DOF";
static const char* CMockString_FilterStart = "FilterStart";
static const char* CMockString_FilterStop = "FilterStop";
static const char* CMockString_Filter_GetMutableActiveFilter = "Filter_GetMutableActiveFilter";
static const char* CMockString_Filter_Update = "Filter_Update";
static const char* CMockString_conf = "conf";
static const char* CMockString_dt = "dt";
static const char* CMockString_pAccel = "pAccel";
static const char* CMockString_pFilter = "pFilter";
static const char* CMockString_pGyro = "pGyro";
static const char* CMockString_pGyroDegs = "pGyroDegs";
static const char* CMockString_pMag = "pMag";
static const char* CMockString_pOut = "pOut";
static const char* CMockString_pOutAttitude = "pOutAttitude";
static const char* CMockString_pOutput = "pOutput";
static const char* CMockString_warmUpIterations = "warmUpIterations";

typedef struct _CMOCK_FilterMadgwickInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  FilterMadgwickInitConf_t Expected_conf;
  FilterMadgwick_t* Expected_pOut;

} CMOCK_FilterMadgwickInit_CALL_INSTANCE;

typedef struct _CMOCK_FilterMadgwickUpdate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  FilterMadgwick_t* Expected_pFilter;
  Vec3f const* Expected_pAccel;
  Vec3f const* Expected_pGyro;
  Vec3f const* Expected_pMag;
  float Expected_dt;
  Vec3f* Expected_pOutAttitude;

} CMOCK_FilterMadgwickUpdate_CALL_INSTANCE;

typedef struct _CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  FilterMadgwick_t* Expected_pFilter;
  Vec3f const* Expected_pAccel;
  Vec3f const* Expected_pGyroDegs;
  float Expected_dt;

} CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE;

typedef struct _CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  FilterMadgwick_t* Expected_pFilter;
  Vec3f const* Expected_pAccel;
  Vec3f const* Expected_pGyro;
  Vec3f const* Expected_pMag;
  float Expected_dt;

} CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE;

typedef struct _CMOCK_FilterInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  FilterInitConf_t Expected_conf;
  Filter_t* Expected_pOut;

} CMOCK_FilterInit_CALL_INSTANCE;

typedef struct _CMOCK_FilterStart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vFilter_t* Expected_pFilter;
  uint32_t Expected_warmUpIterations;
  Vec3f* Expected_pOutAttitude;

} CMOCK_FilterStart_CALL_INSTANCE;

typedef struct _CMOCK_FilterStop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vFilter_t* Expected_pFilter;

} CMOCK_FilterStop_CALL_INSTANCE;

typedef struct _CMOCK_Filter_Update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vFilter_t* Expected_pFilter;
  Vec3f const* Expected_pAccel;
  Vec3f const* Expected_pGyro;
  Vec3f const* Expected_pMag;
  float Expected_dt;
  Vec3f* Expected_pOutput;

} CMOCK_Filter_Update_CALL_INSTANCE;

typedef struct _CMOCK_FilterGetActiveFilter_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  vFilter_t const* ReturnVal;

} CMOCK_FilterGetActiveFilter_CALL_INSTANCE;

typedef struct _CMOCK_Filter_GetMutableActiveFilter_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  vFilter_t* ReturnVal;

} CMOCK_Filter_GetMutableActiveFilter_CALL_INSTANCE;

static struct mock_filterInstance
{
  CMOCK_MEM_INDEX_TYPE FilterMadgwickInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE FilterMadgwickUpdate_CallInstance;
  CMOCK_MEM_INDEX_TYPE FilterMadgwickUpdate_6DOF_CallInstance;
  CMOCK_MEM_INDEX_TYPE FilterMadgwickUpdate_9DOF_CallInstance;
  CMOCK_MEM_INDEX_TYPE FilterInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE FilterStart_CallInstance;
  CMOCK_MEM_INDEX_TYPE FilterStop_CallInstance;
  CMOCK_MEM_INDEX_TYPE Filter_Update_CallInstance;
  CMOCK_MEM_INDEX_TYPE FilterGetActiveFilter_CallInstance;
  CMOCK_MEM_INDEX_TYPE Filter_GetMutableActiveFilter_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_filter_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.FilterMadgwickInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterMadgwickInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FilterMadgwickUpdate_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterMadgwickUpdate);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FilterMadgwickUpdate_6DOF_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterMadgwickUpdate_6DOF);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FilterMadgwickUpdate_9DOF_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterMadgwickUpdate_9DOF);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FilterInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FilterStart_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterStart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FilterStop_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterStop);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.Filter_Update_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Filter_Update);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.FilterGetActiveFilter_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_FilterGetActiveFilter);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.Filter_GetMutableActiveFilter_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Filter_GetMutableActiveFilter);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_filter_Init(void)
{
  mock_filter_Destroy();
}

void mock_filter_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool FilterMadgwickInit(FilterMadgwickInitConf_t conf, FilterMadgwick_t* pOut)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterMadgwickInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterMadgwickInit);
  cmock_call_instance = (CMOCK_FilterMadgwickInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterMadgwickInit_CallInstance);
  Mock.FilterMadgwickInit_CallInstance = CMock_Guts_MemNext(Mock.FilterMadgwickInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickInit,CMockString_conf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf), sizeof(FilterMadgwickInitConf_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickInit,CMockString_pOut);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOut), (void*)(pOut), sizeof(FilterMadgwick_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FilterMadgwickInit(CMOCK_FilterMadgwickInit_CALL_INSTANCE* cmock_call_instance, FilterMadgwickInitConf_t conf, FilterMadgwick_t* pOut);
void CMockExpectParameters_FilterMadgwickInit(CMOCK_FilterMadgwickInit_CALL_INSTANCE* cmock_call_instance, FilterMadgwickInitConf_t conf, FilterMadgwick_t* pOut)
{
  memcpy((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf),
         sizeof(FilterMadgwickInitConf_t[sizeof(conf) == sizeof(FilterMadgwickInitConf_t) ? 1 : -1])); /* add FilterMadgwickInitConf_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_pOut = pOut;
}

void FilterMadgwickInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwickInitConf_t conf, FilterMadgwick_t* pOut, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterMadgwickInit_CALL_INSTANCE));
  CMOCK_FilterMadgwickInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterMadgwickInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterMadgwickInit_CallInstance = CMock_Guts_MemChain(Mock.FilterMadgwickInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FilterMadgwickInit(cmock_call_instance, conf, pOut);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool FilterMadgwickUpdate(FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutAttitude)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterMadgwickUpdate_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterMadgwickUpdate);
  cmock_call_instance = (CMOCK_FilterMadgwickUpdate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterMadgwickUpdate_CallInstance);
  Mock.FilterMadgwickUpdate_CallInstance = CMock_Guts_MemNext(Mock.FilterMadgwickUpdate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate,CMockString_pFilter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pFilter), (void*)(pFilter), sizeof(FilterMadgwick_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate,CMockString_pAccel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAccel), (void*)(pAccel), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate,CMockString_pGyro);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGyro), (void*)(pGyro), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate,CMockString_pMag);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMag), (void*)(pMag), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate,CMockString_dt);
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_dt, dt, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate,CMockString_pOutAttitude);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutAttitude), (void*)(pOutAttitude), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FilterMadgwickUpdate(CMOCK_FilterMadgwickUpdate_CALL_INSTANCE* cmock_call_instance, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutAttitude);
void CMockExpectParameters_FilterMadgwickUpdate(CMOCK_FilterMadgwickUpdate_CALL_INSTANCE* cmock_call_instance, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutAttitude)
{
  cmock_call_instance->Expected_pFilter = pFilter;
  cmock_call_instance->Expected_pAccel = pAccel;
  cmock_call_instance->Expected_pGyro = pGyro;
  cmock_call_instance->Expected_pMag = pMag;
  cmock_call_instance->Expected_dt = dt;
  cmock_call_instance->Expected_pOutAttitude = pOutAttitude;
}

void FilterMadgwickUpdate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutAttitude, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterMadgwickUpdate_CALL_INSTANCE));
  CMOCK_FilterMadgwickUpdate_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterMadgwickUpdate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterMadgwickUpdate_CallInstance = CMock_Guts_MemChain(Mock.FilterMadgwickUpdate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FilterMadgwickUpdate(cmock_call_instance, pFilter, pAccel, pGyro, pMag, dt, pOutAttitude);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool FilterMadgwickUpdate_6DOF(FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyroDegs, float dt)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterMadgwickUpdate_6DOF);
  cmock_call_instance = (CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterMadgwickUpdate_6DOF_CallInstance);
  Mock.FilterMadgwickUpdate_6DOF_CallInstance = CMock_Guts_MemNext(Mock.FilterMadgwickUpdate_6DOF_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_6DOF,CMockString_pFilter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pFilter), (void*)(pFilter), sizeof(FilterMadgwick_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_6DOF,CMockString_pAccel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAccel), (void*)(pAccel), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_6DOF,CMockString_pGyroDegs);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGyroDegs), (void*)(pGyroDegs), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_6DOF,CMockString_dt);
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_dt, dt, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FilterMadgwickUpdate_6DOF(CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE* cmock_call_instance, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyroDegs, float dt);
void CMockExpectParameters_FilterMadgwickUpdate_6DOF(CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE* cmock_call_instance, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyroDegs, float dt)
{
  cmock_call_instance->Expected_pFilter = pFilter;
  cmock_call_instance->Expected_pAccel = pAccel;
  cmock_call_instance->Expected_pGyroDegs = pGyroDegs;
  cmock_call_instance->Expected_dt = dt;
}

void FilterMadgwickUpdate_6DOF_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyroDegs, float dt, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE));
  CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterMadgwickUpdate_6DOF_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterMadgwickUpdate_6DOF_CallInstance = CMock_Guts_MemChain(Mock.FilterMadgwickUpdate_6DOF_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FilterMadgwickUpdate_6DOF(cmock_call_instance, pFilter, pAccel, pGyroDegs, dt);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool FilterMadgwickUpdate_9DOF(FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterMadgwickUpdate_9DOF);
  cmock_call_instance = (CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterMadgwickUpdate_9DOF_CallInstance);
  Mock.FilterMadgwickUpdate_9DOF_CallInstance = CMock_Guts_MemNext(Mock.FilterMadgwickUpdate_9DOF_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_9DOF,CMockString_pFilter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pFilter), (void*)(pFilter), sizeof(FilterMadgwick_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_9DOF,CMockString_pAccel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAccel), (void*)(pAccel), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_9DOF,CMockString_pGyro);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGyro), (void*)(pGyro), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_9DOF,CMockString_pMag);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMag), (void*)(pMag), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterMadgwickUpdate_9DOF,CMockString_dt);
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_dt, dt, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FilterMadgwickUpdate_9DOF(CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE* cmock_call_instance, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt);
void CMockExpectParameters_FilterMadgwickUpdate_9DOF(CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE* cmock_call_instance, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt)
{
  cmock_call_instance->Expected_pFilter = pFilter;
  cmock_call_instance->Expected_pAccel = pAccel;
  cmock_call_instance->Expected_pGyro = pGyro;
  cmock_call_instance->Expected_pMag = pMag;
  cmock_call_instance->Expected_dt = dt;
}

void FilterMadgwickUpdate_9DOF_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE));
  CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterMadgwickUpdate_9DOF_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterMadgwickUpdate_9DOF_CallInstance = CMock_Guts_MemChain(Mock.FilterMadgwickUpdate_9DOF_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FilterMadgwickUpdate_9DOF(cmock_call_instance, pFilter, pAccel, pGyro, pMag, dt);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

eSTATUS_t FilterInit(FilterInitConf_t conf, Filter_t* pOut)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterInit);
  cmock_call_instance = (CMOCK_FilterInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterInit_CallInstance);
  Mock.FilterInit_CallInstance = CMock_Guts_MemNext(Mock.FilterInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FilterInit,CMockString_conf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf), sizeof(FilterInitConf_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterInit,CMockString_pOut);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOut), (void*)(pOut), sizeof(Filter_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FilterInit(CMOCK_FilterInit_CALL_INSTANCE* cmock_call_instance, FilterInitConf_t conf, Filter_t* pOut);
void CMockExpectParameters_FilterInit(CMOCK_FilterInit_CALL_INSTANCE* cmock_call_instance, FilterInitConf_t conf, Filter_t* pOut)
{
  memcpy((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf),
         sizeof(FilterInitConf_t[sizeof(conf) == sizeof(FilterInitConf_t) ? 1 : -1])); /* add FilterInitConf_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_pOut = pOut;
}

void FilterInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterInitConf_t conf, Filter_t* pOut, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterInit_CALL_INSTANCE));
  CMOCK_FilterInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterInit_CallInstance = CMock_Guts_MemChain(Mock.FilterInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FilterInit(cmock_call_instance, conf, pOut);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t FilterStart(vFilter_t* pFilter, uint32_t warmUpIterations, Vec3f* pOutAttitude)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterStart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterStart);
  cmock_call_instance = (CMOCK_FilterStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterStart_CallInstance);
  Mock.FilterStart_CallInstance = CMock_Guts_MemNext(Mock.FilterStart_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FilterStart,CMockString_pFilter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pFilter), (void*)(pFilter), sizeof(vFilter_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterStart,CMockString_warmUpIterations);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_warmUpIterations, warmUpIterations, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_FilterStart,CMockString_pOutAttitude);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutAttitude), (void*)(pOutAttitude), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FilterStart(CMOCK_FilterStart_CALL_INSTANCE* cmock_call_instance, vFilter_t* pFilter, uint32_t warmUpIterations, Vec3f* pOutAttitude);
void CMockExpectParameters_FilterStart(CMOCK_FilterStart_CALL_INSTANCE* cmock_call_instance, vFilter_t* pFilter, uint32_t warmUpIterations, Vec3f* pOutAttitude)
{
  cmock_call_instance->Expected_pFilter = pFilter;
  cmock_call_instance->Expected_warmUpIterations = warmUpIterations;
  cmock_call_instance->Expected_pOutAttitude = pOutAttitude;
}

void FilterStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* pFilter, uint32_t warmUpIterations, Vec3f* pOutAttitude, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterStart_CALL_INSTANCE));
  CMOCK_FilterStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterStart_CallInstance = CMock_Guts_MemChain(Mock.FilterStart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FilterStart(cmock_call_instance, pFilter, warmUpIterations, pOutAttitude);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t FilterStop(vFilter_t* pFilter)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterStop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterStop);
  cmock_call_instance = (CMOCK_FilterStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterStop_CallInstance);
  Mock.FilterStop_CallInstance = CMock_Guts_MemNext(Mock.FilterStop_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_FilterStop,CMockString_pFilter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pFilter), (void*)(pFilter), sizeof(vFilter_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_FilterStop(CMOCK_FilterStop_CALL_INSTANCE* cmock_call_instance, vFilter_t* pFilter);
void CMockExpectParameters_FilterStop(CMOCK_FilterStop_CALL_INSTANCE* cmock_call_instance, vFilter_t* pFilter)
{
  cmock_call_instance->Expected_pFilter = pFilter;
}

void FilterStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* pFilter, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterStop_CALL_INSTANCE));
  CMOCK_FilterStop_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterStop_CallInstance = CMock_Guts_MemChain(Mock.FilterStop_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_FilterStop(cmock_call_instance, pFilter);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t Filter_Update(vFilter_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutput)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Filter_Update_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Filter_Update);
  cmock_call_instance = (CMOCK_Filter_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Filter_Update_CallInstance);
  Mock.Filter_Update_CallInstance = CMock_Guts_MemNext(Mock.Filter_Update_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Filter_Update,CMockString_pFilter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pFilter), (void*)(pFilter), sizeof(vFilter_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Filter_Update,CMockString_pAccel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAccel), (void*)(pAccel), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Filter_Update,CMockString_pGyro);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGyro), (void*)(pGyro), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Filter_Update,CMockString_pMag);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMag), (void*)(pMag), sizeof(Vec3f const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Filter_Update,CMockString_dt);
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_dt, dt, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Filter_Update,CMockString_pOutput);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutput), (void*)(pOutput), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Filter_Update(CMOCK_Filter_Update_CALL_INSTANCE* cmock_call_instance, vFilter_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutput);
void CMockExpectParameters_Filter_Update(CMOCK_Filter_Update_CALL_INSTANCE* cmock_call_instance, vFilter_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutput)
{
  cmock_call_instance->Expected_pFilter = pFilter;
  cmock_call_instance->Expected_pAccel = pAccel;
  cmock_call_instance->Expected_pGyro = pGyro;
  cmock_call_instance->Expected_pMag = pMag;
  cmock_call_instance->Expected_dt = dt;
  cmock_call_instance->Expected_pOutput = pOutput;
}

void Filter_Update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutput, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Filter_Update_CALL_INSTANCE));
  CMOCK_Filter_Update_CALL_INSTANCE* cmock_call_instance = (CMOCK_Filter_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Filter_Update_CallInstance = CMock_Guts_MemChain(Mock.Filter_Update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Filter_Update(cmock_call_instance, pFilter, pAccel, pGyro, pMag, dt, pOutput);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

vFilter_t const* FilterGetActiveFilter(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_FilterGetActiveFilter_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_FilterGetActiveFilter);
  cmock_call_instance = (CMOCK_FilterGetActiveFilter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.FilterGetActiveFilter_CallInstance);
  Mock.FilterGetActiveFilter_CallInstance = CMock_Guts_MemNext(Mock.FilterGetActiveFilter_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void FilterGetActiveFilter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t const* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_FilterGetActiveFilter_CALL_INSTANCE));
  CMOCK_FilterGetActiveFilter_CALL_INSTANCE* cmock_call_instance = (CMOCK_FilterGetActiveFilter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.FilterGetActiveFilter_CallInstance = CMock_Guts_MemChain(Mock.FilterGetActiveFilter_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

vFilter_t* Filter_GetMutableActiveFilter(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Filter_GetMutableActiveFilter_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Filter_GetMutableActiveFilter);
  cmock_call_instance = (CMOCK_Filter_GetMutableActiveFilter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Filter_GetMutableActiveFilter_CallInstance);
  Mock.Filter_GetMutableActiveFilter_CallInstance = CMock_Guts_MemNext(Mock.Filter_GetMutableActiveFilter_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void Filter_GetMutableActiveFilter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Filter_GetMutableActiveFilter_CALL_INSTANCE));
  CMOCK_Filter_GetMutableActiveFilter_CALL_INSTANCE* cmock_call_instance = (CMOCK_Filter_GetMutableActiveFilter_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Filter_GetMutableActiveFilter_CallInstance = CMock_Guts_MemChain(Mock.Filter_GetMutableActiveFilter_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

