/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STM32H7XX_HAL_I2C_H
#define _MOCK_STM32H7XX_HAL_I2C_H

#include "unity.h"
#include "hal_stub.h"
#include "stm32h7xx_hal_i2c.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_stm32h7xx_hal_i2c_Init(void);
void mock_stm32h7xx_hal_i2c_Destroy(void);
void mock_stm32h7xx_hal_i2c_Verify(void);




#define HAL_I2C_Init_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_Init_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_DeInit_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_DeInit_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_MspInit_Expect(hi2c) HAL_I2C_MspInit_CMockExpect(__LINE__, hi2c)
void HAL_I2C_MspInit_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_MspDeInit_Expect(hi2c) HAL_I2C_MspDeInit_CMockExpect(__LINE__, hi2c)
void HAL_I2C_MspDeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_RegisterCallback_ExpectAndReturn(hi2c, CallbackID, pCallback, cmock_retval) HAL_I2C_RegisterCallback_CMockExpectAndReturn(__LINE__, hi2c, CallbackID, pCallback, cmock_retval)
void HAL_I2C_RegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, HAL_I2C_CallbackIDTypeDef CallbackID, pI2C_CallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_UnRegisterCallback_ExpectAndReturn(hi2c, CallbackID, cmock_retval) HAL_I2C_UnRegisterCallback_CMockExpectAndReturn(__LINE__, hi2c, CallbackID, cmock_retval)
void HAL_I2C_UnRegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, HAL_I2C_CallbackIDTypeDef CallbackID, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_RegisterAddrCallback_ExpectAndReturn(hi2c, pCallback, cmock_retval) HAL_I2C_RegisterAddrCallback_CMockExpectAndReturn(__LINE__, hi2c, pCallback, cmock_retval)
void HAL_I2C_RegisterAddrCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, pI2C_AddrCallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_UnRegisterAddrCallback_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_UnRegisterAddrCallback_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_UnRegisterAddrCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Transmit_ExpectAndReturn(hi2c, DevAddress, pData, Size, Timeout, cmock_retval) HAL_I2C_Master_Transmit_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Master_Transmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Receive_ExpectAndReturn(hi2c, DevAddress, pData, Size, Timeout, cmock_retval) HAL_I2C_Master_Receive_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Master_Receive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Transmit_ExpectAndReturn(hi2c, pData, Size, Timeout, cmock_retval) HAL_I2C_Slave_Transmit_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Slave_Transmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Receive_ExpectAndReturn(hi2c, pData, Size, Timeout, cmock_retval) HAL_I2C_Slave_Receive_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Slave_Receive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Write_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval) HAL_I2C_Mem_Write_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Mem_Write_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Read_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval) HAL_I2C_Mem_Read_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, Timeout, cmock_retval)
void HAL_I2C_Mem_Read_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_IsDeviceReady_ExpectAndReturn(hi2c, DevAddress, Trials, Timeout, cmock_retval) HAL_I2C_IsDeviceReady_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, Trials, Timeout, cmock_retval)
void HAL_I2C_IsDeviceReady_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint32_t Trials, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Transmit_IT_ExpectAndReturn(hi2c, DevAddress, pData, Size, cmock_retval) HAL_I2C_Master_Transmit_IT_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, cmock_retval)
void HAL_I2C_Master_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Receive_IT_ExpectAndReturn(hi2c, DevAddress, pData, Size, cmock_retval) HAL_I2C_Master_Receive_IT_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, cmock_retval)
void HAL_I2C_Master_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Transmit_IT_ExpectAndReturn(hi2c, pData, Size, cmock_retval) HAL_I2C_Slave_Transmit_IT_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, cmock_retval)
void HAL_I2C_Slave_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Receive_IT_ExpectAndReturn(hi2c, pData, Size, cmock_retval) HAL_I2C_Slave_Receive_IT_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, cmock_retval)
void HAL_I2C_Slave_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Write_IT_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval) HAL_I2C_Mem_Write_IT_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval)
void HAL_I2C_Mem_Write_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Read_IT_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval) HAL_I2C_Mem_Read_IT_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval)
void HAL_I2C_Mem_Read_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Seq_Transmit_IT_ExpectAndReturn(hi2c, DevAddress, pData, Size, XferOptions, cmock_retval) HAL_I2C_Master_Seq_Transmit_IT_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Master_Seq_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Seq_Receive_IT_ExpectAndReturn(hi2c, DevAddress, pData, Size, XferOptions, cmock_retval) HAL_I2C_Master_Seq_Receive_IT_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Master_Seq_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Seq_Transmit_IT_ExpectAndReturn(hi2c, pData, Size, XferOptions, cmock_retval) HAL_I2C_Slave_Seq_Transmit_IT_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Slave_Seq_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Seq_Receive_IT_ExpectAndReturn(hi2c, pData, Size, XferOptions, cmock_retval) HAL_I2C_Slave_Seq_Receive_IT_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Slave_Seq_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_EnableListen_IT_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_EnableListen_IT_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_EnableListen_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_DisableListen_IT_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_DisableListen_IT_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_DisableListen_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Abort_IT_ExpectAndReturn(hi2c, DevAddress, cmock_retval) HAL_I2C_Master_Abort_IT_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, cmock_retval)
void HAL_I2C_Master_Abort_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Transmit_DMA_ExpectAndReturn(hi2c, DevAddress, pData, Size, cmock_retval) HAL_I2C_Master_Transmit_DMA_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, cmock_retval)
void HAL_I2C_Master_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Receive_DMA_ExpectAndReturn(hi2c, DevAddress, pData, Size, cmock_retval) HAL_I2C_Master_Receive_DMA_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, cmock_retval)
void HAL_I2C_Master_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Transmit_DMA_ExpectAndReturn(hi2c, pData, Size, cmock_retval) HAL_I2C_Slave_Transmit_DMA_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, cmock_retval)
void HAL_I2C_Slave_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Receive_DMA_ExpectAndReturn(hi2c, pData, Size, cmock_retval) HAL_I2C_Slave_Receive_DMA_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, cmock_retval)
void HAL_I2C_Slave_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Write_DMA_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval) HAL_I2C_Mem_Write_DMA_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval)
void HAL_I2C_Mem_Write_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Mem_Read_DMA_ExpectAndReturn(hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval) HAL_I2C_Mem_Read_DMA_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, MemAddress, MemAddSize, pData, Size, cmock_retval)
void HAL_I2C_Mem_Read_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint16_t MemAddress, uint16_t MemAddSize, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Seq_Transmit_DMA_ExpectAndReturn(hi2c, DevAddress, pData, Size, XferOptions, cmock_retval) HAL_I2C_Master_Seq_Transmit_DMA_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Master_Seq_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Master_Seq_Receive_DMA_ExpectAndReturn(hi2c, DevAddress, pData, Size, XferOptions, cmock_retval) HAL_I2C_Master_Seq_Receive_DMA_CMockExpectAndReturn(__LINE__, hi2c, DevAddress, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Master_Seq_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint16_t DevAddress, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Seq_Transmit_DMA_ExpectAndReturn(hi2c, pData, Size, XferOptions, cmock_retval) HAL_I2C_Slave_Seq_Transmit_DMA_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Slave_Seq_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_Slave_Seq_Receive_DMA_ExpectAndReturn(hi2c, pData, Size, XferOptions, cmock_retval) HAL_I2C_Slave_Seq_Receive_DMA_CMockExpectAndReturn(__LINE__, hi2c, pData, Size, XferOptions, cmock_retval)
void HAL_I2C_Slave_Seq_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t* pData, uint16_t Size, uint32_t XferOptions, HAL_StatusTypeDef cmock_to_return);
#define HAL_I2C_EV_IRQHandler_Expect(hi2c) HAL_I2C_EV_IRQHandler_CMockExpect(__LINE__, hi2c)
void HAL_I2C_EV_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_ER_IRQHandler_Expect(hi2c) HAL_I2C_ER_IRQHandler_CMockExpect(__LINE__, hi2c)
void HAL_I2C_ER_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_MasterTxCpltCallback_Expect(hi2c) HAL_I2C_MasterTxCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_MasterTxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_MasterRxCpltCallback_Expect(hi2c) HAL_I2C_MasterRxCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_MasterRxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_SlaveTxCpltCallback_Expect(hi2c) HAL_I2C_SlaveTxCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_SlaveTxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_SlaveRxCpltCallback_Expect(hi2c) HAL_I2C_SlaveRxCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_SlaveRxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_AddrCallback_Expect(hi2c, TransferDirection, AddrMatchCode) HAL_I2C_AddrCallback_CMockExpect(__LINE__, hi2c, TransferDirection, AddrMatchCode)
void HAL_I2C_AddrCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c, uint8_t TransferDirection, uint16_t AddrMatchCode);
#define HAL_I2C_ListenCpltCallback_Expect(hi2c) HAL_I2C_ListenCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_ListenCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_MemTxCpltCallback_Expect(hi2c) HAL_I2C_MemTxCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_MemTxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_MemRxCpltCallback_Expect(hi2c) HAL_I2C_MemRxCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_MemRxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_ErrorCallback_Expect(hi2c) HAL_I2C_ErrorCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_ErrorCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_AbortCpltCallback_Expect(hi2c) HAL_I2C_AbortCpltCallback_CMockExpect(__LINE__, hi2c)
void HAL_I2C_AbortCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, I2C_HandleTypeDef* hi2c);
#define HAL_I2C_GetState_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_GetState_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const I2C_HandleTypeDef* hi2c, HAL_I2C_StateTypeDef cmock_to_return);
#define HAL_I2C_GetMode_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_GetMode_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_GetMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const I2C_HandleTypeDef* hi2c, HAL_I2C_ModeTypeDef cmock_to_return);
#define HAL_I2C_GetError_ExpectAndReturn(hi2c, cmock_retval) HAL_I2C_GetError_CMockExpectAndReturn(__LINE__, hi2c, cmock_retval)
void HAL_I2C_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const I2C_HandleTypeDef* hi2c, uint32_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
