/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STM32H7XX_HAL_SPI_H
#define _MOCK_STM32H7XX_HAL_SPI_H

#include "unity.h"
#include "stm32h747xx.h"
#include "stm32h7xx_hal_conf.h"
#include "stm32h7xx_hal_spi.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_stm32h7xx_hal_spi_Init(void);
void mock_stm32h7xx_hal_spi_Destroy(void);
void mock_stm32h7xx_hal_spi_Verify(void);




#define HAL_SPI_Init_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Init requires _IgnoreAndReturn");
#define HAL_SPI_Init_IgnoreAndReturn(cmock_retval) HAL_SPI_Init_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Init_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Init_StopIgnore() HAL_SPI_Init_CMockStopIgnore()
void HAL_SPI_Init_CMockStopIgnore(void);
#define HAL_SPI_Init_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_Init requires _ExpectAndReturn");
#define HAL_SPI_Init_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_Init_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Init_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_Init_AddCallback(CMOCK_HAL_SPI_Init_CALLBACK Callback);
void HAL_SPI_Init_Stub(CMOCK_HAL_SPI_Init_CALLBACK Callback);
#define HAL_SPI_Init_StubWithCallback HAL_SPI_Init_Stub
#define HAL_SPI_DeInit_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_DeInit requires _IgnoreAndReturn");
#define HAL_SPI_DeInit_IgnoreAndReturn(cmock_retval) HAL_SPI_DeInit_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_DeInit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_DeInit_StopIgnore() HAL_SPI_DeInit_CMockStopIgnore()
void HAL_SPI_DeInit_CMockStopIgnore(void);
#define HAL_SPI_DeInit_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_DeInit requires _ExpectAndReturn");
#define HAL_SPI_DeInit_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_DeInit_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_DeInit_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_DeInit_AddCallback(CMOCK_HAL_SPI_DeInit_CALLBACK Callback);
void HAL_SPI_DeInit_Stub(CMOCK_HAL_SPI_DeInit_CALLBACK Callback);
#define HAL_SPI_DeInit_StubWithCallback HAL_SPI_DeInit_Stub
#define HAL_SPI_MspInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_MspInit requires _Ignore (not AndReturn)");
#define HAL_SPI_MspInit_Ignore() HAL_SPI_MspInit_CMockIgnore()
void HAL_SPI_MspInit_CMockIgnore(void);
#define HAL_SPI_MspInit_StopIgnore() HAL_SPI_MspInit_CMockStopIgnore()
void HAL_SPI_MspInit_CMockStopIgnore(void);
#define HAL_SPI_MspInit_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_MspInit requires _Expect (not AndReturn)");
#define HAL_SPI_MspInit_Expect(hspi) HAL_SPI_MspInit_CMockExpect(__LINE__, hspi)
void HAL_SPI_MspInit_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_MspInit_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_MspInit_AddCallback(CMOCK_HAL_SPI_MspInit_CALLBACK Callback);
void HAL_SPI_MspInit_Stub(CMOCK_HAL_SPI_MspInit_CALLBACK Callback);
#define HAL_SPI_MspInit_StubWithCallback HAL_SPI_MspInit_Stub
#define HAL_SPI_MspDeInit_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_MspDeInit requires _Ignore (not AndReturn)");
#define HAL_SPI_MspDeInit_Ignore() HAL_SPI_MspDeInit_CMockIgnore()
void HAL_SPI_MspDeInit_CMockIgnore(void);
#define HAL_SPI_MspDeInit_StopIgnore() HAL_SPI_MspDeInit_CMockStopIgnore()
void HAL_SPI_MspDeInit_CMockStopIgnore(void);
#define HAL_SPI_MspDeInit_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_MspDeInit requires _Expect (not AndReturn)");
#define HAL_SPI_MspDeInit_Expect(hspi) HAL_SPI_MspDeInit_CMockExpect(__LINE__, hspi)
void HAL_SPI_MspDeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_MspDeInit_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_MspDeInit_AddCallback(CMOCK_HAL_SPI_MspDeInit_CALLBACK Callback);
void HAL_SPI_MspDeInit_Stub(CMOCK_HAL_SPI_MspDeInit_CALLBACK Callback);
#define HAL_SPI_MspDeInit_StubWithCallback HAL_SPI_MspDeInit_Stub
#define HAL_SPI_RegisterCallback_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_RegisterCallback requires _IgnoreAndReturn");
#define HAL_SPI_RegisterCallback_IgnoreAndReturn(cmock_retval) HAL_SPI_RegisterCallback_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_RegisterCallback_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_RegisterCallback_StopIgnore() HAL_SPI_RegisterCallback_CMockStopIgnore()
void HAL_SPI_RegisterCallback_CMockStopIgnore(void);
#define HAL_SPI_RegisterCallback_Expect(hspi, CallbackID, pCallback) TEST_FAIL_MESSAGE("HAL_SPI_RegisterCallback requires _ExpectAndReturn");
#define HAL_SPI_RegisterCallback_ExpectAndReturn(hspi, CallbackID, pCallback, cmock_retval) HAL_SPI_RegisterCallback_CMockExpectAndReturn(__LINE__, hspi, CallbackID, pCallback, cmock_retval)
void HAL_SPI_RegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, pSPI_CallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_RegisterCallback_CALLBACK)(SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, pSPI_CallbackTypeDef pCallback, int cmock_num_calls);
void HAL_SPI_RegisterCallback_AddCallback(CMOCK_HAL_SPI_RegisterCallback_CALLBACK Callback);
void HAL_SPI_RegisterCallback_Stub(CMOCK_HAL_SPI_RegisterCallback_CALLBACK Callback);
#define HAL_SPI_RegisterCallback_StubWithCallback HAL_SPI_RegisterCallback_Stub
#define HAL_SPI_UnRegisterCallback_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_UnRegisterCallback requires _IgnoreAndReturn");
#define HAL_SPI_UnRegisterCallback_IgnoreAndReturn(cmock_retval) HAL_SPI_UnRegisterCallback_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_UnRegisterCallback_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_UnRegisterCallback_StopIgnore() HAL_SPI_UnRegisterCallback_CMockStopIgnore()
void HAL_SPI_UnRegisterCallback_CMockStopIgnore(void);
#define HAL_SPI_UnRegisterCallback_Expect(hspi, CallbackID) TEST_FAIL_MESSAGE("HAL_SPI_UnRegisterCallback requires _ExpectAndReturn");
#define HAL_SPI_UnRegisterCallback_ExpectAndReturn(hspi, CallbackID, cmock_retval) HAL_SPI_UnRegisterCallback_CMockExpectAndReturn(__LINE__, hspi, CallbackID, cmock_retval)
void HAL_SPI_UnRegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_UnRegisterCallback_CALLBACK)(SPI_HandleTypeDef* hspi, HAL_SPI_CallbackIDTypeDef CallbackID, int cmock_num_calls);
void HAL_SPI_UnRegisterCallback_AddCallback(CMOCK_HAL_SPI_UnRegisterCallback_CALLBACK Callback);
void HAL_SPI_UnRegisterCallback_Stub(CMOCK_HAL_SPI_UnRegisterCallback_CALLBACK Callback);
#define HAL_SPI_UnRegisterCallback_StubWithCallback HAL_SPI_UnRegisterCallback_Stub
#define HAL_SPI_Transmit_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Transmit requires _IgnoreAndReturn");
#define HAL_SPI_Transmit_IgnoreAndReturn(cmock_retval) HAL_SPI_Transmit_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Transmit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Transmit_StopIgnore() HAL_SPI_Transmit_CMockStopIgnore()
void HAL_SPI_Transmit_CMockStopIgnore(void);
#define HAL_SPI_Transmit_Expect(hspi, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_SPI_Transmit requires _ExpectAndReturn");
#define HAL_SPI_Transmit_ExpectAndReturn(hspi, pData, Size, Timeout, cmock_retval) HAL_SPI_Transmit_CMockExpectAndReturn(__LINE__, hspi, pData, Size, Timeout, cmock_retval)
void HAL_SPI_Transmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Transmit_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, uint32_t Timeout, int cmock_num_calls);
void HAL_SPI_Transmit_AddCallback(CMOCK_HAL_SPI_Transmit_CALLBACK Callback);
void HAL_SPI_Transmit_Stub(CMOCK_HAL_SPI_Transmit_CALLBACK Callback);
#define HAL_SPI_Transmit_StubWithCallback HAL_SPI_Transmit_Stub
#define HAL_SPI_Receive_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Receive requires _IgnoreAndReturn");
#define HAL_SPI_Receive_IgnoreAndReturn(cmock_retval) HAL_SPI_Receive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Receive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Receive_StopIgnore() HAL_SPI_Receive_CMockStopIgnore()
void HAL_SPI_Receive_CMockStopIgnore(void);
#define HAL_SPI_Receive_Expect(hspi, pData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_SPI_Receive requires _ExpectAndReturn");
#define HAL_SPI_Receive_ExpectAndReturn(hspi, pData, Size, Timeout, cmock_retval) HAL_SPI_Receive_CMockExpectAndReturn(__LINE__, hspi, pData, Size, Timeout, cmock_retval)
void HAL_SPI_Receive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Receive_CALLBACK)(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, uint32_t Timeout, int cmock_num_calls);
void HAL_SPI_Receive_AddCallback(CMOCK_HAL_SPI_Receive_CALLBACK Callback);
void HAL_SPI_Receive_Stub(CMOCK_HAL_SPI_Receive_CALLBACK Callback);
#define HAL_SPI_Receive_StubWithCallback HAL_SPI_Receive_Stub
#define HAL_SPI_TransmitReceive_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_TransmitReceive requires _IgnoreAndReturn");
#define HAL_SPI_TransmitReceive_IgnoreAndReturn(cmock_retval) HAL_SPI_TransmitReceive_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_TransmitReceive_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_TransmitReceive_StopIgnore() HAL_SPI_TransmitReceive_CMockStopIgnore()
void HAL_SPI_TransmitReceive_CMockStopIgnore(void);
#define HAL_SPI_TransmitReceive_Expect(hspi, pTxData, pRxData, Size, Timeout) TEST_FAIL_MESSAGE("HAL_SPI_TransmitReceive requires _ExpectAndReturn");
#define HAL_SPI_TransmitReceive_ExpectAndReturn(hspi, pTxData, pRxData, Size, Timeout, cmock_retval) HAL_SPI_TransmitReceive_CMockExpectAndReturn(__LINE__, hspi, pTxData, pRxData, Size, Timeout, cmock_retval)
void HAL_SPI_TransmitReceive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_TransmitReceive_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, uint32_t Timeout, int cmock_num_calls);
void HAL_SPI_TransmitReceive_AddCallback(CMOCK_HAL_SPI_TransmitReceive_CALLBACK Callback);
void HAL_SPI_TransmitReceive_Stub(CMOCK_HAL_SPI_TransmitReceive_CALLBACK Callback);
#define HAL_SPI_TransmitReceive_StubWithCallback HAL_SPI_TransmitReceive_Stub
#define HAL_SPI_Transmit_IT_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Transmit_IT requires _IgnoreAndReturn");
#define HAL_SPI_Transmit_IT_IgnoreAndReturn(cmock_retval) HAL_SPI_Transmit_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Transmit_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Transmit_IT_StopIgnore() HAL_SPI_Transmit_IT_CMockStopIgnore()
void HAL_SPI_Transmit_IT_CMockStopIgnore(void);
#define HAL_SPI_Transmit_IT_Expect(hspi, pData, Size) TEST_FAIL_MESSAGE("HAL_SPI_Transmit_IT requires _ExpectAndReturn");
#define HAL_SPI_Transmit_IT_ExpectAndReturn(hspi, pData, Size, cmock_retval) HAL_SPI_Transmit_IT_CMockExpectAndReturn(__LINE__, hspi, pData, Size, cmock_retval)
void HAL_SPI_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Transmit_IT_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_Transmit_IT_AddCallback(CMOCK_HAL_SPI_Transmit_IT_CALLBACK Callback);
void HAL_SPI_Transmit_IT_Stub(CMOCK_HAL_SPI_Transmit_IT_CALLBACK Callback);
#define HAL_SPI_Transmit_IT_StubWithCallback HAL_SPI_Transmit_IT_Stub
#define HAL_SPI_Receive_IT_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Receive_IT requires _IgnoreAndReturn");
#define HAL_SPI_Receive_IT_IgnoreAndReturn(cmock_retval) HAL_SPI_Receive_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Receive_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Receive_IT_StopIgnore() HAL_SPI_Receive_IT_CMockStopIgnore()
void HAL_SPI_Receive_IT_CMockStopIgnore(void);
#define HAL_SPI_Receive_IT_Expect(hspi, pData, Size) TEST_FAIL_MESSAGE("HAL_SPI_Receive_IT requires _ExpectAndReturn");
#define HAL_SPI_Receive_IT_ExpectAndReturn(hspi, pData, Size, cmock_retval) HAL_SPI_Receive_IT_CMockExpectAndReturn(__LINE__, hspi, pData, Size, cmock_retval)
void HAL_SPI_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Receive_IT_CALLBACK)(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_Receive_IT_AddCallback(CMOCK_HAL_SPI_Receive_IT_CALLBACK Callback);
void HAL_SPI_Receive_IT_Stub(CMOCK_HAL_SPI_Receive_IT_CALLBACK Callback);
#define HAL_SPI_Receive_IT_StubWithCallback HAL_SPI_Receive_IT_Stub
#define HAL_SPI_TransmitReceive_IT_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_TransmitReceive_IT requires _IgnoreAndReturn");
#define HAL_SPI_TransmitReceive_IT_IgnoreAndReturn(cmock_retval) HAL_SPI_TransmitReceive_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_TransmitReceive_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_TransmitReceive_IT_StopIgnore() HAL_SPI_TransmitReceive_IT_CMockStopIgnore()
void HAL_SPI_TransmitReceive_IT_CMockStopIgnore(void);
#define HAL_SPI_TransmitReceive_IT_Expect(hspi, pTxData, pRxData, Size) TEST_FAIL_MESSAGE("HAL_SPI_TransmitReceive_IT requires _ExpectAndReturn");
#define HAL_SPI_TransmitReceive_IT_ExpectAndReturn(hspi, pTxData, pRxData, Size, cmock_retval) HAL_SPI_TransmitReceive_IT_CMockExpectAndReturn(__LINE__, hspi, pTxData, pRxData, Size, cmock_retval)
void HAL_SPI_TransmitReceive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_TransmitReceive_IT_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_TransmitReceive_IT_AddCallback(CMOCK_HAL_SPI_TransmitReceive_IT_CALLBACK Callback);
void HAL_SPI_TransmitReceive_IT_Stub(CMOCK_HAL_SPI_TransmitReceive_IT_CALLBACK Callback);
#define HAL_SPI_TransmitReceive_IT_StubWithCallback HAL_SPI_TransmitReceive_IT_Stub
#define HAL_SPI_Transmit_DMA_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Transmit_DMA requires _IgnoreAndReturn");
#define HAL_SPI_Transmit_DMA_IgnoreAndReturn(cmock_retval) HAL_SPI_Transmit_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Transmit_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Transmit_DMA_StopIgnore() HAL_SPI_Transmit_DMA_CMockStopIgnore()
void HAL_SPI_Transmit_DMA_CMockStopIgnore(void);
#define HAL_SPI_Transmit_DMA_Expect(hspi, pData, Size) TEST_FAIL_MESSAGE("HAL_SPI_Transmit_DMA requires _ExpectAndReturn");
#define HAL_SPI_Transmit_DMA_ExpectAndReturn(hspi, pData, Size, cmock_retval) HAL_SPI_Transmit_DMA_CMockExpectAndReturn(__LINE__, hspi, pData, Size, cmock_retval)
void HAL_SPI_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Transmit_DMA_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_Transmit_DMA_AddCallback(CMOCK_HAL_SPI_Transmit_DMA_CALLBACK Callback);
void HAL_SPI_Transmit_DMA_Stub(CMOCK_HAL_SPI_Transmit_DMA_CALLBACK Callback);
#define HAL_SPI_Transmit_DMA_StubWithCallback HAL_SPI_Transmit_DMA_Stub
#define HAL_SPI_Receive_DMA_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Receive_DMA requires _IgnoreAndReturn");
#define HAL_SPI_Receive_DMA_IgnoreAndReturn(cmock_retval) HAL_SPI_Receive_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Receive_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Receive_DMA_StopIgnore() HAL_SPI_Receive_DMA_CMockStopIgnore()
void HAL_SPI_Receive_DMA_CMockStopIgnore(void);
#define HAL_SPI_Receive_DMA_Expect(hspi, pData, Size) TEST_FAIL_MESSAGE("HAL_SPI_Receive_DMA requires _ExpectAndReturn");
#define HAL_SPI_Receive_DMA_ExpectAndReturn(hspi, pData, Size, cmock_retval) HAL_SPI_Receive_DMA_CMockExpectAndReturn(__LINE__, hspi, pData, Size, cmock_retval)
void HAL_SPI_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Receive_DMA_CALLBACK)(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_Receive_DMA_AddCallback(CMOCK_HAL_SPI_Receive_DMA_CALLBACK Callback);
void HAL_SPI_Receive_DMA_Stub(CMOCK_HAL_SPI_Receive_DMA_CALLBACK Callback);
#define HAL_SPI_Receive_DMA_StubWithCallback HAL_SPI_Receive_DMA_Stub
#define HAL_SPI_TransmitReceive_DMA_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_TransmitReceive_DMA requires _IgnoreAndReturn");
#define HAL_SPI_TransmitReceive_DMA_IgnoreAndReturn(cmock_retval) HAL_SPI_TransmitReceive_DMA_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_TransmitReceive_DMA_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_TransmitReceive_DMA_StopIgnore() HAL_SPI_TransmitReceive_DMA_CMockStopIgnore()
void HAL_SPI_TransmitReceive_DMA_CMockStopIgnore(void);
#define HAL_SPI_TransmitReceive_DMA_Expect(hspi, pTxData, pRxData, Size) TEST_FAIL_MESSAGE("HAL_SPI_TransmitReceive_DMA requires _ExpectAndReturn");
#define HAL_SPI_TransmitReceive_DMA_ExpectAndReturn(hspi, pTxData, pRxData, Size, cmock_retval) HAL_SPI_TransmitReceive_DMA_CMockExpectAndReturn(__LINE__, hspi, pTxData, pRxData, Size, cmock_retval)
void HAL_SPI_TransmitReceive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_TransmitReceive_DMA_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_TransmitReceive_DMA_AddCallback(CMOCK_HAL_SPI_TransmitReceive_DMA_CALLBACK Callback);
void HAL_SPI_TransmitReceive_DMA_Stub(CMOCK_HAL_SPI_TransmitReceive_DMA_CALLBACK Callback);
#define HAL_SPI_TransmitReceive_DMA_StubWithCallback HAL_SPI_TransmitReceive_DMA_Stub
#define HAL_SPI_Reload_Transmit_IT_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Reload_Transmit_IT requires _IgnoreAndReturn");
#define HAL_SPI_Reload_Transmit_IT_IgnoreAndReturn(cmock_retval) HAL_SPI_Reload_Transmit_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Reload_Transmit_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Reload_Transmit_IT_StopIgnore() HAL_SPI_Reload_Transmit_IT_CMockStopIgnore()
void HAL_SPI_Reload_Transmit_IT_CMockStopIgnore(void);
#define HAL_SPI_Reload_Transmit_IT_Expect(hspi, pData, Size) TEST_FAIL_MESSAGE("HAL_SPI_Reload_Transmit_IT requires _ExpectAndReturn");
#define HAL_SPI_Reload_Transmit_IT_ExpectAndReturn(hspi, pData, Size, cmock_retval) HAL_SPI_Reload_Transmit_IT_CMockExpectAndReturn(__LINE__, hspi, pData, Size, cmock_retval)
void HAL_SPI_Reload_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Reload_Transmit_IT_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_Reload_Transmit_IT_AddCallback(CMOCK_HAL_SPI_Reload_Transmit_IT_CALLBACK Callback);
void HAL_SPI_Reload_Transmit_IT_Stub(CMOCK_HAL_SPI_Reload_Transmit_IT_CALLBACK Callback);
#define HAL_SPI_Reload_Transmit_IT_StubWithCallback HAL_SPI_Reload_Transmit_IT_Stub
#define HAL_SPI_Reload_Receive_IT_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Reload_Receive_IT requires _IgnoreAndReturn");
#define HAL_SPI_Reload_Receive_IT_IgnoreAndReturn(cmock_retval) HAL_SPI_Reload_Receive_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Reload_Receive_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Reload_Receive_IT_StopIgnore() HAL_SPI_Reload_Receive_IT_CMockStopIgnore()
void HAL_SPI_Reload_Receive_IT_CMockStopIgnore(void);
#define HAL_SPI_Reload_Receive_IT_Expect(hspi, pData, Size) TEST_FAIL_MESSAGE("HAL_SPI_Reload_Receive_IT requires _ExpectAndReturn");
#define HAL_SPI_Reload_Receive_IT_ExpectAndReturn(hspi, pData, Size, cmock_retval) HAL_SPI_Reload_Receive_IT_CMockExpectAndReturn(__LINE__, hspi, pData, Size, cmock_retval)
void HAL_SPI_Reload_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Reload_Receive_IT_CALLBACK)(SPI_HandleTypeDef* hspi, uint8_t* pData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_Reload_Receive_IT_AddCallback(CMOCK_HAL_SPI_Reload_Receive_IT_CALLBACK Callback);
void HAL_SPI_Reload_Receive_IT_Stub(CMOCK_HAL_SPI_Reload_Receive_IT_CALLBACK Callback);
#define HAL_SPI_Reload_Receive_IT_StubWithCallback HAL_SPI_Reload_Receive_IT_Stub
#define HAL_SPI_Reload_TransmitReceive_IT_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Reload_TransmitReceive_IT requires _IgnoreAndReturn");
#define HAL_SPI_Reload_TransmitReceive_IT_IgnoreAndReturn(cmock_retval) HAL_SPI_Reload_TransmitReceive_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Reload_TransmitReceive_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Reload_TransmitReceive_IT_StopIgnore() HAL_SPI_Reload_TransmitReceive_IT_CMockStopIgnore()
void HAL_SPI_Reload_TransmitReceive_IT_CMockStopIgnore(void);
#define HAL_SPI_Reload_TransmitReceive_IT_Expect(hspi, pTxData, pRxData, Size) TEST_FAIL_MESSAGE("HAL_SPI_Reload_TransmitReceive_IT requires _ExpectAndReturn");
#define HAL_SPI_Reload_TransmitReceive_IT_ExpectAndReturn(hspi, pTxData, pRxData, Size, cmock_retval) HAL_SPI_Reload_TransmitReceive_IT_CMockExpectAndReturn(__LINE__, hspi, pTxData, pRxData, Size, cmock_retval)
void HAL_SPI_Reload_TransmitReceive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Reload_TransmitReceive_IT_CALLBACK)(SPI_HandleTypeDef* hspi, const uint8_t* pTxData, uint8_t* pRxData, uint16_t Size, int cmock_num_calls);
void HAL_SPI_Reload_TransmitReceive_IT_AddCallback(CMOCK_HAL_SPI_Reload_TransmitReceive_IT_CALLBACK Callback);
void HAL_SPI_Reload_TransmitReceive_IT_Stub(CMOCK_HAL_SPI_Reload_TransmitReceive_IT_CALLBACK Callback);
#define HAL_SPI_Reload_TransmitReceive_IT_StubWithCallback HAL_SPI_Reload_TransmitReceive_IT_Stub
#define HAL_SPI_DMAPause_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_DMAPause requires _IgnoreAndReturn");
#define HAL_SPI_DMAPause_IgnoreAndReturn(cmock_retval) HAL_SPI_DMAPause_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_DMAPause_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_DMAPause_StopIgnore() HAL_SPI_DMAPause_CMockStopIgnore()
void HAL_SPI_DMAPause_CMockStopIgnore(void);
#define HAL_SPI_DMAPause_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_DMAPause requires _ExpectAndReturn");
#define HAL_SPI_DMAPause_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_DMAPause_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_DMAPause_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_DMAPause_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_DMAPause_AddCallback(CMOCK_HAL_SPI_DMAPause_CALLBACK Callback);
void HAL_SPI_DMAPause_Stub(CMOCK_HAL_SPI_DMAPause_CALLBACK Callback);
#define HAL_SPI_DMAPause_StubWithCallback HAL_SPI_DMAPause_Stub
#define HAL_SPI_DMAResume_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_DMAResume requires _IgnoreAndReturn");
#define HAL_SPI_DMAResume_IgnoreAndReturn(cmock_retval) HAL_SPI_DMAResume_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_DMAResume_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_DMAResume_StopIgnore() HAL_SPI_DMAResume_CMockStopIgnore()
void HAL_SPI_DMAResume_CMockStopIgnore(void);
#define HAL_SPI_DMAResume_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_DMAResume requires _ExpectAndReturn");
#define HAL_SPI_DMAResume_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_DMAResume_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_DMAResume_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_DMAResume_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_DMAResume_AddCallback(CMOCK_HAL_SPI_DMAResume_CALLBACK Callback);
void HAL_SPI_DMAResume_Stub(CMOCK_HAL_SPI_DMAResume_CALLBACK Callback);
#define HAL_SPI_DMAResume_StubWithCallback HAL_SPI_DMAResume_Stub
#define HAL_SPI_DMAStop_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_DMAStop requires _IgnoreAndReturn");
#define HAL_SPI_DMAStop_IgnoreAndReturn(cmock_retval) HAL_SPI_DMAStop_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_DMAStop_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_DMAStop_StopIgnore() HAL_SPI_DMAStop_CMockStopIgnore()
void HAL_SPI_DMAStop_CMockStopIgnore(void);
#define HAL_SPI_DMAStop_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_DMAStop requires _ExpectAndReturn");
#define HAL_SPI_DMAStop_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_DMAStop_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_DMAStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_DMAStop_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_DMAStop_AddCallback(CMOCK_HAL_SPI_DMAStop_CALLBACK Callback);
void HAL_SPI_DMAStop_Stub(CMOCK_HAL_SPI_DMAStop_CALLBACK Callback);
#define HAL_SPI_DMAStop_StubWithCallback HAL_SPI_DMAStop_Stub
#define HAL_SPI_Abort_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Abort requires _IgnoreAndReturn");
#define HAL_SPI_Abort_IgnoreAndReturn(cmock_retval) HAL_SPI_Abort_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Abort_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Abort_StopIgnore() HAL_SPI_Abort_CMockStopIgnore()
void HAL_SPI_Abort_CMockStopIgnore(void);
#define HAL_SPI_Abort_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_Abort requires _ExpectAndReturn");
#define HAL_SPI_Abort_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_Abort_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_Abort_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Abort_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_Abort_AddCallback(CMOCK_HAL_SPI_Abort_CALLBACK Callback);
void HAL_SPI_Abort_Stub(CMOCK_HAL_SPI_Abort_CALLBACK Callback);
#define HAL_SPI_Abort_StubWithCallback HAL_SPI_Abort_Stub
#define HAL_SPI_Abort_IT_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_Abort_IT requires _IgnoreAndReturn");
#define HAL_SPI_Abort_IT_IgnoreAndReturn(cmock_retval) HAL_SPI_Abort_IT_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_Abort_IT_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_StatusTypeDef cmock_to_return);
#define HAL_SPI_Abort_IT_StopIgnore() HAL_SPI_Abort_IT_CMockStopIgnore()
void HAL_SPI_Abort_IT_CMockStopIgnore(void);
#define HAL_SPI_Abort_IT_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_Abort_IT requires _ExpectAndReturn");
#define HAL_SPI_Abort_IT_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_Abort_IT_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_Abort_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi, HAL_StatusTypeDef cmock_to_return);
typedef HAL_StatusTypeDef (* CMOCK_HAL_SPI_Abort_IT_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_Abort_IT_AddCallback(CMOCK_HAL_SPI_Abort_IT_CALLBACK Callback);
void HAL_SPI_Abort_IT_Stub(CMOCK_HAL_SPI_Abort_IT_CALLBACK Callback);
#define HAL_SPI_Abort_IT_StubWithCallback HAL_SPI_Abort_IT_Stub
#define HAL_SPI_IRQHandler_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_IRQHandler requires _Ignore (not AndReturn)");
#define HAL_SPI_IRQHandler_Ignore() HAL_SPI_IRQHandler_CMockIgnore()
void HAL_SPI_IRQHandler_CMockIgnore(void);
#define HAL_SPI_IRQHandler_StopIgnore() HAL_SPI_IRQHandler_CMockStopIgnore()
void HAL_SPI_IRQHandler_CMockStopIgnore(void);
#define HAL_SPI_IRQHandler_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_IRQHandler requires _Expect (not AndReturn)");
#define HAL_SPI_IRQHandler_Expect(hspi) HAL_SPI_IRQHandler_CMockExpect(__LINE__, hspi)
void HAL_SPI_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_IRQHandler_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_IRQHandler_AddCallback(CMOCK_HAL_SPI_IRQHandler_CALLBACK Callback);
void HAL_SPI_IRQHandler_Stub(CMOCK_HAL_SPI_IRQHandler_CALLBACK Callback);
#define HAL_SPI_IRQHandler_StubWithCallback HAL_SPI_IRQHandler_Stub
#define HAL_SPI_TxCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxCpltCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_TxCpltCallback_Ignore() HAL_SPI_TxCpltCallback_CMockIgnore()
void HAL_SPI_TxCpltCallback_CMockIgnore(void);
#define HAL_SPI_TxCpltCallback_StopIgnore() HAL_SPI_TxCpltCallback_CMockStopIgnore()
void HAL_SPI_TxCpltCallback_CMockStopIgnore(void);
#define HAL_SPI_TxCpltCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxCpltCallback requires _Expect (not AndReturn)");
#define HAL_SPI_TxCpltCallback_Expect(hspi) HAL_SPI_TxCpltCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_TxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_TxCpltCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_TxCpltCallback_AddCallback(CMOCK_HAL_SPI_TxCpltCallback_CALLBACK Callback);
void HAL_SPI_TxCpltCallback_Stub(CMOCK_HAL_SPI_TxCpltCallback_CALLBACK Callback);
#define HAL_SPI_TxCpltCallback_StubWithCallback HAL_SPI_TxCpltCallback_Stub
#define HAL_SPI_RxCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_RxCpltCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_RxCpltCallback_Ignore() HAL_SPI_RxCpltCallback_CMockIgnore()
void HAL_SPI_RxCpltCallback_CMockIgnore(void);
#define HAL_SPI_RxCpltCallback_StopIgnore() HAL_SPI_RxCpltCallback_CMockStopIgnore()
void HAL_SPI_RxCpltCallback_CMockStopIgnore(void);
#define HAL_SPI_RxCpltCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_RxCpltCallback requires _Expect (not AndReturn)");
#define HAL_SPI_RxCpltCallback_Expect(hspi) HAL_SPI_RxCpltCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_RxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_RxCpltCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_RxCpltCallback_AddCallback(CMOCK_HAL_SPI_RxCpltCallback_CALLBACK Callback);
void HAL_SPI_RxCpltCallback_Stub(CMOCK_HAL_SPI_RxCpltCallback_CALLBACK Callback);
#define HAL_SPI_RxCpltCallback_StubWithCallback HAL_SPI_RxCpltCallback_Stub
#define HAL_SPI_TxRxCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxRxCpltCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_TxRxCpltCallback_Ignore() HAL_SPI_TxRxCpltCallback_CMockIgnore()
void HAL_SPI_TxRxCpltCallback_CMockIgnore(void);
#define HAL_SPI_TxRxCpltCallback_StopIgnore() HAL_SPI_TxRxCpltCallback_CMockStopIgnore()
void HAL_SPI_TxRxCpltCallback_CMockStopIgnore(void);
#define HAL_SPI_TxRxCpltCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxRxCpltCallback requires _Expect (not AndReturn)");
#define HAL_SPI_TxRxCpltCallback_Expect(hspi) HAL_SPI_TxRxCpltCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_TxRxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_TxRxCpltCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_TxRxCpltCallback_AddCallback(CMOCK_HAL_SPI_TxRxCpltCallback_CALLBACK Callback);
void HAL_SPI_TxRxCpltCallback_Stub(CMOCK_HAL_SPI_TxRxCpltCallback_CALLBACK Callback);
#define HAL_SPI_TxRxCpltCallback_StubWithCallback HAL_SPI_TxRxCpltCallback_Stub
#define HAL_SPI_TxHalfCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxHalfCpltCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_TxHalfCpltCallback_Ignore() HAL_SPI_TxHalfCpltCallback_CMockIgnore()
void HAL_SPI_TxHalfCpltCallback_CMockIgnore(void);
#define HAL_SPI_TxHalfCpltCallback_StopIgnore() HAL_SPI_TxHalfCpltCallback_CMockStopIgnore()
void HAL_SPI_TxHalfCpltCallback_CMockStopIgnore(void);
#define HAL_SPI_TxHalfCpltCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxHalfCpltCallback requires _Expect (not AndReturn)");
#define HAL_SPI_TxHalfCpltCallback_Expect(hspi) HAL_SPI_TxHalfCpltCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_TxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_TxHalfCpltCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_TxHalfCpltCallback_AddCallback(CMOCK_HAL_SPI_TxHalfCpltCallback_CALLBACK Callback);
void HAL_SPI_TxHalfCpltCallback_Stub(CMOCK_HAL_SPI_TxHalfCpltCallback_CALLBACK Callback);
#define HAL_SPI_TxHalfCpltCallback_StubWithCallback HAL_SPI_TxHalfCpltCallback_Stub
#define HAL_SPI_RxHalfCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_RxHalfCpltCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_RxHalfCpltCallback_Ignore() HAL_SPI_RxHalfCpltCallback_CMockIgnore()
void HAL_SPI_RxHalfCpltCallback_CMockIgnore(void);
#define HAL_SPI_RxHalfCpltCallback_StopIgnore() HAL_SPI_RxHalfCpltCallback_CMockStopIgnore()
void HAL_SPI_RxHalfCpltCallback_CMockStopIgnore(void);
#define HAL_SPI_RxHalfCpltCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_RxHalfCpltCallback requires _Expect (not AndReturn)");
#define HAL_SPI_RxHalfCpltCallback_Expect(hspi) HAL_SPI_RxHalfCpltCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_RxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_RxHalfCpltCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_RxHalfCpltCallback_AddCallback(CMOCK_HAL_SPI_RxHalfCpltCallback_CALLBACK Callback);
void HAL_SPI_RxHalfCpltCallback_Stub(CMOCK_HAL_SPI_RxHalfCpltCallback_CALLBACK Callback);
#define HAL_SPI_RxHalfCpltCallback_StubWithCallback HAL_SPI_RxHalfCpltCallback_Stub
#define HAL_SPI_TxRxHalfCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxRxHalfCpltCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_TxRxHalfCpltCallback_Ignore() HAL_SPI_TxRxHalfCpltCallback_CMockIgnore()
void HAL_SPI_TxRxHalfCpltCallback_CMockIgnore(void);
#define HAL_SPI_TxRxHalfCpltCallback_StopIgnore() HAL_SPI_TxRxHalfCpltCallback_CMockStopIgnore()
void HAL_SPI_TxRxHalfCpltCallback_CMockStopIgnore(void);
#define HAL_SPI_TxRxHalfCpltCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_TxRxHalfCpltCallback requires _Expect (not AndReturn)");
#define HAL_SPI_TxRxHalfCpltCallback_Expect(hspi) HAL_SPI_TxRxHalfCpltCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_TxRxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_TxRxHalfCpltCallback_AddCallback(CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALLBACK Callback);
void HAL_SPI_TxRxHalfCpltCallback_Stub(CMOCK_HAL_SPI_TxRxHalfCpltCallback_CALLBACK Callback);
#define HAL_SPI_TxRxHalfCpltCallback_StubWithCallback HAL_SPI_TxRxHalfCpltCallback_Stub
#define HAL_SPI_ErrorCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_ErrorCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_ErrorCallback_Ignore() HAL_SPI_ErrorCallback_CMockIgnore()
void HAL_SPI_ErrorCallback_CMockIgnore(void);
#define HAL_SPI_ErrorCallback_StopIgnore() HAL_SPI_ErrorCallback_CMockStopIgnore()
void HAL_SPI_ErrorCallback_CMockStopIgnore(void);
#define HAL_SPI_ErrorCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_ErrorCallback requires _Expect (not AndReturn)");
#define HAL_SPI_ErrorCallback_Expect(hspi) HAL_SPI_ErrorCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_ErrorCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_ErrorCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_ErrorCallback_AddCallback(CMOCK_HAL_SPI_ErrorCallback_CALLBACK Callback);
void HAL_SPI_ErrorCallback_Stub(CMOCK_HAL_SPI_ErrorCallback_CALLBACK Callback);
#define HAL_SPI_ErrorCallback_StubWithCallback HAL_SPI_ErrorCallback_Stub
#define HAL_SPI_AbortCpltCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_AbortCpltCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_AbortCpltCallback_Ignore() HAL_SPI_AbortCpltCallback_CMockIgnore()
void HAL_SPI_AbortCpltCallback_CMockIgnore(void);
#define HAL_SPI_AbortCpltCallback_StopIgnore() HAL_SPI_AbortCpltCallback_CMockStopIgnore()
void HAL_SPI_AbortCpltCallback_CMockStopIgnore(void);
#define HAL_SPI_AbortCpltCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_AbortCpltCallback requires _Expect (not AndReturn)");
#define HAL_SPI_AbortCpltCallback_Expect(hspi) HAL_SPI_AbortCpltCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_AbortCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_AbortCpltCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_AbortCpltCallback_AddCallback(CMOCK_HAL_SPI_AbortCpltCallback_CALLBACK Callback);
void HAL_SPI_AbortCpltCallback_Stub(CMOCK_HAL_SPI_AbortCpltCallback_CALLBACK Callback);
#define HAL_SPI_AbortCpltCallback_StubWithCallback HAL_SPI_AbortCpltCallback_Stub
#define HAL_SPI_SuspendCallback_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_SuspendCallback requires _Ignore (not AndReturn)");
#define HAL_SPI_SuspendCallback_Ignore() HAL_SPI_SuspendCallback_CMockIgnore()
void HAL_SPI_SuspendCallback_CMockIgnore(void);
#define HAL_SPI_SuspendCallback_StopIgnore() HAL_SPI_SuspendCallback_CMockStopIgnore()
void HAL_SPI_SuspendCallback_CMockStopIgnore(void);
#define HAL_SPI_SuspendCallback_ExpectAndReturn(hspi, cmock_retval) TEST_FAIL_MESSAGE("HAL_SPI_SuspendCallback requires _Expect (not AndReturn)");
#define HAL_SPI_SuspendCallback_Expect(hspi) HAL_SPI_SuspendCallback_CMockExpect(__LINE__, hspi)
void HAL_SPI_SuspendCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, SPI_HandleTypeDef* hspi);
typedef void (* CMOCK_HAL_SPI_SuspendCallback_CALLBACK)(SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_SuspendCallback_AddCallback(CMOCK_HAL_SPI_SuspendCallback_CALLBACK Callback);
void HAL_SPI_SuspendCallback_Stub(CMOCK_HAL_SPI_SuspendCallback_CALLBACK Callback);
#define HAL_SPI_SuspendCallback_StubWithCallback HAL_SPI_SuspendCallback_Stub
#define HAL_SPI_GetState_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_GetState requires _IgnoreAndReturn");
#define HAL_SPI_GetState_IgnoreAndReturn(cmock_retval) HAL_SPI_GetState_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_GetState_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, HAL_SPI_StateTypeDef cmock_to_return);
#define HAL_SPI_GetState_StopIgnore() HAL_SPI_GetState_CMockStopIgnore()
void HAL_SPI_GetState_CMockStopIgnore(void);
#define HAL_SPI_GetState_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_GetState requires _ExpectAndReturn");
#define HAL_SPI_GetState_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_GetState_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_HandleTypeDef* hspi, HAL_SPI_StateTypeDef cmock_to_return);
typedef HAL_SPI_StateTypeDef (* CMOCK_HAL_SPI_GetState_CALLBACK)(const SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_GetState_AddCallback(CMOCK_HAL_SPI_GetState_CALLBACK Callback);
void HAL_SPI_GetState_Stub(CMOCK_HAL_SPI_GetState_CALLBACK Callback);
#define HAL_SPI_GetState_StubWithCallback HAL_SPI_GetState_Stub
#define HAL_SPI_GetError_Ignore() TEST_FAIL_MESSAGE("HAL_SPI_GetError requires _IgnoreAndReturn");
#define HAL_SPI_GetError_IgnoreAndReturn(cmock_retval) HAL_SPI_GetError_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void HAL_SPI_GetError_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define HAL_SPI_GetError_StopIgnore() HAL_SPI_GetError_CMockStopIgnore()
void HAL_SPI_GetError_CMockStopIgnore(void);
#define HAL_SPI_GetError_Expect(hspi) TEST_FAIL_MESSAGE("HAL_SPI_GetError requires _ExpectAndReturn");
#define HAL_SPI_GetError_ExpectAndReturn(hspi, cmock_retval) HAL_SPI_GetError_CMockExpectAndReturn(__LINE__, hspi, cmock_retval)
void HAL_SPI_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const SPI_HandleTypeDef* hspi, uint32_t cmock_to_return);
typedef uint32_t (* CMOCK_HAL_SPI_GetError_CALLBACK)(const SPI_HandleTypeDef* hspi, int cmock_num_calls);
void HAL_SPI_GetError_AddCallback(CMOCK_HAL_SPI_GetError_CALLBACK Callback);
void HAL_SPI_GetError_Stub(CMOCK_HAL_SPI_GetError_CALLBACK Callback);
#define HAL_SPI_GetError_StubWithCallback HAL_SPI_GetError_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
