/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STM32H7XX_HAL_DMA_EX_H
#define _MOCK_STM32H7XX_HAL_DMA_EX_H

#include "unity.h"
#include "hal_stub.h"
#include "stm32h7xx_hal_dma_ex.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_stm32h7xx_hal_dma_ex_Init(void);
void mock_stm32h7xx_hal_dma_ex_Destroy(void);
void mock_stm32h7xx_hal_dma_ex_Verify(void);




#define HAL_DMAEx_MultiBufferStart_ExpectAndReturn(hdma, SrcAddress, DstAddress, SecondMemAddress, DataLength, cmock_retval) HAL_DMAEx_MultiBufferStart_CMockExpectAndReturn(__LINE__, hdma, SrcAddress, DstAddress, SecondMemAddress, DataLength, cmock_retval)
void HAL_DMAEx_MultiBufferStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMAEx_MultiBufferStart_IT_ExpectAndReturn(hdma, SrcAddress, DstAddress, SecondMemAddress, DataLength, cmock_retval) HAL_DMAEx_MultiBufferStart_IT_CMockExpectAndReturn(__LINE__, hdma, SrcAddress, DstAddress, SecondMemAddress, DataLength, cmock_retval)
void HAL_DMAEx_MultiBufferStart_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t SecondMemAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMAEx_ChangeMemory_ExpectAndReturn(hdma, Address, memory, cmock_retval) HAL_DMAEx_ChangeMemory_CMockExpectAndReturn(__LINE__, hdma, Address, memory, cmock_retval)
void HAL_DMAEx_ChangeMemory_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t Address, HAL_DMA_MemoryTypeDef memory, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMAEx_ConfigMuxSync_ExpectAndReturn(hdma, pSyncConfig, cmock_retval) HAL_DMAEx_ConfigMuxSync_CMockExpectAndReturn(__LINE__, hdma, pSyncConfig, cmock_retval)
void HAL_DMAEx_ConfigMuxSync_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_MuxSyncConfigTypeDef* pSyncConfig, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMAEx_ConfigMuxRequestGenerator_ExpectAndReturn(hdma, pRequestGeneratorConfig, cmock_retval) HAL_DMAEx_ConfigMuxRequestGenerator_CMockExpectAndReturn(__LINE__, hdma, pRequestGeneratorConfig, cmock_retval)
void HAL_DMAEx_ConfigMuxRequestGenerator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_MuxRequestGeneratorConfigTypeDef* pRequestGeneratorConfig, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMAEx_EnableMuxRequestGenerator_ExpectAndReturn(hdma, cmock_retval) HAL_DMAEx_EnableMuxRequestGenerator_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMAEx_EnableMuxRequestGenerator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMAEx_DisableMuxRequestGenerator_ExpectAndReturn(hdma, cmock_retval) HAL_DMAEx_DisableMuxRequestGenerator_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMAEx_DisableMuxRequestGenerator_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMAEx_MUX_IRQHandler_Expect(hdma) HAL_DMAEx_MUX_IRQHandler_CMockExpect(__LINE__, hdma)
void HAL_DMAEx_MUX_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
