/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_stm32h7xx_hal_dma.h"

static const char* CMockString_CallbackID = "CallbackID";
static const char* CMockString_CompleteLevel = "CompleteLevel";
static const char* CMockString_DataLength = "DataLength";
static const char* CMockString_DstAddress = "DstAddress";
static const char* CMockString_HAL_DMA_Abort = "HAL_DMA_Abort";
static const char* CMockString_HAL_DMA_Abort_IT = "HAL_DMA_Abort_IT";
static const char* CMockString_HAL_DMA_DeInit = "HAL_DMA_DeInit";
static const char* CMockString_HAL_DMA_GetError = "HAL_DMA_GetError";
static const char* CMockString_HAL_DMA_GetState = "HAL_DMA_GetState";
static const char* CMockString_HAL_DMA_IRQHandler = "HAL_DMA_IRQHandler";
static const char* CMockString_HAL_DMA_Init = "HAL_DMA_Init";
static const char* CMockString_HAL_DMA_PollForTransfer = "HAL_DMA_PollForTransfer";
static const char* CMockString_HAL_DMA_RegisterCallback = "HAL_DMA_RegisterCallback";
static const char* CMockString_HAL_DMA_Start = "HAL_DMA_Start";
static const char* CMockString_HAL_DMA_Start_IT = "HAL_DMA_Start_IT";
static const char* CMockString_HAL_DMA_UnRegisterCallback = "HAL_DMA_UnRegisterCallback";
static const char* CMockString_SrcAddress = "SrcAddress";
static const char* CMockString_Timeout = "Timeout";
static const char* CMockString_hdma = "hdma";
static const char* CMockString_pCallback = "pCallback";

typedef struct _CMOCK_HAL_DMA_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMA_Init_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_DeInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMA_DeInit_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_Start_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  uint32_t Expected_SrcAddress;
  uint32_t Expected_DstAddress;
  uint32_t Expected_DataLength;

} CMOCK_HAL_DMA_Start_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  uint32_t Expected_SrcAddress;
  uint32_t Expected_DstAddress;
  uint32_t Expected_DataLength;

} CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_Abort_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMA_Abort_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  HAL_DMA_LevelCompleteTypeDef Expected_CompleteLevel;
  uint32_t Expected_Timeout;

} CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  HAL_DMA_CallbackIDTypeDef Expected_CallbackID;
  cmock_stm32h7xx_hal_dma_func_ptr1 Expected_pCallback;

} CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  DMA_HandleTypeDef* Expected_hdma;
  HAL_DMA_CallbackIDTypeDef Expected_CallbackID;

} CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_GetState_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_DMA_StateTypeDef ReturnVal;
  const DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMA_GetState_CALL_INSTANCE;

typedef struct _CMOCK_HAL_DMA_GetError_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  const DMA_HandleTypeDef* Expected_hdma;

} CMOCK_HAL_DMA_GetError_CALL_INSTANCE;

static struct mock_stm32h7xx_hal_dmaInstance
{
  CMOCK_MEM_INDEX_TYPE HAL_DMA_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_DeInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_Start_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_Start_IT_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_Abort_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_Abort_IT_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_PollForTransfer_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_IRQHandler_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_RegisterCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_UnRegisterCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_GetState_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_DMA_GetError_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_stm32h7xx_hal_dma_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HAL_DMA_Init_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_DeInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_DeInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_Start_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_Start);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_Start_IT_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_Start_IT);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_Abort_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_Abort);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_Abort_IT_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_Abort_IT);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_PollForTransfer_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_PollForTransfer);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_IRQHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_IRQHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_RegisterCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_RegisterCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_UnRegisterCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_UnRegisterCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_GetState_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_GetState);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_DMA_GetError_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_DMA_GetError);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_stm32h7xx_hal_dma_Init(void)
{
  mock_stm32h7xx_hal_dma_Destroy();
}

void mock_stm32h7xx_hal_dma_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

HAL_StatusTypeDef HAL_DMA_Init(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_Init);
  cmock_call_instance = (CMOCK_HAL_DMA_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_Init_CallInstance);
  Mock.HAL_DMA_Init_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Init,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_Init(CMOCK_HAL_DMA_Init_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMA_Init(CMOCK_HAL_DMA_Init_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMA_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_Init_CALL_INSTANCE));
  CMOCK_HAL_DMA_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_Init_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_Init(cmock_call_instance, hdma);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMA_DeInit(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_DeInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_DeInit);
  cmock_call_instance = (CMOCK_HAL_DMA_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_DeInit_CallInstance);
  Mock.HAL_DMA_DeInit_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_DeInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_DeInit,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_DeInit(CMOCK_HAL_DMA_DeInit_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMA_DeInit(CMOCK_HAL_DMA_DeInit_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMA_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_DeInit_CALL_INSTANCE));
  CMOCK_HAL_DMA_DeInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_DeInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_DeInit_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_DeInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_DeInit(cmock_call_instance, hdma);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMA_Start(DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_Start_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_Start);
  cmock_call_instance = (CMOCK_HAL_DMA_Start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_Start_CallInstance);
  Mock.HAL_DMA_Start_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_Start_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start,CMockString_SrcAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SrcAddress, SrcAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start,CMockString_DstAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DstAddress, DstAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start,CMockString_DataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DataLength, DataLength, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_Start(CMOCK_HAL_DMA_Start_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength);
void CMockExpectParameters_HAL_DMA_Start(CMOCK_HAL_DMA_Start_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength)
{
  cmock_call_instance->Expected_hdma = hdma;
  cmock_call_instance->Expected_SrcAddress = SrcAddress;
  cmock_call_instance->Expected_DstAddress = DstAddress;
  cmock_call_instance->Expected_DataLength = DataLength;
}

void HAL_DMA_Start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_Start_CALL_INSTANCE));
  CMOCK_HAL_DMA_Start_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_Start_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_Start_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_Start_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_Start(cmock_call_instance, hdma, SrcAddress, DstAddress, DataLength);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMA_Start_IT(DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_Start_IT);
  cmock_call_instance = (CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_Start_IT_CallInstance);
  Mock.HAL_DMA_Start_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_Start_IT_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start_IT,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start_IT,CMockString_SrcAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SrcAddress, SrcAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start_IT,CMockString_DstAddress);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DstAddress, DstAddress, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Start_IT,CMockString_DataLength);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_DataLength, DataLength, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_Start_IT(CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength);
void CMockExpectParameters_HAL_DMA_Start_IT(CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength)
{
  cmock_call_instance->Expected_hdma = hdma;
  cmock_call_instance->Expected_SrcAddress = SrcAddress;
  cmock_call_instance->Expected_DstAddress = DstAddress;
  cmock_call_instance->Expected_DataLength = DataLength;
}

void HAL_DMA_Start_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE));
  CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_Start_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_Start_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_Start_IT_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_Start_IT(cmock_call_instance, hdma, SrcAddress, DstAddress, DataLength);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMA_Abort(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_Abort_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_Abort);
  cmock_call_instance = (CMOCK_HAL_DMA_Abort_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_Abort_CallInstance);
  Mock.HAL_DMA_Abort_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_Abort_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Abort,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_Abort(CMOCK_HAL_DMA_Abort_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMA_Abort(CMOCK_HAL_DMA_Abort_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMA_Abort_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_Abort_CALL_INSTANCE));
  CMOCK_HAL_DMA_Abort_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_Abort_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_Abort_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_Abort_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_Abort(cmock_call_instance, hdma);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMA_Abort_IT(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_Abort_IT);
  cmock_call_instance = (CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_Abort_IT_CallInstance);
  Mock.HAL_DMA_Abort_IT_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_Abort_IT_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_Abort_IT,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_Abort_IT(CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMA_Abort_IT(CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMA_Abort_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE));
  CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_Abort_IT_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_Abort_IT_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_Abort_IT_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_Abort_IT(cmock_call_instance, hdma);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMA_PollForTransfer(DMA_HandleTypeDef* hdma, HAL_DMA_LevelCompleteTypeDef CompleteLevel, uint32_t Timeout)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_PollForTransfer);
  cmock_call_instance = (CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_PollForTransfer_CallInstance);
  Mock.HAL_DMA_PollForTransfer_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_PollForTransfer_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_PollForTransfer,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_PollForTransfer,CMockString_CompleteLevel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_CompleteLevel), (void*)(&CompleteLevel), sizeof(HAL_DMA_LevelCompleteTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_PollForTransfer,CMockString_Timeout);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Timeout, Timeout, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_PollForTransfer(CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_LevelCompleteTypeDef CompleteLevel, uint32_t Timeout);
void CMockExpectParameters_HAL_DMA_PollForTransfer(CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_LevelCompleteTypeDef CompleteLevel, uint32_t Timeout)
{
  cmock_call_instance->Expected_hdma = hdma;
  memcpy((void*)(&cmock_call_instance->Expected_CompleteLevel), (void*)(&CompleteLevel),
         sizeof(HAL_DMA_LevelCompleteTypeDef[sizeof(CompleteLevel) == sizeof(HAL_DMA_LevelCompleteTypeDef) ? 1 : -1])); /* add HAL_DMA_LevelCompleteTypeDef to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_Timeout = Timeout;
}

void HAL_DMA_PollForTransfer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_LevelCompleteTypeDef CompleteLevel, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE));
  CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_PollForTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_PollForTransfer_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_PollForTransfer_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_PollForTransfer(cmock_call_instance, hdma, CompleteLevel, Timeout);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_DMA_IRQHandler(DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_IRQHandler);
  cmock_call_instance = (CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_IRQHandler_CallInstance);
  Mock.HAL_DMA_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_IRQHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_IRQHandler,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_DMA_IRQHandler(CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMA_IRQHandler(CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMA_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE));
  CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_IRQHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_IRQHandler(cmock_call_instance, hdma);
}

HAL_StatusTypeDef HAL_DMA_RegisterCallback(DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID, cmock_stm32h7xx_hal_dma_func_ptr1 pCallback)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_RegisterCallback);
  cmock_call_instance = (CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_RegisterCallback_CallInstance);
  Mock.HAL_DMA_RegisterCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_RegisterCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_RegisterCallback,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_RegisterCallback,CMockString_CallbackID);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID), sizeof(HAL_DMA_CallbackIDTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_RegisterCallback,CMockString_pCallback);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_pCallback, pCallback, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_RegisterCallback(CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID, cmock_stm32h7xx_hal_dma_func_ptr1 pCallback);
void CMockExpectParameters_HAL_DMA_RegisterCallback(CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID, cmock_stm32h7xx_hal_dma_func_ptr1 pCallback)
{
  cmock_call_instance->Expected_hdma = hdma;
  memcpy((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID),
         sizeof(HAL_DMA_CallbackIDTypeDef[sizeof(CallbackID) == sizeof(HAL_DMA_CallbackIDTypeDef) ? 1 : -1])); /* add HAL_DMA_CallbackIDTypeDef to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_pCallback), (void*)(&pCallback),
         sizeof(cmock_stm32h7xx_hal_dma_func_ptr1[sizeof(pCallback) == sizeof(cmock_stm32h7xx_hal_dma_func_ptr1) ? 1 : -1])); /* add cmock_stm32h7xx_hal_dma_func_ptr1 to :treat_as_array if this causes an error */
}

void HAL_DMA_RegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID, cmock_stm32h7xx_hal_dma_func_ptr1 pCallback, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE));
  CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_RegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_RegisterCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_RegisterCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_RegisterCallback(cmock_call_instance, hdma, CallbackID, pCallback);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_DMA_UnRegisterCallback(DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_UnRegisterCallback);
  cmock_call_instance = (CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_UnRegisterCallback_CallInstance);
  Mock.HAL_DMA_UnRegisterCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_UnRegisterCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_UnRegisterCallback,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_UnRegisterCallback,CMockString_CallbackID);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID), sizeof(HAL_DMA_CallbackIDTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_UnRegisterCallback(CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID);
void CMockExpectParameters_HAL_DMA_UnRegisterCallback(CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE* cmock_call_instance, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID)
{
  cmock_call_instance->Expected_hdma = hdma;
  memcpy((void*)(&cmock_call_instance->Expected_CallbackID), (void*)(&CallbackID),
         sizeof(HAL_DMA_CallbackIDTypeDef[sizeof(CallbackID) == sizeof(HAL_DMA_CallbackIDTypeDef) ? 1 : -1])); /* add HAL_DMA_CallbackIDTypeDef to :treat_as_array if this causes an error */
}

void HAL_DMA_UnRegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE));
  CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_UnRegisterCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_UnRegisterCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_UnRegisterCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_UnRegisterCallback(cmock_call_instance, hdma, CallbackID);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_DMA_StateTypeDef HAL_DMA_GetState(const DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_GetState_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_GetState);
  cmock_call_instance = (CMOCK_HAL_DMA_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_GetState_CallInstance);
  Mock.HAL_DMA_GetState_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_GetState_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_GetState,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(const DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_GetState(CMOCK_HAL_DMA_GetState_CALL_INSTANCE* cmock_call_instance, const DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMA_GetState(CMOCK_HAL_DMA_GetState_CALL_INSTANCE* cmock_call_instance, const DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMA_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DMA_HandleTypeDef* hdma, HAL_DMA_StateTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_GetState_CALL_INSTANCE));
  CMOCK_HAL_DMA_GetState_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_GetState_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_GetState_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_GetState_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_GetState(cmock_call_instance, hdma);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_DMA_StateTypeDef[sizeof(cmock_to_return) == sizeof(HAL_DMA_StateTypeDef) ? 1 : -1])); /* add HAL_DMA_StateTypeDef to :treat_as_array if this causes an error */
}

uint32_t HAL_DMA_GetError(const DMA_HandleTypeDef* hdma)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_DMA_GetError_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_DMA_GetError);
  cmock_call_instance = (CMOCK_HAL_DMA_GetError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_DMA_GetError_CallInstance);
  Mock.HAL_DMA_GetError_CallInstance = CMock_Guts_MemNext(Mock.HAL_DMA_GetError_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_DMA_GetError,CMockString_hdma);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_hdma), (void*)(hdma), sizeof(const DMA_HandleTypeDef), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_DMA_GetError(CMOCK_HAL_DMA_GetError_CALL_INSTANCE* cmock_call_instance, const DMA_HandleTypeDef* hdma);
void CMockExpectParameters_HAL_DMA_GetError(CMOCK_HAL_DMA_GetError_CALL_INSTANCE* cmock_call_instance, const DMA_HandleTypeDef* hdma)
{
  cmock_call_instance->Expected_hdma = hdma;
}

void HAL_DMA_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DMA_HandleTypeDef* hdma, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_DMA_GetError_CALL_INSTANCE));
  CMOCK_HAL_DMA_GetError_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_DMA_GetError_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_DMA_GetError_CallInstance = CMock_Guts_MemChain(Mock.HAL_DMA_GetError_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_DMA_GetError(cmock_call_instance, hdma);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

