/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_mag.h"

static const char* CMockString_MagGetActiveDevice = "MagGetActiveDevice";
static const char* CMockString_MagInit = "MagInit";
static const char* CMockString_MagStart = "MagStart";
static const char* CMockString_MagStop = "MagStop";
static const char* CMockString_Mag_GetMutableActiveDevice = "Mag_GetMutableActiveDevice";
static const char* CMockString_Mag_Update = "Mag_Update";
static const char* CMockString_conf = "conf";
static const char* CMockString_forcePolling = "forcePolling";
static const char* CMockString_pBusOverride = "pBusOverride";
static const char* CMockString_pMag = "pMag";
static const char* CMockString_pOutMag = "pOutMag";
static const char* CMockString_pOutput = "pOutput";

typedef struct _CMOCK_MagInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eMAG_STATUS_t ReturnVal;
  MagInitConf_t Expected_conf;
  Mag_t* Expected_pOutMag;
  BusVTable_t* Expected_pBusOverride;

} CMOCK_MagInit_CALL_INSTANCE;

typedef struct _CMOCK_MagStart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eMAG_STATUS_t ReturnVal;
  vMag_t* Expected_pMag;

} CMOCK_MagStart_CALL_INSTANCE;

typedef struct _CMOCK_MagStop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eMAG_STATUS_t ReturnVal;
  vMag_t* Expected_pMag;

} CMOCK_MagStop_CALL_INSTANCE;

typedef struct _CMOCK_Mag_Update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eMAG_STATUS_t ReturnVal;
  vMag_t* Expected_pMag;
  bool Expected_forcePolling;
  Vec3f* Expected_pOutput;

} CMOCK_Mag_Update_CALL_INSTANCE;

typedef struct _CMOCK_MagGetActiveDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  vMag_t const* ReturnVal;

} CMOCK_MagGetActiveDevice_CALL_INSTANCE;

typedef struct _CMOCK_Mag_GetMutableActiveDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  vMag_t* ReturnVal;

} CMOCK_Mag_GetMutableActiveDevice_CALL_INSTANCE;

static struct mock_magInstance
{
  CMOCK_MEM_INDEX_TYPE MagInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE MagStart_CallInstance;
  CMOCK_MEM_INDEX_TYPE MagStop_CallInstance;
  CMOCK_MEM_INDEX_TYPE Mag_Update_CallInstance;
  CMOCK_MEM_INDEX_TYPE MagGetActiveDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE Mag_GetMutableActiveDevice_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_mag_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.MagInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MagInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.MagStart_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MagStart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.MagStop_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MagStop);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.Mag_Update_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Mag_Update);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.MagGetActiveDevice_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_MagGetActiveDevice);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.Mag_GetMutableActiveDevice_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Mag_GetMutableActiveDevice);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_mag_Init(void)
{
  mock_mag_Destroy();
}

void mock_mag_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

eMAG_STATUS_t MagInit(MagInitConf_t conf, Mag_t* pOutMag, BusVTable_t* pBusOverride)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MagInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MagInit);
  cmock_call_instance = (CMOCK_MagInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MagInit_CallInstance);
  Mock.MagInit_CallInstance = CMock_Guts_MemNext(Mock.MagInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_MagInit,CMockString_conf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf), sizeof(MagInitConf_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_MagInit,CMockString_pOutMag);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutMag), (void*)(pOutMag), sizeof(Mag_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_MagInit,CMockString_pBusOverride);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pBusOverride), (void*)(pBusOverride), sizeof(BusVTable_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MagInit(CMOCK_MagInit_CALL_INSTANCE* cmock_call_instance, MagInitConf_t conf, Mag_t* pOutMag, BusVTable_t* pBusOverride);
void CMockExpectParameters_MagInit(CMOCK_MagInit_CALL_INSTANCE* cmock_call_instance, MagInitConf_t conf, Mag_t* pOutMag, BusVTable_t* pBusOverride)
{
  memcpy((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf),
         sizeof(MagInitConf_t[sizeof(conf) == sizeof(MagInitConf_t) ? 1 : -1])); /* add MagInitConf_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_pOutMag = pOutMag;
  cmock_call_instance->Expected_pBusOverride = pBusOverride;
}

void MagInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, MagInitConf_t conf, Mag_t* pOutMag, BusVTable_t* pBusOverride, eMAG_STATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MagInit_CALL_INSTANCE));
  CMOCK_MagInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_MagInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MagInit_CallInstance = CMock_Guts_MemChain(Mock.MagInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_MagInit(cmock_call_instance, conf, pOutMag, pBusOverride);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eMAG_STATUS_t[sizeof(cmock_to_return) == sizeof(eMAG_STATUS_t) ? 1 : -1])); /* add eMAG_STATUS_t to :treat_as_array if this causes an error */
}

eMAG_STATUS_t MagStart(vMag_t* pMag)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MagStart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MagStart);
  cmock_call_instance = (CMOCK_MagStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MagStart_CallInstance);
  Mock.MagStart_CallInstance = CMock_Guts_MemNext(Mock.MagStart_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_MagStart,CMockString_pMag);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMag), (void*)(pMag), sizeof(vMag_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MagStart(CMOCK_MagStart_CALL_INSTANCE* cmock_call_instance, vMag_t* pMag);
void CMockExpectParameters_MagStart(CMOCK_MagStart_CALL_INSTANCE* cmock_call_instance, vMag_t* pMag)
{
  cmock_call_instance->Expected_pMag = pMag;
}

void MagStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vMag_t* pMag, eMAG_STATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MagStart_CALL_INSTANCE));
  CMOCK_MagStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_MagStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MagStart_CallInstance = CMock_Guts_MemChain(Mock.MagStart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_MagStart(cmock_call_instance, pMag);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eMAG_STATUS_t[sizeof(cmock_to_return) == sizeof(eMAG_STATUS_t) ? 1 : -1])); /* add eMAG_STATUS_t to :treat_as_array if this causes an error */
}

eMAG_STATUS_t MagStop(vMag_t* pMag)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MagStop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MagStop);
  cmock_call_instance = (CMOCK_MagStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MagStop_CallInstance);
  Mock.MagStop_CallInstance = CMock_Guts_MemNext(Mock.MagStop_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_MagStop,CMockString_pMag);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMag), (void*)(pMag), sizeof(vMag_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_MagStop(CMOCK_MagStop_CALL_INSTANCE* cmock_call_instance, vMag_t* pMag);
void CMockExpectParameters_MagStop(CMOCK_MagStop_CALL_INSTANCE* cmock_call_instance, vMag_t* pMag)
{
  cmock_call_instance->Expected_pMag = pMag;
}

void MagStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vMag_t* pMag, eMAG_STATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MagStop_CALL_INSTANCE));
  CMOCK_MagStop_CALL_INSTANCE* cmock_call_instance = (CMOCK_MagStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MagStop_CallInstance = CMock_Guts_MemChain(Mock.MagStop_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_MagStop(cmock_call_instance, pMag);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eMAG_STATUS_t[sizeof(cmock_to_return) == sizeof(eMAG_STATUS_t) ? 1 : -1])); /* add eMAG_STATUS_t to :treat_as_array if this causes an error */
}

eMAG_STATUS_t Mag_Update(vMag_t* pMag, bool forcePolling, Vec3f* pOutput)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Mag_Update_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Mag_Update);
  cmock_call_instance = (CMOCK_Mag_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Mag_Update_CallInstance);
  Mock.Mag_Update_CallInstance = CMock_Guts_MemNext(Mock.Mag_Update_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Mag_Update,CMockString_pMag);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pMag), (void*)(pMag), sizeof(vMag_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Mag_Update,CMockString_forcePolling);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_forcePolling, forcePolling, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_Mag_Update,CMockString_pOutput);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutput), (void*)(pOutput), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_Mag_Update(CMOCK_Mag_Update_CALL_INSTANCE* cmock_call_instance, vMag_t* pMag, bool forcePolling, Vec3f* pOutput);
void CMockExpectParameters_Mag_Update(CMOCK_Mag_Update_CALL_INSTANCE* cmock_call_instance, vMag_t* pMag, bool forcePolling, Vec3f* pOutput)
{
  cmock_call_instance->Expected_pMag = pMag;
  cmock_call_instance->Expected_forcePolling = forcePolling;
  cmock_call_instance->Expected_pOutput = pOutput;
}

void Mag_Update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vMag_t* pMag, bool forcePolling, Vec3f* pOutput, eMAG_STATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Mag_Update_CALL_INSTANCE));
  CMOCK_Mag_Update_CALL_INSTANCE* cmock_call_instance = (CMOCK_Mag_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Mag_Update_CallInstance = CMock_Guts_MemChain(Mock.Mag_Update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Mag_Update(cmock_call_instance, pMag, forcePolling, pOutput);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eMAG_STATUS_t[sizeof(cmock_to_return) == sizeof(eMAG_STATUS_t) ? 1 : -1])); /* add eMAG_STATUS_t to :treat_as_array if this causes an error */
}

vMag_t const* MagGetActiveDevice(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MagGetActiveDevice_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_MagGetActiveDevice);
  cmock_call_instance = (CMOCK_MagGetActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.MagGetActiveDevice_CallInstance);
  Mock.MagGetActiveDevice_CallInstance = CMock_Guts_MemNext(Mock.MagGetActiveDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void MagGetActiveDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vMag_t const* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_MagGetActiveDevice_CALL_INSTANCE));
  CMOCK_MagGetActiveDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_MagGetActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.MagGetActiveDevice_CallInstance = CMock_Guts_MemChain(Mock.MagGetActiveDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

vMag_t* Mag_GetMutableActiveDevice(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Mag_GetMutableActiveDevice_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Mag_GetMutableActiveDevice);
  cmock_call_instance = (CMOCK_Mag_GetMutableActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Mag_GetMutableActiveDevice_CallInstance);
  Mock.Mag_GetMutableActiveDevice_CallInstance = CMock_Guts_MemNext(Mock.Mag_GetMutableActiveDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void Mag_GetMutableActiveDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vMag_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Mag_GetMutableActiveDevice_CALL_INSTANCE));
  CMOCK_Mag_GetMutableActiveDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_Mag_GetMutableActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Mag_GetMutableActiveDevice_CallInstance = CMock_Guts_MemChain(Mock.Mag_GetMutableActiveDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

