/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STM32H7XX_HAL_DMA_H
#define _MOCK_STM32H7XX_HAL_DMA_H

#include "unity.h"
#include "hal_stub.h"
#include "stm32h7xx_hal_dma.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_stm32h7xx_hal_dma_Init(void);
void mock_stm32h7xx_hal_dma_Destroy(void);
void mock_stm32h7xx_hal_dma_Verify(void);


typedef void(*cmock_stm32h7xx_hal_dma_func_ptr1)(DMA_HandleTypeDef* _hdma);


#define HAL_DMA_Init_ExpectAndReturn(hdma, cmock_retval) HAL_DMA_Init_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMA_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_DeInit_ExpectAndReturn(hdma, cmock_retval) HAL_DMA_DeInit_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMA_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_Start_ExpectAndReturn(hdma, SrcAddress, DstAddress, DataLength, cmock_retval) HAL_DMA_Start_CMockExpectAndReturn(__LINE__, hdma, SrcAddress, DstAddress, DataLength, cmock_retval)
void HAL_DMA_Start_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_Start_IT_ExpectAndReturn(hdma, SrcAddress, DstAddress, DataLength, cmock_retval) HAL_DMA_Start_IT_CMockExpectAndReturn(__LINE__, hdma, SrcAddress, DstAddress, DataLength, cmock_retval)
void HAL_DMA_Start_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, uint32_t SrcAddress, uint32_t DstAddress, uint32_t DataLength, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_Abort_ExpectAndReturn(hdma, cmock_retval) HAL_DMA_Abort_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMA_Abort_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_Abort_IT_ExpectAndReturn(hdma, cmock_retval) HAL_DMA_Abort_IT_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMA_Abort_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_PollForTransfer_ExpectAndReturn(hdma, CompleteLevel, Timeout, cmock_retval) HAL_DMA_PollForTransfer_CMockExpectAndReturn(__LINE__, hdma, CompleteLevel, Timeout, cmock_retval)
void HAL_DMA_PollForTransfer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_LevelCompleteTypeDef CompleteLevel, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_IRQHandler_Expect(hdma) HAL_DMA_IRQHandler_CMockExpect(__LINE__, hdma)
void HAL_DMA_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma);
#define HAL_DMA_RegisterCallback_ExpectAndReturn(hdma, CallbackID, pCallback, cmock_retval) HAL_DMA_RegisterCallback_CMockExpectAndReturn(__LINE__, hdma, CallbackID, pCallback, cmock_retval)
void HAL_DMA_RegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID, cmock_stm32h7xx_hal_dma_func_ptr1 pCallback, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_UnRegisterCallback_ExpectAndReturn(hdma, CallbackID, cmock_retval) HAL_DMA_UnRegisterCallback_CMockExpectAndReturn(__LINE__, hdma, CallbackID, cmock_retval)
void HAL_DMA_UnRegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DMA_HandleTypeDef* hdma, HAL_DMA_CallbackIDTypeDef CallbackID, HAL_StatusTypeDef cmock_to_return);
#define HAL_DMA_GetState_ExpectAndReturn(hdma, cmock_retval) HAL_DMA_GetState_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMA_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DMA_HandleTypeDef* hdma, HAL_DMA_StateTypeDef cmock_to_return);
#define HAL_DMA_GetError_ExpectAndReturn(hdma, cmock_retval) HAL_DMA_GetError_CMockExpectAndReturn(__LINE__, hdma, cmock_retval)
void HAL_DMA_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const DMA_HandleTypeDef* hdma, uint32_t cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
