/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_FILTER_H
#define _MOCK_FILTER_H

#include "unity.h"
#include "hal_stub.h"
#include "filter.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_filter_Init(void);
void mock_filter_Destroy(void);
void mock_filter_Verify(void);




#define FilterMadgwickInit_ExpectAndReturn(conf, pOut, cmock_retval) FilterMadgwickInit_CMockExpectAndReturn(__LINE__, conf, pOut, cmock_retval)
void FilterMadgwickInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwickInitConf_t conf, FilterMadgwick_t* pOut, bool cmock_to_return);
#define FilterMadgwickUpdate_ExpectAndReturn(pFilter, pAccel, pGyro, pMag, dt, pOutAttitude, cmock_retval) FilterMadgwickUpdate_CMockExpectAndReturn(__LINE__, pFilter, pAccel, pGyro, pMag, dt, pOutAttitude, cmock_retval)
void FilterMadgwickUpdate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutAttitude, bool cmock_to_return);
#define FilterMadgwickUpdate_6DOF_ExpectAndReturn(pFilter, pAccel, pGyroDegs, dt, cmock_retval) FilterMadgwickUpdate_6DOF_CMockExpectAndReturn(__LINE__, pFilter, pAccel, pGyroDegs, dt, cmock_retval)
void FilterMadgwickUpdate_6DOF_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyroDegs, float dt, bool cmock_to_return);
#define FilterMadgwickUpdate_9DOF_ExpectAndReturn(pFilter, pAccel, pGyro, pMag, dt, cmock_retval) FilterMadgwickUpdate_9DOF_CMockExpectAndReturn(__LINE__, pFilter, pAccel, pGyro, pMag, dt, cmock_retval)
void FilterMadgwickUpdate_9DOF_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterMadgwick_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, bool cmock_to_return);
#define FilterInit_ExpectAndReturn(conf, pOut, cmock_retval) FilterInit_CMockExpectAndReturn(__LINE__, conf, pOut, cmock_retval)
void FilterInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, FilterInitConf_t conf, Filter_t* pOut, eSTATUS_t cmock_to_return);
#define FilterStart_ExpectAndReturn(pFilter, warmUpIterations, pOutAttitude, cmock_retval) FilterStart_CMockExpectAndReturn(__LINE__, pFilter, warmUpIterations, pOutAttitude, cmock_retval)
void FilterStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* pFilter, uint32_t warmUpIterations, Vec3f* pOutAttitude, eSTATUS_t cmock_to_return);
#define FilterStop_ExpectAndReturn(pFilter, cmock_retval) FilterStop_CMockExpectAndReturn(__LINE__, pFilter, cmock_retval)
void FilterStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* pFilter, eSTATUS_t cmock_to_return);
#define Filter_Update_ExpectAndReturn(pFilter, pAccel, pGyro, pMag, dt, pOutput, cmock_retval) Filter_Update_CMockExpectAndReturn(__LINE__, pFilter, pAccel, pGyro, pMag, dt, pOutput, cmock_retval)
void Filter_Update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* pFilter, Vec3f const* pAccel, Vec3f const* pGyro, Vec3f const* pMag, float dt, Vec3f* pOutput, eSTATUS_t cmock_to_return);
#define FilterGetActiveFilter_ExpectAndReturn(cmock_retval) FilterGetActiveFilter_CMockExpectAndReturn(__LINE__, cmock_retval)
void FilterGetActiveFilter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t const* cmock_to_return);
#define Filter_GetMutableActiveFilter_ExpectAndReturn(cmock_retval) Filter_GetMutableActiveFilter_CMockExpectAndReturn(__LINE__, cmock_retval)
void Filter_GetMutableActiveFilter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vFilter_t* cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
