/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_imu.h"

static const char* CMockString_IMU2CPUInterruptHandler = "IMU2CPUInterruptHandler";
static const char* CMockString_IMUCalibrate = "IMUCalibrate";
static const char* CMockString_IMUCompareConfs = "IMUCompareConfs";
static const char* CMockString_IMUConvertRaw = "IMUConvertRaw";
static const char* CMockString_IMUDisableInterrupts = "IMUDisableInterrupts";
static const char* CMockString_IMUEnableInterrupts = "IMUEnableInterrupts";
static const char* CMockString_IMUGetActiveDevice = "IMUGetActiveDevice";
static const char* CMockString_IMUGetAltConf = "IMUGetAltConf";
static const char* CMockString_IMUGetConf = "IMUGetConf";
static const char* CMockString_IMUGetConf_ = "IMUGetConf_";
static const char* CMockString_IMUGetFeatureStatus = "IMUGetFeatureStatus";
static const char* CMockString_IMUGetINTStatus = "IMUGetINTStatus";
static const char* CMockString_IMUGetSysStatus = "IMUGetSysStatus";
static const char* CMockString_IMUHandleErr = "IMUHandleErr";
static const char* CMockString_IMUInit = "IMUInit";
static const char* CMockString_IMUReadReg = "IMUReadReg";
static const char* CMockString_IMUSendCmd = "IMUSendCmd";
static const char* CMockString_IMUSetAltConf = "IMUSetAltConf";
static const char* CMockString_IMUSetAxesRemap = "IMUSetAxesRemap";
static const char* CMockString_IMUSetConf = "IMUSetConf";
static const char* CMockString_IMUSetConf_ = "IMUSetConf_";
static const char* CMockString_IMUSetupInterrupts = "IMUSetupInterrupts";
static const char* CMockString_IMUSoftReset = "IMUSoftReset";
static const char* CMockString_IMUStart = "IMUStart";
static const char* CMockString_IMUStop = "IMUStop";
static const char* CMockString_IMUUpdateRawAccel = "IMUUpdateRawAccel";
static const char* CMockString_IMUUpdateRawGyro = "IMUUpdateRawGyro";
static const char* CMockString_IMUWriteReg = "IMUWriteReg";
static const char* CMockString_IMU_GetMutableActiveDevice = "IMU_GetMutableActiveDevice";
static const char* CMockString_IMU_Update = "IMU_Update";
static const char* CMockString_aRange = "aRange";
static const char* CMockString_aconf = "aconf";
static const char* CMockString_aconf2 = "aconf2";
static const char* CMockString_altConfFlag = "altConfFlag";
static const char* CMockString_applyCorrection = "applyCorrection";
static const char* CMockString_calibSelection = "calibSelection";
static const char* CMockString_cmd = "cmd";
static const char* CMockString_cmock_arg1 = "cmock_arg1";
static const char* CMockString_conf = "conf";
static const char* CMockString_featureRegAddr = "featureRegAddr";
static const char* CMockString_forcePolling = "forcePolling";
static const char* CMockString_gRange = "gRange";
static const char* CMockString_gconf = "gconf";
static const char* CMockString_gconf2 = "gconf2";
static const char* CMockString_len = "len";
static const char* CMockString_pAConf = "pAConf";
static const char* CMockString_pAccelOut = "pAccelOut";
static const char* CMockString_pBuf = "pBuf";
static const char* CMockString_pBusOverride = "pBusOverride";
static const char* CMockString_pGConf = "pGConf";
static const char* CMockString_pGyroOut = "pGyroOut";
static const char* CMockString_pIMU = "pIMU";
static const char* CMockString_pOutIMU = "pOutIMU";
static const char* CMockString_pOutStatus = "pOutStatus";
static const char* CMockString_pOutputAccel = "pOutputAccel";
static const char* CMockString_pOutputGyro = "pOutputGyro";
static const char* CMockString_ra = "ra";
static const char* CMockString_reg = "reg";
static const char* CMockString_remap = "remap";
static const char* CMockString_rg = "rg";

typedef struct _CMOCK_IMUSendCmd_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;
  uint16_t Expected_cmd;

} CMOCK_IMUSendCmd_CALL_INSTANCE;

typedef struct _CMOCK_IMUGetFeatureStatus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;
  uint16_t Expected_featureRegAddr;
  IMU_FeatureReg_t* Expected_pOutStatus;

} CMOCK_IMUGetFeatureStatus_CALL_INSTANCE;

typedef struct _CMOCK_IMUGetINTStatus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;
  IMU_INTStatusReg_t* Expected_cmock_arg1;

} CMOCK_IMUGetINTStatus_CALL_INSTANCE;

typedef struct _CMOCK_IMUGetSysStatus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;
  IMU_SysStatusReg_t* Expected_pOutStatus;

} CMOCK_IMUGetSysStatus_CALL_INSTANCE;

typedef struct _CMOCK_IMUReadReg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;
  uint8_t Expected_reg;
  uint8_t* Expected_pBuf;
  uint32_t Expected_len;

} CMOCK_IMUReadReg_CALL_INSTANCE;

typedef struct _CMOCK_IMUWriteReg_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;
  uint8_t Expected_reg;
  uint8_t* Expected_pBuf;
  uint32_t Expected_len;

} CMOCK_IMUWriteReg_CALL_INSTANCE;

typedef struct _CMOCK_IMUUpdateRawGyro_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;

} CMOCK_IMUUpdateRawGyro_CALL_INSTANCE;

typedef struct _CMOCK_IMUUpdateRawAccel_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;

} CMOCK_IMUUpdateRawAccel_CALL_INSTANCE;

typedef struct _CMOCK_IMUSetAxesRemap_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  IMUAxesRemapConf Expected_remap;

} CMOCK_IMUSetAxesRemap_CALL_INSTANCE;

typedef struct _CMOCK_IMUSoftReset_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;

} CMOCK_IMUSoftReset_CALL_INSTANCE;

typedef struct _CMOCK_IMUGetConf__CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  IMUAccConf* Expected_pAConf;
  IMUGyroConf* Expected_pGConf;
  uint8_t Expected_altConfFlag;

} CMOCK_IMUGetConf__CALL_INSTANCE;

typedef struct _CMOCK_IMUSetConf__CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  IMUAccConf const* Expected_pAConf;
  IMUGyroConf const* Expected_pGConf;
  uint8_t Expected_altConfFlag;

} CMOCK_IMUSetConf__CALL_INSTANCE;

typedef struct _CMOCK_IMUCalibrate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  uint8_t Expected_calibSelection;
  uint8_t Expected_applyCorrection;

} CMOCK_IMUCalibrate_CALL_INSTANCE;

typedef struct _CMOCK_IMUSetupInterrupts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;

} CMOCK_IMUSetupInterrupts_CALL_INSTANCE;

typedef struct _CMOCK_IMUEnableInterrupts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;

} CMOCK_IMUEnableInterrupts_CALL_INSTANCE;

typedef struct _CMOCK_IMUDisableInterrupts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t const* Expected_pIMU;

} CMOCK_IMUDisableInterrupts_CALL_INSTANCE;

typedef struct _CMOCK_IMUConvertRaw_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  IMU_ACC_RANGE Expected_aRange;
  Vec3i Expected_ra;
  IMU_GYRO_RANGE Expected_gRange;
  Vec3i Expected_rg;
  Vec3f* Expected_pAccelOut;
  Vec3f* Expected_pGyroOut;

} CMOCK_IMUConvertRaw_CALL_INSTANCE;

typedef struct _CMOCK_IMUInit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  IMUInitConf_t Expected_conf;
  IMU_t* Expected_pOutIMU;
  BusVTable_t* Expected_pBusOverride;

} CMOCK_IMUInit_CALL_INSTANCE;

typedef struct _CMOCK_IMUStart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;

} CMOCK_IMUStart_CALL_INSTANCE;

typedef struct _CMOCK_IMUStop_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;

} CMOCK_IMUStop_CALL_INSTANCE;

typedef struct _CMOCK_IMUHandleErr_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;

} CMOCK_IMUHandleErr_CALL_INSTANCE;

typedef struct _CMOCK_IMU_Update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  bool Expected_forcePolling;
  Vec3f* Expected_pOutputAccel;
  Vec3f* Expected_pOutputGyro;

} CMOCK_IMU_Update_CALL_INSTANCE;

typedef struct _CMOCK_IMUGetConf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  IMUAccConf* Expected_pAConf;
  IMUGyroConf* Expected_pGConf;

} CMOCK_IMUGetConf_CALL_INSTANCE;

typedef struct _CMOCK_IMUGetAltConf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  IMUAccConf* Expected_pAConf;
  IMUGyroConf* Expected_pGConf;

} CMOCK_IMUGetAltConf_CALL_INSTANCE;

typedef struct _CMOCK_IMUSetConf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  IMUAccConf const* Expected_pAConf;
  IMUGyroConf const* Expected_pGConf;

} CMOCK_IMUSetConf_CALL_INSTANCE;

typedef struct _CMOCK_IMUSetAltConf_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  vIMU_t* Expected_pIMU;
  IMUAccConf const* Expected_pAConf;
  IMUGyroConf const* Expected_pGConf;

} CMOCK_IMUSetAltConf_CALL_INSTANCE;

typedef struct _CMOCK_IMUCompareConfs_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  eSTATUS_t ReturnVal;
  IMUAccConf Expected_aconf;
  IMUGyroConf Expected_gconf;
  IMUAccConf Expected_aconf2;
  IMUGyroConf Expected_gconf2;

} CMOCK_IMUCompareConfs_CALL_INSTANCE;

typedef struct _CMOCK_IMUGetActiveDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  vIMU_t const* ReturnVal;

} CMOCK_IMUGetActiveDevice_CALL_INSTANCE;

typedef struct _CMOCK_IMU_GetMutableActiveDevice_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  vIMU_t* ReturnVal;

} CMOCK_IMU_GetMutableActiveDevice_CALL_INSTANCE;

typedef struct _CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  vIMU_t* Expected_pIMU;

} CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE;

static struct mock_imuInstance
{
  CMOCK_MEM_INDEX_TYPE IMUSendCmd_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUGetFeatureStatus_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUGetINTStatus_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUGetSysStatus_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUReadReg_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUWriteReg_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUUpdateRawGyro_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUUpdateRawAccel_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUSetAxesRemap_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUSoftReset_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUGetConf__CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUSetConf__CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUCalibrate_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUSetupInterrupts_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUEnableInterrupts_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUDisableInterrupts_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUConvertRaw_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUInit_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUStart_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUStop_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUHandleErr_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMU_Update_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUGetConf_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUGetAltConf_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUSetConf_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUSetAltConf_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUCompareConfs_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMUGetActiveDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMU_GetMutableActiveDevice_CallInstance;
  CMOCK_MEM_INDEX_TYPE IMU2CPUInterruptHandler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_imu_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.IMUSendCmd_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUSendCmd);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUGetFeatureStatus_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUGetFeatureStatus);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUGetINTStatus_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUGetINTStatus);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUGetSysStatus_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUGetSysStatus);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUReadReg_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUReadReg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUWriteReg_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUWriteReg);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUUpdateRawGyro_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUUpdateRawGyro);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUUpdateRawAccel_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUUpdateRawAccel);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUSetAxesRemap_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUSetAxesRemap);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUSoftReset_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUSoftReset);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUGetConf__CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUGetConf_);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUSetConf__CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUSetConf_);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUCalibrate_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUCalibrate);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUSetupInterrupts_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUSetupInterrupts);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUEnableInterrupts_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUEnableInterrupts);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUDisableInterrupts_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUDisableInterrupts);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUConvertRaw_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUConvertRaw);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUInit_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUInit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUStart_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUStart);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUStop_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUStop);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUHandleErr_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUHandleErr);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMU_Update_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMU_Update);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUGetConf_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUGetConf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUGetAltConf_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUGetAltConf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUSetConf_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUSetConf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUSetAltConf_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUSetAltConf);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUCompareConfs_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUCompareConfs);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMUGetActiveDevice_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMUGetActiveDevice);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMU_GetMutableActiveDevice_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMU_GetMutableActiveDevice);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.IMU2CPUInterruptHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IMU2CPUInterruptHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_imu_Init(void)
{
  mock_imu_Destroy();
}

void mock_imu_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

eSTATUS_t IMUSendCmd(vIMU_t const* pIMU, uint16_t cmd)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUSendCmd_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUSendCmd);
  cmock_call_instance = (CMOCK_IMUSendCmd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUSendCmd_CallInstance);
  Mock.IMUSendCmd_CallInstance = CMock_Guts_MemNext(Mock.IMUSendCmd_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUSendCmd,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSendCmd,CMockString_cmd);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_cmd, cmd, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUSendCmd(CMOCK_IMUSendCmd_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint16_t cmd);
void CMockExpectParameters_IMUSendCmd(CMOCK_IMUSendCmd_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint16_t cmd)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_cmd = cmd;
}

void IMUSendCmd_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, uint16_t cmd, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUSendCmd_CALL_INSTANCE));
  CMOCK_IMUSendCmd_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUSendCmd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUSendCmd_CallInstance = CMock_Guts_MemChain(Mock.IMUSendCmd_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUSendCmd(cmock_call_instance, pIMU, cmd);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUGetFeatureStatus(vIMU_t const* pIMU, uint16_t featureRegAddr, IMU_FeatureReg_t* pOutStatus)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUGetFeatureStatus_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUGetFeatureStatus);
  cmock_call_instance = (CMOCK_IMUGetFeatureStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUGetFeatureStatus_CallInstance);
  Mock.IMUGetFeatureStatus_CallInstance = CMock_Guts_MemNext(Mock.IMUGetFeatureStatus_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUGetFeatureStatus,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetFeatureStatus,CMockString_featureRegAddr);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_featureRegAddr, featureRegAddr, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetFeatureStatus,CMockString_pOutStatus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutStatus), (void*)(pOutStatus), sizeof(IMU_FeatureReg_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUGetFeatureStatus(CMOCK_IMUGetFeatureStatus_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint16_t featureRegAddr, IMU_FeatureReg_t* pOutStatus);
void CMockExpectParameters_IMUGetFeatureStatus(CMOCK_IMUGetFeatureStatus_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint16_t featureRegAddr, IMU_FeatureReg_t* pOutStatus)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_featureRegAddr = featureRegAddr;
  cmock_call_instance->Expected_pOutStatus = pOutStatus;
}

void IMUGetFeatureStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, uint16_t featureRegAddr, IMU_FeatureReg_t* pOutStatus, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUGetFeatureStatus_CALL_INSTANCE));
  CMOCK_IMUGetFeatureStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUGetFeatureStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUGetFeatureStatus_CallInstance = CMock_Guts_MemChain(Mock.IMUGetFeatureStatus_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUGetFeatureStatus(cmock_call_instance, pIMU, featureRegAddr, pOutStatus);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUGetINTStatus(vIMU_t const* pIMU, IMU_INTStatusReg_t* cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUGetINTStatus_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUGetINTStatus);
  cmock_call_instance = (CMOCK_IMUGetINTStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUGetINTStatus_CallInstance);
  Mock.IMUGetINTStatus_CallInstance = CMock_Guts_MemNext(Mock.IMUGetINTStatus_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUGetINTStatus,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetINTStatus,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_cmock_arg1), (void*)(cmock_arg1), sizeof(IMU_INTStatusReg_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUGetINTStatus(CMOCK_IMUGetINTStatus_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, IMU_INTStatusReg_t* cmock_arg1);
void CMockExpectParameters_IMUGetINTStatus(CMOCK_IMUGetINTStatus_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, IMU_INTStatusReg_t* cmock_arg1)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_cmock_arg1 = cmock_arg1;
}

void IMUGetINTStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, IMU_INTStatusReg_t* cmock_arg1, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUGetINTStatus_CALL_INSTANCE));
  CMOCK_IMUGetINTStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUGetINTStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUGetINTStatus_CallInstance = CMock_Guts_MemChain(Mock.IMUGetINTStatus_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUGetINTStatus(cmock_call_instance, pIMU, cmock_arg1);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUGetSysStatus(vIMU_t const* pIMU, IMU_SysStatusReg_t* pOutStatus)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUGetSysStatus_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUGetSysStatus);
  cmock_call_instance = (CMOCK_IMUGetSysStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUGetSysStatus_CallInstance);
  Mock.IMUGetSysStatus_CallInstance = CMock_Guts_MemNext(Mock.IMUGetSysStatus_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUGetSysStatus,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetSysStatus,CMockString_pOutStatus);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutStatus), (void*)(pOutStatus), sizeof(IMU_SysStatusReg_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUGetSysStatus(CMOCK_IMUGetSysStatus_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, IMU_SysStatusReg_t* pOutStatus);
void CMockExpectParameters_IMUGetSysStatus(CMOCK_IMUGetSysStatus_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, IMU_SysStatusReg_t* pOutStatus)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_pOutStatus = pOutStatus;
}

void IMUGetSysStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, IMU_SysStatusReg_t* pOutStatus, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUGetSysStatus_CALL_INSTANCE));
  CMOCK_IMUGetSysStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUGetSysStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUGetSysStatus_CallInstance = CMock_Guts_MemChain(Mock.IMUGetSysStatus_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUGetSysStatus(cmock_call_instance, pIMU, pOutStatus);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUReadReg(vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUReadReg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUReadReg);
  cmock_call_instance = (CMOCK_IMUReadReg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUReadReg_CallInstance);
  Mock.IMUReadReg_CallInstance = CMock_Guts_MemNext(Mock.IMUReadReg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUReadReg,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUReadReg,CMockString_reg);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_reg, reg, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUReadReg,CMockString_pBuf);
    if (cmock_call_instance->Expected_pBuf == NULL)
      { UNITY_TEST_ASSERT_NULL(pBuf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pBuf, pBuf, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUReadReg,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUReadReg(CMOCK_IMUReadReg_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len);
void CMockExpectParameters_IMUReadReg(CMOCK_IMUReadReg_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_reg = reg;
  cmock_call_instance->Expected_pBuf = pBuf;
  cmock_call_instance->Expected_len = len;
}

void IMUReadReg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUReadReg_CALL_INSTANCE));
  CMOCK_IMUReadReg_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUReadReg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUReadReg_CallInstance = CMock_Guts_MemChain(Mock.IMUReadReg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUReadReg(cmock_call_instance, pIMU, reg, pBuf, len);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUWriteReg(vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUWriteReg_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUWriteReg);
  cmock_call_instance = (CMOCK_IMUWriteReg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUWriteReg_CallInstance);
  Mock.IMUWriteReg_CallInstance = CMock_Guts_MemNext(Mock.IMUWriteReg_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUWriteReg,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUWriteReg,CMockString_reg);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_reg, reg, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUWriteReg,CMockString_pBuf);
    if (cmock_call_instance->Expected_pBuf == NULL)
      { UNITY_TEST_ASSERT_NULL(pBuf, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_pBuf, pBuf, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUWriteReg,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUWriteReg(CMOCK_IMUWriteReg_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len);
void CMockExpectParameters_IMUWriteReg(CMOCK_IMUWriteReg_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_reg = reg;
  cmock_call_instance->Expected_pBuf = pBuf;
  cmock_call_instance->Expected_len = len;
}

void IMUWriteReg_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, uint8_t reg, uint8_t* pBuf, uint32_t len, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUWriteReg_CALL_INSTANCE));
  CMOCK_IMUWriteReg_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUWriteReg_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUWriteReg_CallInstance = CMock_Guts_MemChain(Mock.IMUWriteReg_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUWriteReg(cmock_call_instance, pIMU, reg, pBuf, len);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUUpdateRawGyro(vIMU_t* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUUpdateRawGyro_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUUpdateRawGyro);
  cmock_call_instance = (CMOCK_IMUUpdateRawGyro_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUUpdateRawGyro_CallInstance);
  Mock.IMUUpdateRawGyro_CallInstance = CMock_Guts_MemNext(Mock.IMUUpdateRawGyro_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUUpdateRawGyro,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUUpdateRawGyro(CMOCK_IMUUpdateRawGyro_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU);
void CMockExpectParameters_IMUUpdateRawGyro(CMOCK_IMUUpdateRawGyro_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUUpdateRawGyro_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUUpdateRawGyro_CALL_INSTANCE));
  CMOCK_IMUUpdateRawGyro_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUUpdateRawGyro_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUUpdateRawGyro_CallInstance = CMock_Guts_MemChain(Mock.IMUUpdateRawGyro_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUUpdateRawGyro(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUUpdateRawAccel(vIMU_t* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUUpdateRawAccel_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUUpdateRawAccel);
  cmock_call_instance = (CMOCK_IMUUpdateRawAccel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUUpdateRawAccel_CallInstance);
  Mock.IMUUpdateRawAccel_CallInstance = CMock_Guts_MemNext(Mock.IMUUpdateRawAccel_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUUpdateRawAccel,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUUpdateRawAccel(CMOCK_IMUUpdateRawAccel_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU);
void CMockExpectParameters_IMUUpdateRawAccel(CMOCK_IMUUpdateRawAccel_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUUpdateRawAccel_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUUpdateRawAccel_CALL_INSTANCE));
  CMOCK_IMUUpdateRawAccel_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUUpdateRawAccel_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUUpdateRawAccel_CallInstance = CMock_Guts_MemChain(Mock.IMUUpdateRawAccel_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUUpdateRawAccel(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUSetAxesRemap(vIMU_t* pIMU, IMUAxesRemapConf remap)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUSetAxesRemap_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUSetAxesRemap);
  cmock_call_instance = (CMOCK_IMUSetAxesRemap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUSetAxesRemap_CallInstance);
  Mock.IMUSetAxesRemap_CallInstance = CMock_Guts_MemNext(Mock.IMUSetAxesRemap_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUSetAxesRemap,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetAxesRemap,CMockString_remap);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_remap), (void*)(&remap), sizeof(IMUAxesRemapConf), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUSetAxesRemap(CMOCK_IMUSetAxesRemap_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAxesRemapConf remap);
void CMockExpectParameters_IMUSetAxesRemap(CMOCK_IMUSetAxesRemap_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAxesRemapConf remap)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  memcpy((void*)(&cmock_call_instance->Expected_remap), (void*)(&remap),
         sizeof(IMUAxesRemapConf[sizeof(remap) == sizeof(IMUAxesRemapConf) ? 1 : -1])); /* add IMUAxesRemapConf to :treat_as_array if this causes an error */
}

void IMUSetAxesRemap_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAxesRemapConf remap, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUSetAxesRemap_CALL_INSTANCE));
  CMOCK_IMUSetAxesRemap_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUSetAxesRemap_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUSetAxesRemap_CallInstance = CMock_Guts_MemChain(Mock.IMUSetAxesRemap_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUSetAxesRemap(cmock_call_instance, pIMU, remap);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUSoftReset(vIMU_t* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUSoftReset_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUSoftReset);
  cmock_call_instance = (CMOCK_IMUSoftReset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUSoftReset_CallInstance);
  Mock.IMUSoftReset_CallInstance = CMock_Guts_MemNext(Mock.IMUSoftReset_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUSoftReset,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUSoftReset(CMOCK_IMUSoftReset_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU);
void CMockExpectParameters_IMUSoftReset(CMOCK_IMUSoftReset_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUSoftReset_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUSoftReset_CALL_INSTANCE));
  CMOCK_IMUSoftReset_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUSoftReset_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUSoftReset_CallInstance = CMock_Guts_MemChain(Mock.IMUSoftReset_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUSoftReset(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUGetConf_(vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, uint8_t altConfFlag)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUGetConf__CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUGetConf_);
  cmock_call_instance = (CMOCK_IMUGetConf__CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUGetConf__CallInstance);
  Mock.IMUGetConf__CallInstance = CMock_Guts_MemNext(Mock.IMUGetConf__CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUGetConf_,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetConf_,CMockString_pAConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAConf), (void*)(pAConf), sizeof(IMUAccConf), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetConf_,CMockString_pGConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGConf), (void*)(pGConf), sizeof(IMUGyroConf), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetConf_,CMockString_altConfFlag);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_altConfFlag, altConfFlag, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUGetConf_(CMOCK_IMUGetConf__CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, uint8_t altConfFlag);
void CMockExpectParameters_IMUGetConf_(CMOCK_IMUGetConf__CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, uint8_t altConfFlag)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_pAConf = pAConf;
  cmock_call_instance->Expected_pGConf = pGConf;
  cmock_call_instance->Expected_altConfFlag = altConfFlag;
}

void IMUGetConf__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, uint8_t altConfFlag, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUGetConf__CALL_INSTANCE));
  CMOCK_IMUGetConf__CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUGetConf__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUGetConf__CallInstance = CMock_Guts_MemChain(Mock.IMUGetConf__CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUGetConf_(cmock_call_instance, pIMU, pAConf, pGConf, altConfFlag);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUSetConf_(vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf, uint8_t altConfFlag)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUSetConf__CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUSetConf_);
  cmock_call_instance = (CMOCK_IMUSetConf__CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUSetConf__CallInstance);
  Mock.IMUSetConf__CallInstance = CMock_Guts_MemNext(Mock.IMUSetConf__CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUSetConf_,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetConf_,CMockString_pAConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAConf), (void*)(pAConf), sizeof(IMUAccConf const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetConf_,CMockString_pGConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGConf), (void*)(pGConf), sizeof(IMUGyroConf const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetConf_,CMockString_altConfFlag);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_altConfFlag, altConfFlag, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUSetConf_(CMOCK_IMUSetConf__CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf, uint8_t altConfFlag);
void CMockExpectParameters_IMUSetConf_(CMOCK_IMUSetConf__CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf, uint8_t altConfFlag)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_pAConf = pAConf;
  cmock_call_instance->Expected_pGConf = pGConf;
  cmock_call_instance->Expected_altConfFlag = altConfFlag;
}

void IMUSetConf__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf, uint8_t altConfFlag, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUSetConf__CALL_INSTANCE));
  CMOCK_IMUSetConf__CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUSetConf__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUSetConf__CallInstance = CMock_Guts_MemChain(Mock.IMUSetConf__CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUSetConf_(cmock_call_instance, pIMU, pAConf, pGConf, altConfFlag);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUCalibrate(vIMU_t* pIMU, uint8_t calibSelection, uint8_t applyCorrection)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUCalibrate_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUCalibrate);
  cmock_call_instance = (CMOCK_IMUCalibrate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUCalibrate_CallInstance);
  Mock.IMUCalibrate_CallInstance = CMock_Guts_MemNext(Mock.IMUCalibrate_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUCalibrate,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUCalibrate,CMockString_calibSelection);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_calibSelection, calibSelection, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUCalibrate,CMockString_applyCorrection);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_applyCorrection, applyCorrection, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUCalibrate(CMOCK_IMUCalibrate_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, uint8_t calibSelection, uint8_t applyCorrection);
void CMockExpectParameters_IMUCalibrate(CMOCK_IMUCalibrate_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, uint8_t calibSelection, uint8_t applyCorrection)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_calibSelection = calibSelection;
  cmock_call_instance->Expected_applyCorrection = applyCorrection;
}

void IMUCalibrate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, uint8_t calibSelection, uint8_t applyCorrection, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUCalibrate_CALL_INSTANCE));
  CMOCK_IMUCalibrate_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUCalibrate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUCalibrate_CallInstance = CMock_Guts_MemChain(Mock.IMUCalibrate_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUCalibrate(cmock_call_instance, pIMU, calibSelection, applyCorrection);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUSetupInterrupts(vIMU_t const* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUSetupInterrupts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUSetupInterrupts);
  cmock_call_instance = (CMOCK_IMUSetupInterrupts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUSetupInterrupts_CallInstance);
  Mock.IMUSetupInterrupts_CallInstance = CMock_Guts_MemNext(Mock.IMUSetupInterrupts_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUSetupInterrupts,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUSetupInterrupts(CMOCK_IMUSetupInterrupts_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU);
void CMockExpectParameters_IMUSetupInterrupts(CMOCK_IMUSetupInterrupts_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUSetupInterrupts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUSetupInterrupts_CALL_INSTANCE));
  CMOCK_IMUSetupInterrupts_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUSetupInterrupts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUSetupInterrupts_CallInstance = CMock_Guts_MemChain(Mock.IMUSetupInterrupts_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUSetupInterrupts(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUEnableInterrupts(vIMU_t const* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUEnableInterrupts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUEnableInterrupts);
  cmock_call_instance = (CMOCK_IMUEnableInterrupts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUEnableInterrupts_CallInstance);
  Mock.IMUEnableInterrupts_CallInstance = CMock_Guts_MemNext(Mock.IMUEnableInterrupts_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUEnableInterrupts,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUEnableInterrupts(CMOCK_IMUEnableInterrupts_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU);
void CMockExpectParameters_IMUEnableInterrupts(CMOCK_IMUEnableInterrupts_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUEnableInterrupts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUEnableInterrupts_CALL_INSTANCE));
  CMOCK_IMUEnableInterrupts_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUEnableInterrupts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUEnableInterrupts_CallInstance = CMock_Guts_MemChain(Mock.IMUEnableInterrupts_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUEnableInterrupts(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUDisableInterrupts(vIMU_t const* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUDisableInterrupts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUDisableInterrupts);
  cmock_call_instance = (CMOCK_IMUDisableInterrupts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUDisableInterrupts_CallInstance);
  Mock.IMUDisableInterrupts_CallInstance = CMock_Guts_MemNext(Mock.IMUDisableInterrupts_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUDisableInterrupts,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t const), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUDisableInterrupts(CMOCK_IMUDisableInterrupts_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU);
void CMockExpectParameters_IMUDisableInterrupts(CMOCK_IMUDisableInterrupts_CALL_INSTANCE* cmock_call_instance, vIMU_t const* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUDisableInterrupts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUDisableInterrupts_CALL_INSTANCE));
  CMOCK_IMUDisableInterrupts_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUDisableInterrupts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUDisableInterrupts_CallInstance = CMock_Guts_MemChain(Mock.IMUDisableInterrupts_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUDisableInterrupts(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUConvertRaw(IMU_ACC_RANGE aRange, Vec3i ra, IMU_GYRO_RANGE gRange, Vec3i rg, Vec3f* pAccelOut, Vec3f* pGyroOut)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUConvertRaw_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUConvertRaw);
  cmock_call_instance = (CMOCK_IMUConvertRaw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUConvertRaw_CallInstance);
  Mock.IMUConvertRaw_CallInstance = CMock_Guts_MemNext(Mock.IMUConvertRaw_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUConvertRaw,CMockString_aRange);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_aRange), (void*)(&aRange), sizeof(IMU_ACC_RANGE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUConvertRaw,CMockString_ra);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ra), (void*)(&ra), sizeof(Vec3i), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUConvertRaw,CMockString_gRange);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gRange), (void*)(&gRange), sizeof(IMU_GYRO_RANGE), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUConvertRaw,CMockString_rg);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_rg), (void*)(&rg), sizeof(Vec3i), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUConvertRaw,CMockString_pAccelOut);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAccelOut), (void*)(pAccelOut), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUConvertRaw,CMockString_pGyroOut);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGyroOut), (void*)(pGyroOut), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUConvertRaw(CMOCK_IMUConvertRaw_CALL_INSTANCE* cmock_call_instance, IMU_ACC_RANGE aRange, Vec3i ra, IMU_GYRO_RANGE gRange, Vec3i rg, Vec3f* pAccelOut, Vec3f* pGyroOut);
void CMockExpectParameters_IMUConvertRaw(CMOCK_IMUConvertRaw_CALL_INSTANCE* cmock_call_instance, IMU_ACC_RANGE aRange, Vec3i ra, IMU_GYRO_RANGE gRange, Vec3i rg, Vec3f* pAccelOut, Vec3f* pGyroOut)
{
  memcpy((void*)(&cmock_call_instance->Expected_aRange), (void*)(&aRange),
         sizeof(IMU_ACC_RANGE[sizeof(aRange) == sizeof(IMU_ACC_RANGE) ? 1 : -1])); /* add IMU_ACC_RANGE to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_ra), (void*)(&ra),
         sizeof(Vec3i[sizeof(ra) == sizeof(Vec3i) ? 1 : -1])); /* add Vec3i to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_gRange), (void*)(&gRange),
         sizeof(IMU_GYRO_RANGE[sizeof(gRange) == sizeof(IMU_GYRO_RANGE) ? 1 : -1])); /* add IMU_GYRO_RANGE to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_rg), (void*)(&rg),
         sizeof(Vec3i[sizeof(rg) == sizeof(Vec3i) ? 1 : -1])); /* add Vec3i to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_pAccelOut = pAccelOut;
  cmock_call_instance->Expected_pGyroOut = pGyroOut;
}

void IMUConvertRaw_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, IMU_ACC_RANGE aRange, Vec3i ra, IMU_GYRO_RANGE gRange, Vec3i rg, Vec3f* pAccelOut, Vec3f* pGyroOut, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUConvertRaw_CALL_INSTANCE));
  CMOCK_IMUConvertRaw_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUConvertRaw_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUConvertRaw_CallInstance = CMock_Guts_MemChain(Mock.IMUConvertRaw_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUConvertRaw(cmock_call_instance, aRange, ra, gRange, rg, pAccelOut, pGyroOut);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUInit(IMUInitConf_t conf, IMU_t* pOutIMU, BusVTable_t* pBusOverride)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUInit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUInit);
  cmock_call_instance = (CMOCK_IMUInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUInit_CallInstance);
  Mock.IMUInit_CallInstance = CMock_Guts_MemNext(Mock.IMUInit_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUInit,CMockString_conf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf), sizeof(IMUInitConf_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUInit,CMockString_pOutIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutIMU), (void*)(pOutIMU), sizeof(IMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUInit,CMockString_pBusOverride);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pBusOverride), (void*)(pBusOverride), sizeof(BusVTable_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUInit(CMOCK_IMUInit_CALL_INSTANCE* cmock_call_instance, IMUInitConf_t conf, IMU_t* pOutIMU, BusVTable_t* pBusOverride);
void CMockExpectParameters_IMUInit(CMOCK_IMUInit_CALL_INSTANCE* cmock_call_instance, IMUInitConf_t conf, IMU_t* pOutIMU, BusVTable_t* pBusOverride)
{
  memcpy((void*)(&cmock_call_instance->Expected_conf), (void*)(&conf),
         sizeof(IMUInitConf_t[sizeof(conf) == sizeof(IMUInitConf_t) ? 1 : -1])); /* add IMUInitConf_t to :treat_as_array if this causes an error */
  cmock_call_instance->Expected_pOutIMU = pOutIMU;
  cmock_call_instance->Expected_pBusOverride = pBusOverride;
}

void IMUInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, IMUInitConf_t conf, IMU_t* pOutIMU, BusVTable_t* pBusOverride, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUInit_CALL_INSTANCE));
  CMOCK_IMUInit_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUInit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUInit_CallInstance = CMock_Guts_MemChain(Mock.IMUInit_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUInit(cmock_call_instance, conf, pOutIMU, pBusOverride);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUStart(vIMU_t* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUStart_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUStart);
  cmock_call_instance = (CMOCK_IMUStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUStart_CallInstance);
  Mock.IMUStart_CallInstance = CMock_Guts_MemNext(Mock.IMUStart_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUStart,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUStart(CMOCK_IMUStart_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU);
void CMockExpectParameters_IMUStart(CMOCK_IMUStart_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUStart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUStart_CALL_INSTANCE));
  CMOCK_IMUStart_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUStart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUStart_CallInstance = CMock_Guts_MemChain(Mock.IMUStart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUStart(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUStop(vIMU_t* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUStop_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUStop);
  cmock_call_instance = (CMOCK_IMUStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUStop_CallInstance);
  Mock.IMUStop_CallInstance = CMock_Guts_MemNext(Mock.IMUStop_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUStop,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUStop(CMOCK_IMUStop_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU);
void CMockExpectParameters_IMUStop(CMOCK_IMUStop_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUStop_CALL_INSTANCE));
  CMOCK_IMUStop_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUStop_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUStop_CallInstance = CMock_Guts_MemChain(Mock.IMUStop_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUStop(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUHandleErr(vIMU_t* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUHandleErr_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUHandleErr);
  cmock_call_instance = (CMOCK_IMUHandleErr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUHandleErr_CallInstance);
  Mock.IMUHandleErr_CallInstance = CMock_Guts_MemNext(Mock.IMUHandleErr_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUHandleErr,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUHandleErr(CMOCK_IMUHandleErr_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU);
void CMockExpectParameters_IMUHandleErr(CMOCK_IMUHandleErr_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMUHandleErr_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUHandleErr_CALL_INSTANCE));
  CMOCK_IMUHandleErr_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUHandleErr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUHandleErr_CallInstance = CMock_Guts_MemChain(Mock.IMUHandleErr_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUHandleErr(cmock_call_instance, pIMU);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMU_Update(vIMU_t* pIMU, bool forcePolling, Vec3f* pOutputAccel, Vec3f* pOutputGyro)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMU_Update_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMU_Update);
  cmock_call_instance = (CMOCK_IMU_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMU_Update_CallInstance);
  Mock.IMU_Update_CallInstance = CMock_Guts_MemNext(Mock.IMU_Update_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMU_Update,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMU_Update,CMockString_forcePolling);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_forcePolling, forcePolling, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMU_Update,CMockString_pOutputAccel);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutputAccel), (void*)(pOutputAccel), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMU_Update,CMockString_pOutputGyro);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pOutputGyro), (void*)(pOutputGyro), sizeof(Vec3f), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMU_Update(CMOCK_IMU_Update_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, bool forcePolling, Vec3f* pOutputAccel, Vec3f* pOutputGyro);
void CMockExpectParameters_IMU_Update(CMOCK_IMU_Update_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, bool forcePolling, Vec3f* pOutputAccel, Vec3f* pOutputGyro)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_forcePolling = forcePolling;
  cmock_call_instance->Expected_pOutputAccel = pOutputAccel;
  cmock_call_instance->Expected_pOutputGyro = pOutputGyro;
}

void IMU_Update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, bool forcePolling, Vec3f* pOutputAccel, Vec3f* pOutputGyro, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMU_Update_CALL_INSTANCE));
  CMOCK_IMU_Update_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMU_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMU_Update_CallInstance = CMock_Guts_MemChain(Mock.IMU_Update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMU_Update(cmock_call_instance, pIMU, forcePolling, pOutputAccel, pOutputGyro);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUGetConf(vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUGetConf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUGetConf);
  cmock_call_instance = (CMOCK_IMUGetConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUGetConf_CallInstance);
  Mock.IMUGetConf_CallInstance = CMock_Guts_MemNext(Mock.IMUGetConf_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUGetConf,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetConf,CMockString_pAConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAConf), (void*)(pAConf), sizeof(IMUAccConf), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetConf,CMockString_pGConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGConf), (void*)(pGConf), sizeof(IMUGyroConf), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUGetConf(CMOCK_IMUGetConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf);
void CMockExpectParameters_IMUGetConf(CMOCK_IMUGetConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_pAConf = pAConf;
  cmock_call_instance->Expected_pGConf = pGConf;
}

void IMUGetConf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUGetConf_CALL_INSTANCE));
  CMOCK_IMUGetConf_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUGetConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUGetConf_CallInstance = CMock_Guts_MemChain(Mock.IMUGetConf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUGetConf(cmock_call_instance, pIMU, pAConf, pGConf);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUGetAltConf(vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUGetAltConf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUGetAltConf);
  cmock_call_instance = (CMOCK_IMUGetAltConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUGetAltConf_CallInstance);
  Mock.IMUGetAltConf_CallInstance = CMock_Guts_MemNext(Mock.IMUGetAltConf_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUGetAltConf,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetAltConf,CMockString_pAConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAConf), (void*)(pAConf), sizeof(IMUAccConf), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUGetAltConf,CMockString_pGConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGConf), (void*)(pGConf), sizeof(IMUGyroConf), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUGetAltConf(CMOCK_IMUGetAltConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf);
void CMockExpectParameters_IMUGetAltConf(CMOCK_IMUGetAltConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_pAConf = pAConf;
  cmock_call_instance->Expected_pGConf = pGConf;
}

void IMUGetAltConf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf* pAConf, IMUGyroConf* pGConf, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUGetAltConf_CALL_INSTANCE));
  CMOCK_IMUGetAltConf_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUGetAltConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUGetAltConf_CallInstance = CMock_Guts_MemChain(Mock.IMUGetAltConf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUGetAltConf(cmock_call_instance, pIMU, pAConf, pGConf);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUSetConf(vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUSetConf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUSetConf);
  cmock_call_instance = (CMOCK_IMUSetConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUSetConf_CallInstance);
  Mock.IMUSetConf_CallInstance = CMock_Guts_MemNext(Mock.IMUSetConf_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUSetConf,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetConf,CMockString_pAConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAConf), (void*)(pAConf), sizeof(IMUAccConf const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetConf,CMockString_pGConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGConf), (void*)(pGConf), sizeof(IMUGyroConf const), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUSetConf(CMOCK_IMUSetConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf);
void CMockExpectParameters_IMUSetConf(CMOCK_IMUSetConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_pAConf = pAConf;
  cmock_call_instance->Expected_pGConf = pGConf;
}

void IMUSetConf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUSetConf_CALL_INSTANCE));
  CMOCK_IMUSetConf_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUSetConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUSetConf_CallInstance = CMock_Guts_MemChain(Mock.IMUSetConf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUSetConf(cmock_call_instance, pIMU, pAConf, pGConf);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUSetAltConf(vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUSetAltConf_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUSetAltConf);
  cmock_call_instance = (CMOCK_IMUSetAltConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUSetAltConf_CallInstance);
  Mock.IMUSetAltConf_CallInstance = CMock_Guts_MemNext(Mock.IMUSetAltConf_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUSetAltConf,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetAltConf,CMockString_pAConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pAConf), (void*)(pAConf), sizeof(IMUAccConf const), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUSetAltConf,CMockString_pGConf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pGConf), (void*)(pGConf), sizeof(IMUGyroConf const), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUSetAltConf(CMOCK_IMUSetAltConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf);
void CMockExpectParameters_IMUSetAltConf(CMOCK_IMUSetAltConf_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf)
{
  cmock_call_instance->Expected_pIMU = pIMU;
  cmock_call_instance->Expected_pAConf = pAConf;
  cmock_call_instance->Expected_pGConf = pGConf;
}

void IMUSetAltConf_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU, IMUAccConf const* pAConf, IMUGyroConf const* pGConf, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUSetAltConf_CALL_INSTANCE));
  CMOCK_IMUSetAltConf_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUSetAltConf_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUSetAltConf_CallInstance = CMock_Guts_MemChain(Mock.IMUSetAltConf_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUSetAltConf(cmock_call_instance, pIMU, pAConf, pGConf);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

eSTATUS_t IMUCompareConfs(IMUAccConf aconf, IMUGyroConf gconf, IMUAccConf aconf2, IMUGyroConf gconf2)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUCompareConfs_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUCompareConfs);
  cmock_call_instance = (CMOCK_IMUCompareConfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUCompareConfs_CallInstance);
  Mock.IMUCompareConfs_CallInstance = CMock_Guts_MemNext(Mock.IMUCompareConfs_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMUCompareConfs,CMockString_aconf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_aconf), (void*)(&aconf), sizeof(IMUAccConf), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUCompareConfs,CMockString_gconf);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gconf), (void*)(&gconf), sizeof(IMUGyroConf), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUCompareConfs,CMockString_aconf2);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_aconf2), (void*)(&aconf2), sizeof(IMUAccConf), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_IMUCompareConfs,CMockString_gconf2);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_gconf2), (void*)(&gconf2), sizeof(IMUGyroConf), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IMUCompareConfs(CMOCK_IMUCompareConfs_CALL_INSTANCE* cmock_call_instance, IMUAccConf aconf, IMUGyroConf gconf, IMUAccConf aconf2, IMUGyroConf gconf2);
void CMockExpectParameters_IMUCompareConfs(CMOCK_IMUCompareConfs_CALL_INSTANCE* cmock_call_instance, IMUAccConf aconf, IMUGyroConf gconf, IMUAccConf aconf2, IMUGyroConf gconf2)
{
  memcpy((void*)(&cmock_call_instance->Expected_aconf), (void*)(&aconf),
         sizeof(IMUAccConf[sizeof(aconf) == sizeof(IMUAccConf) ? 1 : -1])); /* add IMUAccConf to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_gconf), (void*)(&gconf),
         sizeof(IMUGyroConf[sizeof(gconf) == sizeof(IMUGyroConf) ? 1 : -1])); /* add IMUGyroConf to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_aconf2), (void*)(&aconf2),
         sizeof(IMUAccConf[sizeof(aconf2) == sizeof(IMUAccConf) ? 1 : -1])); /* add IMUAccConf to :treat_as_array if this causes an error */
  memcpy((void*)(&cmock_call_instance->Expected_gconf2), (void*)(&gconf2),
         sizeof(IMUGyroConf[sizeof(gconf2) == sizeof(IMUGyroConf) ? 1 : -1])); /* add IMUGyroConf to :treat_as_array if this causes an error */
}

void IMUCompareConfs_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, IMUAccConf aconf, IMUGyroConf gconf, IMUAccConf aconf2, IMUGyroConf gconf2, eSTATUS_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUCompareConfs_CALL_INSTANCE));
  CMOCK_IMUCompareConfs_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUCompareConfs_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUCompareConfs_CallInstance = CMock_Guts_MemChain(Mock.IMUCompareConfs_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMUCompareConfs(cmock_call_instance, aconf, gconf, aconf2, gconf2);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(eSTATUS_t[sizeof(cmock_to_return) == sizeof(eSTATUS_t) ? 1 : -1])); /* add eSTATUS_t to :treat_as_array if this causes an error */
}

vIMU_t const* IMUGetActiveDevice(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMUGetActiveDevice_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMUGetActiveDevice);
  cmock_call_instance = (CMOCK_IMUGetActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMUGetActiveDevice_CallInstance);
  Mock.IMUGetActiveDevice_CallInstance = CMock_Guts_MemNext(Mock.IMUGetActiveDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void IMUGetActiveDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t const* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMUGetActiveDevice_CALL_INSTANCE));
  CMOCK_IMUGetActiveDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMUGetActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMUGetActiveDevice_CallInstance = CMock_Guts_MemChain(Mock.IMUGetActiveDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

vIMU_t* IMU_GetMutableActiveDevice(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMU_GetMutableActiveDevice_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMU_GetMutableActiveDevice);
  cmock_call_instance = (CMOCK_IMU_GetMutableActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMU_GetMutableActiveDevice_CallInstance);
  Mock.IMU_GetMutableActiveDevice_CallInstance = CMock_Guts_MemNext(Mock.IMU_GetMutableActiveDevice_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void IMU_GetMutableActiveDevice_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, vIMU_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMU_GetMutableActiveDevice_CALL_INSTANCE));
  CMOCK_IMU_GetMutableActiveDevice_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMU_GetMutableActiveDevice_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMU_GetMutableActiveDevice_CallInstance = CMock_Guts_MemChain(Mock.IMU_GetMutableActiveDevice_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void IMU2CPUInterruptHandler(vIMU_t* pIMU)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IMU2CPUInterruptHandler);
  cmock_call_instance = (CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IMU2CPUInterruptHandler_CallInstance);
  Mock.IMU2CPUInterruptHandler_CallInstance = CMock_Guts_MemNext(Mock.IMU2CPUInterruptHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_IMU2CPUInterruptHandler,CMockString_pIMU);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_pIMU), (void*)(pIMU), sizeof(vIMU_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_IMU2CPUInterruptHandler(CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU);
void CMockExpectParameters_IMU2CPUInterruptHandler(CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE* cmock_call_instance, vIMU_t* pIMU)
{
  cmock_call_instance->Expected_pIMU = pIMU;
}

void IMU2CPUInterruptHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, vIMU_t* pIMU)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE));
  CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_IMU2CPUInterruptHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IMU2CPUInterruptHandler_CallInstance = CMock_Guts_MemChain(Mock.IMU2CPUInterruptHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_IMU2CPUInterruptHandler(cmock_call_instance, pIMU);
}

