/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_stm32h7xx_hal_hsem.h"

static const char* CMockString_CoreID = "CoreID";
static const char* CMockString_HAL_HSEM_ActivateNotification = "HAL_HSEM_ActivateNotification";
static const char* CMockString_HAL_HSEM_DeactivateNotification = "HAL_HSEM_DeactivateNotification";
static const char* CMockString_HAL_HSEM_FastTake = "HAL_HSEM_FastTake";
static const char* CMockString_HAL_HSEM_FreeCallback = "HAL_HSEM_FreeCallback";
static const char* CMockString_HAL_HSEM_GetClearKey = "HAL_HSEM_GetClearKey";
static const char* CMockString_HAL_HSEM_IRQHandler = "HAL_HSEM_IRQHandler";
static const char* CMockString_HAL_HSEM_IsSemTaken = "HAL_HSEM_IsSemTaken";
static const char* CMockString_HAL_HSEM_Release = "HAL_HSEM_Release";
static const char* CMockString_HAL_HSEM_ReleaseAll = "HAL_HSEM_ReleaseAll";
static const char* CMockString_HAL_HSEM_SetClearKey = "HAL_HSEM_SetClearKey";
static const char* CMockString_HAL_HSEM_Take = "HAL_HSEM_Take";
static const char* CMockString_Key = "Key";
static const char* CMockString_ProcessID = "ProcessID";
static const char* CMockString_SemID = "SemID";
static const char* CMockString_SemMask = "SemMask";

typedef struct _CMOCK_HAL_HSEM_Take_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  uint32_t Expected_SemID;
  uint32_t Expected_ProcessID;

} CMOCK_HAL_HSEM_Take_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  HAL_StatusTypeDef ReturnVal;
  uint32_t Expected_SemID;

} CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_Release_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_SemID;
  uint32_t Expected_ProcessID;

} CMOCK_HAL_HSEM_Release_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_Key;
  uint32_t Expected_CoreID;

} CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  uint32_t Expected_SemID;

} CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_Key;

} CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_GetClearKey_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;

} CMOCK_HAL_HSEM_GetClearKey_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_SemMask;

} CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_SemMask;

} CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t Expected_SemMask;

} CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE;

typedef struct _CMOCK_HAL_HSEM_IRQHandler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_HAL_HSEM_IRQHandler_CALL_INSTANCE;

static struct mock_stm32h7xx_hal_hsemInstance
{
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_Take_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_FastTake_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_Release_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_ReleaseAll_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_IsSemTaken_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_SetClearKey_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_GetClearKey_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_ActivateNotification_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_DeactivateNotification_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_FreeCallback_CallInstance;
  CMOCK_MEM_INDEX_TYPE HAL_HSEM_IRQHandler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void mock_stm32h7xx_hal_hsem_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.HAL_HSEM_Take_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_Take);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_FastTake_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_FastTake);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_Release_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_Release);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_ReleaseAll_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_ReleaseAll);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_IsSemTaken_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_IsSemTaken);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_SetClearKey_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_SetClearKey);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_GetClearKey_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_GetClearKey);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_ActivateNotification_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_ActivateNotification);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_DeactivateNotification_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_DeactivateNotification);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_FreeCallback_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_FreeCallback);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  call_instance = Mock.HAL_HSEM_IRQHandler_CallInstance;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_HAL_HSEM_IRQHandler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
}

void mock_stm32h7xx_hal_hsem_Init(void)
{
  mock_stm32h7xx_hal_hsem_Destroy();
}

void mock_stm32h7xx_hal_hsem_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

HAL_StatusTypeDef HAL_HSEM_Take(uint32_t SemID, uint32_t ProcessID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_Take_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_Take);
  cmock_call_instance = (CMOCK_HAL_HSEM_Take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_Take_CallInstance);
  Mock.HAL_HSEM_Take_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_Take_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_Take,CMockString_SemID);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SemID, SemID, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_Take,CMockString_ProcessID);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ProcessID, ProcessID, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_HSEM_Take(CMOCK_HAL_HSEM_Take_CALL_INSTANCE* cmock_call_instance, uint32_t SemID, uint32_t ProcessID);
void CMockExpectParameters_HAL_HSEM_Take(CMOCK_HAL_HSEM_Take_CALL_INSTANCE* cmock_call_instance, uint32_t SemID, uint32_t ProcessID)
{
  cmock_call_instance->Expected_SemID = SemID;
  cmock_call_instance->Expected_ProcessID = ProcessID;
}

void HAL_HSEM_Take_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t SemID, uint32_t ProcessID, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_Take_CALL_INSTANCE));
  CMOCK_HAL_HSEM_Take_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_Take_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_Take_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_Take_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_Take(cmock_call_instance, SemID, ProcessID);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

HAL_StatusTypeDef HAL_HSEM_FastTake(uint32_t SemID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_FastTake);
  cmock_call_instance = (CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_FastTake_CallInstance);
  Mock.HAL_HSEM_FastTake_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_FastTake_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_FastTake,CMockString_SemID);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SemID, SemID, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_HSEM_FastTake(CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE* cmock_call_instance, uint32_t SemID);
void CMockExpectParameters_HAL_HSEM_FastTake(CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE* cmock_call_instance, uint32_t SemID)
{
  cmock_call_instance->Expected_SemID = SemID;
}

void HAL_HSEM_FastTake_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t SemID, HAL_StatusTypeDef cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE));
  CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_FastTake_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_FastTake_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_FastTake_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_FastTake(cmock_call_instance, SemID);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(HAL_StatusTypeDef[sizeof(cmock_to_return) == sizeof(HAL_StatusTypeDef) ? 1 : -1])); /* add HAL_StatusTypeDef to :treat_as_array if this causes an error */
}

void HAL_HSEM_Release(uint32_t SemID, uint32_t ProcessID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_Release_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_Release);
  cmock_call_instance = (CMOCK_HAL_HSEM_Release_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_Release_CallInstance);
  Mock.HAL_HSEM_Release_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_Release_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_Release,CMockString_SemID);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SemID, SemID, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_Release,CMockString_ProcessID);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ProcessID, ProcessID, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_HSEM_Release(CMOCK_HAL_HSEM_Release_CALL_INSTANCE* cmock_call_instance, uint32_t SemID, uint32_t ProcessID);
void CMockExpectParameters_HAL_HSEM_Release(CMOCK_HAL_HSEM_Release_CALL_INSTANCE* cmock_call_instance, uint32_t SemID, uint32_t ProcessID)
{
  cmock_call_instance->Expected_SemID = SemID;
  cmock_call_instance->Expected_ProcessID = ProcessID;
}

void HAL_HSEM_Release_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemID, uint32_t ProcessID)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_Release_CALL_INSTANCE));
  CMOCK_HAL_HSEM_Release_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_Release_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_Release_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_Release_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_Release(cmock_call_instance, SemID, ProcessID);
}

void HAL_HSEM_ReleaseAll(uint32_t Key, uint32_t CoreID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_ReleaseAll);
  cmock_call_instance = (CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_ReleaseAll_CallInstance);
  Mock.HAL_HSEM_ReleaseAll_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_ReleaseAll_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_ReleaseAll,CMockString_Key);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Key, Key, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_ReleaseAll,CMockString_CoreID);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_CoreID, CoreID, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_HSEM_ReleaseAll(CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE* cmock_call_instance, uint32_t Key, uint32_t CoreID);
void CMockExpectParameters_HAL_HSEM_ReleaseAll(CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE* cmock_call_instance, uint32_t Key, uint32_t CoreID)
{
  cmock_call_instance->Expected_Key = Key;
  cmock_call_instance->Expected_CoreID = CoreID;
}

void HAL_HSEM_ReleaseAll_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t Key, uint32_t CoreID)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE));
  CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_ReleaseAll_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_ReleaseAll_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_ReleaseAll_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_ReleaseAll(cmock_call_instance, Key, CoreID);
}

uint32_t HAL_HSEM_IsSemTaken(uint32_t SemID)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_IsSemTaken);
  cmock_call_instance = (CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_IsSemTaken_CallInstance);
  Mock.HAL_HSEM_IsSemTaken_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_IsSemTaken_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_IsSemTaken,CMockString_SemID);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SemID, SemID, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_HAL_HSEM_IsSemTaken(CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE* cmock_call_instance, uint32_t SemID);
void CMockExpectParameters_HAL_HSEM_IsSemTaken(CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE* cmock_call_instance, uint32_t SemID)
{
  cmock_call_instance->Expected_SemID = SemID;
}

void HAL_HSEM_IsSemTaken_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t SemID, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE));
  CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_IsSemTaken_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_IsSemTaken_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_IsSemTaken_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_IsSemTaken(cmock_call_instance, SemID);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HAL_HSEM_SetClearKey(uint32_t Key)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_SetClearKey);
  cmock_call_instance = (CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_SetClearKey_CallInstance);
  Mock.HAL_HSEM_SetClearKey_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_SetClearKey_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_SetClearKey,CMockString_Key);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_Key, Key, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_HSEM_SetClearKey(CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE* cmock_call_instance, uint32_t Key);
void CMockExpectParameters_HAL_HSEM_SetClearKey(CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE* cmock_call_instance, uint32_t Key)
{
  cmock_call_instance->Expected_Key = Key;
}

void HAL_HSEM_SetClearKey_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t Key)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE));
  CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_SetClearKey_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_SetClearKey_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_SetClearKey_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_SetClearKey(cmock_call_instance, Key);
}

uint32_t HAL_HSEM_GetClearKey(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_GetClearKey_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_GetClearKey);
  cmock_call_instance = (CMOCK_HAL_HSEM_GetClearKey_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_GetClearKey_CallInstance);
  Mock.HAL_HSEM_GetClearKey_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_GetClearKey_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void HAL_HSEM_GetClearKey_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_GetClearKey_CALL_INSTANCE));
  CMOCK_HAL_HSEM_GetClearKey_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_GetClearKey_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_GetClearKey_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_GetClearKey_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void HAL_HSEM_ActivateNotification(uint32_t SemMask)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_ActivateNotification);
  cmock_call_instance = (CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_ActivateNotification_CallInstance);
  Mock.HAL_HSEM_ActivateNotification_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_ActivateNotification_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_ActivateNotification,CMockString_SemMask);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SemMask, SemMask, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_HSEM_ActivateNotification(CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE* cmock_call_instance, uint32_t SemMask);
void CMockExpectParameters_HAL_HSEM_ActivateNotification(CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE* cmock_call_instance, uint32_t SemMask)
{
  cmock_call_instance->Expected_SemMask = SemMask;
}

void HAL_HSEM_ActivateNotification_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemMask)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE));
  CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_ActivateNotification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_ActivateNotification_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_ActivateNotification_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_ActivateNotification(cmock_call_instance, SemMask);
}

void HAL_HSEM_DeactivateNotification(uint32_t SemMask)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_DeactivateNotification);
  cmock_call_instance = (CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_DeactivateNotification_CallInstance);
  Mock.HAL_HSEM_DeactivateNotification_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_DeactivateNotification_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_DeactivateNotification,CMockString_SemMask);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SemMask, SemMask, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_HSEM_DeactivateNotification(CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE* cmock_call_instance, uint32_t SemMask);
void CMockExpectParameters_HAL_HSEM_DeactivateNotification(CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE* cmock_call_instance, uint32_t SemMask)
{
  cmock_call_instance->Expected_SemMask = SemMask;
}

void HAL_HSEM_DeactivateNotification_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemMask)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE));
  CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_DeactivateNotification_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_DeactivateNotification_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_DeactivateNotification_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_DeactivateNotification(cmock_call_instance, SemMask);
}

void HAL_HSEM_FreeCallback(uint32_t SemMask)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_FreeCallback);
  cmock_call_instance = (CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_FreeCallback_CallInstance);
  Mock.HAL_HSEM_FreeCallback_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_FreeCallback_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_HAL_HSEM_FreeCallback,CMockString_SemMask);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_SemMask, SemMask, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_HAL_HSEM_FreeCallback(CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE* cmock_call_instance, uint32_t SemMask);
void CMockExpectParameters_HAL_HSEM_FreeCallback(CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE* cmock_call_instance, uint32_t SemMask)
{
  cmock_call_instance->Expected_SemMask = SemMask;
}

void HAL_HSEM_FreeCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t SemMask)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE));
  CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_FreeCallback_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_FreeCallback_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_FreeCallback_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_HAL_HSEM_FreeCallback(cmock_call_instance, SemMask);
}

void HAL_HSEM_IRQHandler(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_HAL_HSEM_IRQHandler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_HAL_HSEM_IRQHandler);
  cmock_call_instance = (CMOCK_HAL_HSEM_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.HAL_HSEM_IRQHandler_CallInstance);
  Mock.HAL_HSEM_IRQHandler_CallInstance = CMock_Guts_MemNext(Mock.HAL_HSEM_IRQHandler_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void HAL_HSEM_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_HAL_HSEM_IRQHandler_CALL_INSTANCE));
  CMOCK_HAL_HSEM_IRQHandler_CALL_INSTANCE* cmock_call_instance = (CMOCK_HAL_HSEM_IRQHandler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.HAL_HSEM_IRQHandler_CallInstance = CMock_Guts_MemChain(Mock.HAL_HSEM_IRQHandler_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

