/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_STM32H7XX_HAL_UART_H
#define _MOCK_STM32H7XX_HAL_UART_H

#include "unity.h"
#include "hal_stub.h"
#include "stm32h7xx_hal_uart.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void mock_stm32h7xx_hal_uart_Init(void);
void mock_stm32h7xx_hal_uart_Destroy(void);
void mock_stm32h7xx_hal_uart_Verify(void);




#define HAL_UART_Init_ExpectAndReturn(huart, cmock_retval) HAL_UART_Init_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_Init_ExpectAndReturn(huart, cmock_retval) HAL_HalfDuplex_Init_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_HalfDuplex_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_LIN_Init_ExpectAndReturn(huart, BreakDetectLength, cmock_retval) HAL_LIN_Init_CMockExpectAndReturn(__LINE__, huart, BreakDetectLength, cmock_retval)
void HAL_LIN_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint32_t BreakDetectLength, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_Init_ExpectAndReturn(huart, Address, WakeUpMethod, cmock_retval) HAL_MultiProcessor_Init_CMockExpectAndReturn(__LINE__, huart, Address, WakeUpMethod, cmock_retval)
void HAL_MultiProcessor_Init_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t Address, uint32_t WakeUpMethod, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DeInit_ExpectAndReturn(huart, cmock_retval) HAL_UART_DeInit_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DeInit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_MspInit_Expect(huart) HAL_UART_MspInit_CMockExpect(__LINE__, huart)
void HAL_UART_MspInit_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_MspDeInit_Expect(huart) HAL_UART_MspDeInit_CMockExpect(__LINE__, huart)
void HAL_UART_MspDeInit_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_RegisterCallback_ExpectAndReturn(huart, CallbackID, pCallback, cmock_retval) HAL_UART_RegisterCallback_CMockExpectAndReturn(__LINE__, huart, CallbackID, pCallback, cmock_retval)
void HAL_UART_RegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_UART_CallbackIDTypeDef CallbackID, pUART_CallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_UnRegisterCallback_ExpectAndReturn(huart, CallbackID, cmock_retval) HAL_UART_UnRegisterCallback_CMockExpectAndReturn(__LINE__, huart, CallbackID, cmock_retval)
void HAL_UART_UnRegisterCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_UART_CallbackIDTypeDef CallbackID, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_RegisterRxEventCallback_ExpectAndReturn(huart, pCallback, cmock_retval) HAL_UART_RegisterRxEventCallback_CMockExpectAndReturn(__LINE__, huart, pCallback, cmock_retval)
void HAL_UART_RegisterRxEventCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, pUART_RxEventCallbackTypeDef pCallback, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_UnRegisterRxEventCallback_ExpectAndReturn(huart, cmock_retval) HAL_UART_UnRegisterRxEventCallback_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_UnRegisterRxEventCallback_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_ExpectAndReturn(huart, pData, Size, Timeout, cmock_retval) HAL_UART_Transmit_CMockExpectAndReturn(__LINE__, huart, pData, Size, Timeout, cmock_retval)
void HAL_UART_Transmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, const uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_ExpectAndReturn(huart, pData, Size, Timeout, cmock_retval) HAL_UART_Receive_CMockExpectAndReturn(__LINE__, huart, pData, Size, Timeout, cmock_retval)
void HAL_UART_Receive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_IT_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Transmit_IT_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Transmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, const uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_IT_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Receive_IT_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Transmit_DMA_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Transmit_DMA_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Transmit_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, const uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Receive_DMA_ExpectAndReturn(huart, pData, Size, cmock_retval) HAL_UART_Receive_DMA_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void HAL_UART_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAPause_ExpectAndReturn(huart, cmock_retval) HAL_UART_DMAPause_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DMAPause_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAResume_ExpectAndReturn(huart, cmock_retval) HAL_UART_DMAResume_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DMAResume_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DMAStop_ExpectAndReturn(huart, cmock_retval) HAL_UART_DMAStop_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DMAStop_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Abort_ExpectAndReturn(huart, cmock_retval) HAL_UART_Abort_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_Abort_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortTransmit_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortTransmit_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortTransmit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortReceive_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortReceive_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortReceive_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_Abort_IT_ExpectAndReturn(huart, cmock_retval) HAL_UART_Abort_IT_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_Abort_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortTransmit_IT_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortTransmit_IT_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortTransmit_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_AbortReceive_IT_ExpectAndReturn(huart, cmock_retval) HAL_UART_AbortReceive_IT_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_AbortReceive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_IRQHandler_Expect(huart) HAL_UART_IRQHandler_CMockExpect(__LINE__, huart)
void HAL_UART_IRQHandler_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_TxHalfCpltCallback_Expect(huart) HAL_UART_TxHalfCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_TxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_TxCpltCallback_Expect(huart) HAL_UART_TxCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_TxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_RxHalfCpltCallback_Expect(huart) HAL_UART_RxHalfCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_RxHalfCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_RxCpltCallback_Expect(huart) HAL_UART_RxCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_RxCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_ErrorCallback_Expect(huart) HAL_UART_ErrorCallback_CMockExpect(__LINE__, huart)
void HAL_UART_ErrorCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_AbortCpltCallback_Expect(huart) HAL_UART_AbortCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_AbortCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_AbortTransmitCpltCallback_Expect(huart) HAL_UART_AbortTransmitCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_AbortTransmitCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UART_AbortReceiveCpltCallback_Expect(huart) HAL_UART_AbortReceiveCpltCallback_CMockExpect(__LINE__, huart)
void HAL_UART_AbortReceiveCpltCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_UARTEx_RxEventCallback_Expect(huart, Size) HAL_UARTEx_RxEventCallback_CMockExpect(__LINE__, huart, Size)
void HAL_UARTEx_RxEventCallback_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint16_t Size);
#define HAL_UART_ReceiverTimeout_Config_Expect(huart, TimeoutValue) HAL_UART_ReceiverTimeout_Config_CMockExpect(__LINE__, huart, TimeoutValue)
void HAL_UART_ReceiverTimeout_Config_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint32_t TimeoutValue);
#define HAL_UART_EnableReceiverTimeout_ExpectAndReturn(huart, cmock_retval) HAL_UART_EnableReceiverTimeout_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_EnableReceiverTimeout_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_DisableReceiverTimeout_ExpectAndReturn(huart, cmock_retval) HAL_UART_DisableReceiverTimeout_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_DisableReceiverTimeout_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_LIN_SendBreak_ExpectAndReturn(huart, cmock_retval) HAL_LIN_SendBreak_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_LIN_SendBreak_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_EnableMuteMode_ExpectAndReturn(huart, cmock_retval) HAL_MultiProcessor_EnableMuteMode_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_MultiProcessor_EnableMuteMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_DisableMuteMode_ExpectAndReturn(huart, cmock_retval) HAL_MultiProcessor_DisableMuteMode_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_MultiProcessor_DisableMuteMode_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_MultiProcessor_EnterMuteMode_Expect(huart) HAL_MultiProcessor_EnterMuteMode_CMockExpect(__LINE__, huart)
void HAL_MultiProcessor_EnterMuteMode_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define HAL_HalfDuplex_EnableTransmitter_ExpectAndReturn(huart, cmock_retval) HAL_HalfDuplex_EnableTransmitter_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_HalfDuplex_EnableTransmitter_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_HalfDuplex_EnableReceiver_ExpectAndReturn(huart, cmock_retval) HAL_HalfDuplex_EnableReceiver_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_HalfDuplex_EnableReceiver_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define HAL_UART_GetState_ExpectAndReturn(huart, cmock_retval) HAL_UART_GetState_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_GetState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const UART_HandleTypeDef* huart, HAL_UART_StateTypeDef cmock_to_return);
#define HAL_UART_GetError_ExpectAndReturn(huart, cmock_retval) HAL_UART_GetError_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void HAL_UART_GetError_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const UART_HandleTypeDef* huart, uint32_t cmock_to_return);
#define UART_InitCallbacksToDefault_Expect(huart) UART_InitCallbacksToDefault_CMockExpect(__LINE__, huart)
void UART_InitCallbacksToDefault_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define UART_SetConfig_ExpectAndReturn(huart, cmock_retval) UART_SetConfig_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void UART_SetConfig_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define UART_CheckIdleState_ExpectAndReturn(huart, cmock_retval) UART_CheckIdleState_CMockExpectAndReturn(__LINE__, huart, cmock_retval)
void UART_CheckIdleState_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, HAL_StatusTypeDef cmock_to_return);
#define UART_WaitOnFlagUntilTimeout_ExpectAndReturn(huart, Flag, Status, Tickstart, Timeout, cmock_retval) UART_WaitOnFlagUntilTimeout_CMockExpectAndReturn(__LINE__, huart, Flag, Status, Tickstart, Timeout, cmock_retval)
void UART_WaitOnFlagUntilTimeout_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint32_t Flag, FlagStatus Status, uint32_t Tickstart, uint32_t Timeout, HAL_StatusTypeDef cmock_to_return);
#define UART_AdvFeatureConfig_Expect(huart) UART_AdvFeatureConfig_CMockExpect(__LINE__, huart)
void UART_AdvFeatureConfig_CMockExpect(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart);
#define UART_Start_Receive_IT_ExpectAndReturn(huart, pData, Size, cmock_retval) UART_Start_Receive_IT_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void UART_Start_Receive_IT_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);
#define UART_Start_Receive_DMA_ExpectAndReturn(huart, pData, Size, cmock_retval) UART_Start_Receive_DMA_CMockExpectAndReturn(__LINE__, huart, pData, Size, cmock_retval)
void UART_Start_Receive_DMA_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, UART_HandleTypeDef* huart, uint8_t* pData, uint16_t Size, HAL_StatusTypeDef cmock_to_return);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
