#ifndef CONF_DEV_BOARD_H
#define CONF_DEV_BOARD_H

#include "conf/ids.h"

#define TIM8_CH1_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_6)

#define TIM13_CH1_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_8)

// SPI_2: SCK, MISO, MOSI
#define SPI2_ENABLED
#define SPI2_SCK_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_12)
#define SPI2_MISO_GPIO GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_2)
#define SPI2_MOSI_GPIO GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_3)

// UART1: RX, TX
#define UART_1_ENABLED
#define UART_1_RX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_9)
#define UART_1_TX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_10)

#define IMU_ENABLED
#define IMU_INT_EXTI eEXTI_7_ID
#define IMU_INT_GPIO GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_7)
#define IMU_BUS_ID   eSPI_2_BUS_ID
#define IMU_NSS_GPIO GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_11)

#define SERIAL_DEBUG_ENABLED
#define SERIAL_DEBUG_BUS_ID eUART_1_BUS_ID

#endif // CONF_DEV_BOARD_H