#ifndef CONF_MY_BOARD_H
#define CONF_MY_BOARD_H

#include "conf/board.h"
#include "conf/ids.h"

// #define TIM5_CH1_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_0)
// #define TIM5_CH2_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_1)
// #define TIM5_CH3_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_2)
// #define TIM5_CH4_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_3)

// #define TIM8_CH1_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_6)
// #define TIM8_CH2_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_7)
// #define TIM8_CH3_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_8)
// #define TIM8_CH4_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_9)

// #define TIM12_CH1_GPIO GPIO_ID_MAKE (eGPIO_PORTID_H, eGPIO_PINID_6)
// #define TIM12_CH2_GPIO GPIO_ID_MAKE (eGPIO_PORTID_H, eGPIO_PINID_9)

// // SPI_1: SCK, MISO, MOSI
// #define SPI1_ENABLED
// #define SPI1_SCK_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_5)
// #define SPI1_MISO_GPIO GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_6)
// #define SPI1_MOSI_GPIO GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_7)
// // #define SPI1_NSS_GPIO      GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_4)

// // SPI_3: SCK, MISO, MOSI
// #define SPI3_ENABLED
// #define SPI3_SCK_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_10)
// #define SPI3_MISO_GPIO GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_11)
// #define SPI3_MOSI_GPIO GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_12)
// // #define SPI3_NSS_1_GPIO      GPIO_ID_MAKE (eGPIO_PORTID_A, eGPIO_PINID_15)

// // SPI_5: SCK, MISO, MOSI
// #define SPI5_ENABLED
// #define SPI5_SCK_GPIO  GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_7)
// #define SPI5_MISO_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_8)
// #define SPI5_MOSI_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_9)
// // #define SPI5_NSS_GPIO      GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_10)

// // UART1: RX, TX
// #define UART1_ENABLED
// #define UART1_RX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_B, eGPIO_PINID_15)
// #define UART1_TX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_B, eGPIO_PINID_14)
// // #define UART1_GPIO_AF          GPIO_AF7_USART1

// // UART2: RX, TX
// #define UART2_ENABLED
// #define UART2_RX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_D, eGPIO_PINID_6)
// #define UART2_TX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_D, eGPIO_PINID_5)
// // #define UART2_GPIO_AF             GPIO_AF7_USART2

// // UART3: RX, TX
// #define UART3_ENABLED
// #define UART3_RX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_B, eGPIO_PINID_11)
// #define UART3_TX_GPIO GPIO_ID_MAKE (eGPIO_PORTID_B, eGPIO_PINID_10)
// // #define UART3_GPIO_AF            GPIO_AF7_USART3

// // I2C: SCL, SDA
// #define I2C1_ENABLED
// #define I2C1_SCL_GPIO GPIO_ID_MAKE (eGPIO_PORTID_B, eGPIO_PINID_6)
// #define I2C1_SDA_GPIO GPIO_ID_MAKE (eGPIO_PORTID_B, eGPIO_PINID_7)

// #define IMU_ENABLED
// #define IMU_INT_EXTI eEXTI_5_ID
// #define IMU_INT_GPIO GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_5)
// #define IMU_BUS_ID   eSPI_1_BUS_ID
// #define IMU_NSS_GPIO GPIO_ID_MAKE (eGPIO_PORTID_C, eGPIO_PINID_4)

// #define MAG_ENABLED
// #define MAG_INT_EXTI eEXTI_3_ID
// #define MAG_INT_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_3)
// #define MAG_BUS_ID   eSPI_5_BUS_ID
// #define MAG_NSS_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_4)

// #define BARO_ENABLED
// #define BARO_INT_EXTI eEXTI_10_ID
// #define BARO_INT_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_10)
// #define BARO_BUS_ID   eSPI_5_BUS_ID
// #define BARO_NSS_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_6)

// #define FLASH_ENABLED
// #define FLASH_BUS_ID   eSPI_3_BUS_ID
// #define FLASH_NSS_GPIO GPIO_ID_MAKE (eGPIO_PORTID_F, eGPIO_PINID_10)

// #define SERIAL_DEBUG_ENABLED
// #define SERIAL_DEBUG_BUS_ID eUART_1_BUS_ID

// #define GPS_ENABLED
// #define GPS_BUS_ID eUART_2_BUS_ID

// #define RF_RECEIVER_ENABLED
// #define RF_RECEIVER_BUS_ID eUART_3_BUS_ID

// #define CURRENT_SENSOR_ENABLED
// #define CURRENT_SENSOR_BUS_ID eI2C_1_BUS_ID

// // clang-format off

// #define LEFT_SERVO_MOTOR_TIMER                  TIMER_ID_MAKE (eTIMER_5_DEV_ID, eTIMER_CHANNEL_1_ID)
// #define LEFT_SERVO_MOTOR_PWM_FREQUENCY          50U // 50 Hz

// #define LEFT_SERVO_AILERON_TIMER                  TIMER_ID_MAKE (eTIMER_5_DEV_ID, eTIMER_CHANNEL_2_ID)
// #define LEFT_SERVO_AILERON_PWM_FREQUENCY          50U // 50 Hz

// #define SERVO_ELEVATOR_TIMER                  TIMER_ID_MAKE (eTIMER_5_DEV_ID, eTIMER_CHANNEL_3_ID)
// #define SERVO_ELEVATOR_PWM_FREQUENCY          50U // 50 Hz

// #define SERVO_RUDDER_TIMER                  TIMER_ID_MAKE (eTIMER_5_DEV_ID, eTIMER_CHANNEL_4_ID)
// #define SERVO_RUDDER_PWM_FREQUENCY          50U // 50 Hz

// #define RIGHT_SERVO_MOTOR_TIMER                 TIMER_ID_MAKE (eTIMER_8_DEV_ID, eTIMER_CHANNEL_1_ID)
// #define RIGHT_SERVO_MOTOR_PWM_FREQUENCY         50U // 50 Hz

// #define RIGHT_SERVO_AILERON_TIMER                 TIMER_ID_MAKE (eTIMER_8_DEV_ID, eTIMER_CHANNEL_2_ID)
// #define RIGHT_SERVO_AILERON_PWM_FREQUENCY         50U // 50 Hz

// #define SERVO_FLIGHT_MODE_TIMER                 TIMER_ID_MAKE (eTIMER_8_DEV_ID, eTIMER_CHANNEL_3_ID)
// #define SERVO_FLIGHT_MODE_PWM_FREQUENCY         50U // 50 Hz

// #define SERVO_SPARE_1_TIMER                 TIMER_ID_MAKE (eTIMER_8_DEV_ID, eTIMER_CHANNEL_4_ID)
// #define SERVO_SPARE_1_PWM_FREQUENCY         50U // 50 Hz

// #define LEFT_MOTOR_TIMER                    TIMER_ID_MAKE (eTIMER_12_DEV_ID, eTIMER_CHANNEL_1_ID)
// #define LEFT_MOTOR_GPIO                     TIM12_CH1_GPIO

// #define RIGHT_MOTOR_TIMER                   TIMER_ID_MAKE (eTIMER_12_DEV_ID, eTIMER_CHANNEL_2_ID)
// #define RIGHT_MOTOR_GPIO                    TIM12_CH2_GPIO

// clang-format on

uint8_t BoardConfInit (void);
BoardConf_t* BoardConfGet (void);
DeviceBoardConf_t* BoardConfGetDeviceById (eDEVICE_ID_t deviceId);
ServoBoardConf_t* BoardConfGetServoById (eDEVICE_ID_t servoId);
MotorBoardConf_t* BoardConfGetMotorById (eDEVICE_ID_t motorId);

#endif // CONF_MY_BOARD_H