/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_FLAPJACK_PB_H_INCLUDED
#define PB_FLAPJACK_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Axis {
    Axis_ROLL = 0,
    Axis_PITCH = 1,
    Axis_YAW = 2,
    Axis_THROTTLE = 3
} Axis;

typedef enum _PidGainType {
    PidGainType_KP = 0,
    PidGainType_KI = 1,
    PidGainType_KD = 2,
    PidGainType_INTEGRAL_LIMIT = 3
} PidGainType;

/* Struct definitions */
typedef struct _SetPidCmd {
    Axis axis;
    PidGainType gain;
    float value;
} SetPidCmd;

typedef struct _ArmCmd {
    bool arm;
} ArmCmd;

typedef struct _Command {
    pb_size_t which_cmd;
    union _Command_cmd {
        SetPidCmd set_pid;
        ArmCmd arm_disarm;
    } cmd;
} Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Axis_MIN Axis_ROLL
#define _Axis_MAX Axis_THROTTLE
#define _Axis_ARRAYSIZE ((Axis)(Axis_THROTTLE+1))

#define _PidGainType_MIN PidGainType_KP
#define _PidGainType_MAX PidGainType_INTEGRAL_LIMIT
#define _PidGainType_ARRAYSIZE ((PidGainType)(PidGainType_INTEGRAL_LIMIT+1))

#define SetPidCmd_axis_ENUMTYPE Axis
#define SetPidCmd_gain_ENUMTYPE PidGainType




/* Initializer values for message structs */
#define SetPidCmd_init_default                   {_Axis_MIN, _PidGainType_MIN, 0}
#define ArmCmd_init_default                      {0}
#define Command_init_default                     {0, {SetPidCmd_init_default}}
#define SetPidCmd_init_zero                      {_Axis_MIN, _PidGainType_MIN, 0}
#define ArmCmd_init_zero                         {0}
#define Command_init_zero                        {0, {SetPidCmd_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SetPidCmd_axis_tag                       1
#define SetPidCmd_gain_tag                       2
#define SetPidCmd_value_tag                      3
#define ArmCmd_arm_tag                           1
#define Command_set_pid_tag                      1
#define Command_arm_disarm_tag                   2

/* Struct field encoding specification for nanopb */
#define SetPidCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    axis,              1) \
X(a, STATIC,   SINGULAR, UENUM,    gain,              2) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             3)
#define SetPidCmd_CALLBACK NULL
#define SetPidCmd_DEFAULT NULL

#define ArmCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     arm,               1)
#define ArmCmd_CALLBACK NULL
#define ArmCmd_DEFAULT NULL

#define Command_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,set_pid,cmd.set_pid),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (cmd,arm_disarm,cmd.arm_disarm),   2)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL
#define Command_cmd_set_pid_MSGTYPE SetPidCmd
#define Command_cmd_arm_disarm_MSGTYPE ArmCmd

extern const pb_msgdesc_t SetPidCmd_msg;
extern const pb_msgdesc_t ArmCmd_msg;
extern const pb_msgdesc_t Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SetPidCmd_fields &SetPidCmd_msg
#define ArmCmd_fields &ArmCmd_msg
#define Command_fields &Command_msg

/* Maximum encoded size of messages (where known) */
#define ArmCmd_size                              2
#define Command_size                             11
#define FLAPJACK_PB_H_MAX_SIZE                   Command_size
#define SetPidCmd_size                           9

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
