/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_SIM_PB_H_INCLUDED
#define PB_SIM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* FC -> PC: servo (tilt) command, one angle per servo. */
typedef struct _ServoCmd {
    pb_size_t angle_count;
    float angle[8]; /* radians, per servo */
} ServoCmd;

/* FC -> PC: motor command, one throttle per motor. */
typedef struct _MotorCmd {
    pb_size_t throttle_count;
    float throttle[8]; /* 0.0 - 1.0, per motor */
} MotorCmd;

/* FC -> PC: telemetry for open-loop validation.

 The baro_* and gps_* fields are a deliberate LOOPBACK, not an estimate: the
 FC echoes back the sensor value it recovered, so the bridge can assert that
 what it sent is what the firmware understood. That round trip is the whole
 acceptance test for the sensor path - it covers the wire, the driver, the
 device and the umsg publish in one comparison, and it is exactly the check
 that catches a parser which succeeds while discarding its result.

 baro_pa is no longer bit-exact against what was sent, and must not be
 compared as though it were. It is a physical value that went into an emulated
 BMP390 as a 24-bit ADC count and came back through the driver's float32
 compensation polynomial, so the bridge compares it within a tolerance.
 Measured round-trip error over -20..60 C and 50..115 kPa is 0.016 Pa, which
 is float32 rounding rather than quantisation - so the tolerance stays far
 tighter than any real decode error would be.

 The *_count fields are the pacing metric, same role as imu_count: they should
 track what the bridge pushed 1:1, and a shortfall means samples are being
 dropped rather than mis-decoded. */
typedef struct _Telemetry {
    float euler[3]; /* deg [roll, pitch, yaw] from nav */
    bool armed;
    uint32_t imu_count; /* IMU samples read off the part and published (pacing check) */
    bool rc_link_up; /* CRSF frames still arriving (Rx_IsLinkUp) */
    float baro_pa; /* last pressure the baro driver compensated, Pa */
    uint32_t baro_count; /* samples consumed by the baro driver */
    double gps_lat; /* last fix decoded from NMEA, degrees */
    double gps_lon;
    float gps_alt; /* metres MSL */
    uint32_t gps_sats;
    uint32_t gps_count; /* GPS publishes consumed (NMEA sentences decoded) */
    /* The nav_* fields are the ESTIMATOR OUTPUT, and are the opposite of a
 loopback: nothing here was sent by the bridge. They are what the FC
 worked out from the baro and GPS it was fed, so the bridge can compare
 them against the FDM's own truth and gate on the difference.

 Straight from umsg_nav_state_t, so NED and down-positive - altitude is
 -nav_pos_ned[2] and climb rate is -nav_vel_ned[2]. Carried once rather
 than duplicated into scalar alt/vz fields, which would only cost payload
 and invite the two copies to disagree.

 nav_valid is the NAV_VALID_* bitmask and is what makes the rest
 interpretable: it separates "the estimate says 0 m" from "there is no
 estimate yet", and asserting against an unpopulated field is exactly how
 a green gate comes to mean nothing. */
    float nav_pos_ned[3]; /* metres, NED (down positive) */
    float nav_vel_ned[3]; /* metres/second, NED (down positive) */
    uint32_t nav_valid; /* NAV_VALID_* bitmask from nav.json */
    /* Estimator innovation: the angle between measured specific force and the
 estimate's own down axis, degrees. See Nav_AccelResidualDeg.

 Carried because it is the one attitude cross-check that also exists on
 hardware. Every est_* gate in the SIL is estimate-vs-FDM-truth, which is
 a comparison a real vehicle cannot make (KnownIssues 1.16); this one is
 computed entirely on board. Gating it here is what calibrates it for
 use there. */
    float nav_accel_residual_deg;
} Telemetry;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ServoCmd_init_default                    {0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define MotorCmd_init_default                    {0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define Telemetry_init_default                   {{0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0}, {0, 0, 0}, 0, 0}
#define ServoCmd_init_zero                       {0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define MotorCmd_init_zero                       {0, {0, 0, 0, 0, 0, 0, 0, 0}}
#define Telemetry_init_zero                      {{0, 0, 0}, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0}, {0, 0, 0}, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ServoCmd_angle_tag                       1
#define MotorCmd_throttle_tag                    1
#define Telemetry_euler_tag                      1
#define Telemetry_armed_tag                      2
#define Telemetry_imu_count_tag                  3
#define Telemetry_rc_link_up_tag                 4
#define Telemetry_baro_pa_tag                    5
#define Telemetry_baro_count_tag                 6
#define Telemetry_gps_lat_tag                    7
#define Telemetry_gps_lon_tag                    8
#define Telemetry_gps_alt_tag                    9
#define Telemetry_gps_sats_tag                   10
#define Telemetry_gps_count_tag                  11
#define Telemetry_nav_pos_ned_tag                12
#define Telemetry_nav_vel_ned_tag                13
#define Telemetry_nav_valid_tag                  14
#define Telemetry_nav_accel_residual_deg_tag     15

/* Struct field encoding specification for nanopb */
#define ServoCmd_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    angle,             1)
#define ServoCmd_CALLBACK NULL
#define ServoCmd_DEFAULT NULL

#define MotorCmd_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    throttle,          1)
#define MotorCmd_CALLBACK NULL
#define MotorCmd_DEFAULT NULL

#define Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   FIXARRAY, FLOAT,    euler,             1) \
X(a, STATIC,   SINGULAR, BOOL,     armed,             2) \
X(a, STATIC,   SINGULAR, UINT32,   imu_count,         3) \
X(a, STATIC,   SINGULAR, BOOL,     rc_link_up,        4) \
X(a, STATIC,   SINGULAR, FLOAT,    baro_pa,           5) \
X(a, STATIC,   SINGULAR, UINT32,   baro_count,        6) \
X(a, STATIC,   SINGULAR, DOUBLE,   gps_lat,           7) \
X(a, STATIC,   SINGULAR, DOUBLE,   gps_lon,           8) \
X(a, STATIC,   SINGULAR, FLOAT,    gps_alt,           9) \
X(a, STATIC,   SINGULAR, UINT32,   gps_sats,         10) \
X(a, STATIC,   SINGULAR, UINT32,   gps_count,        11) \
X(a, STATIC,   FIXARRAY, FLOAT,    nav_pos_ned,      12) \
X(a, STATIC,   FIXARRAY, FLOAT,    nav_vel_ned,      13) \
X(a, STATIC,   SINGULAR, UINT32,   nav_valid,        14) \
X(a, STATIC,   SINGULAR, FLOAT,    nav_accel_residual_deg,  15)
#define Telemetry_CALLBACK NULL
#define Telemetry_DEFAULT NULL

extern const pb_msgdesc_t ServoCmd_msg;
extern const pb_msgdesc_t MotorCmd_msg;
extern const pb_msgdesc_t Telemetry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ServoCmd_fields &ServoCmd_msg
#define MotorCmd_fields &MotorCmd_msg
#define Telemetry_fields &Telemetry_msg

/* Maximum encoded size of messages (where known) */
#define MotorCmd_size                            40
#define SIM_PB_H_MAX_SIZE                        Telemetry_size
#define ServoCmd_size                            40
#define Telemetry_size                           112

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
