/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "sim.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorData, SensorData, AUTO)


PB_BIND(ServoCmd, ServoCmd, AUTO)


PB_BIND(MotorCmd, MotorCmd, AUTO)


PB_BIND(Telemetry, Telemetry, AUTO)



