# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: flapjack.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'flapjack.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66lapjack.proto\"K\n\tSetPidCmd\x12\x13\n\x04\x61xis\x18\x01 \x01(\x0e\x32\x05.Axis\x12\x1a\n\x04gain\x18\x02 \x01(\x0e\x32\x0c.PidGainType\x12\r\n\x05value\x18\x03 \x01(\x02\"\x15\n\x06\x41rmCmd\x12\x0b\n\x03\x61rm\x18\x01 \x01(\x08\"N\n\x07\x43ommand\x12\x1d\n\x07set_pid\x18\x01 \x01(\x0b\x32\n.SetPidCmdH\x00\x12\x1d\n\narm_disarm\x18\x02 \x01(\x0b\x32\x07.ArmCmdH\x00\x42\x05\n\x03\x63md*2\n\x04\x41xis\x12\x08\n\x04ROLL\x10\x00\x12\t\n\x05PITCH\x10\x01\x12\x07\n\x03YAW\x10\x02\x12\x0c\n\x08THROTTLE\x10\x03*9\n\x0bPidGainType\x12\x06\n\x02KP\x10\x00\x12\x06\n\x02KI\x10\x01\x12\x06\n\x02KD\x10\x02\x12\x12\n\x0eINTEGRAL_LIMIT\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'flapjack_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AXIS']._serialized_start=198
  _globals['_AXIS']._serialized_end=248
  _globals['_PIDGAINTYPE']._serialized_start=250
  _globals['_PIDGAINTYPE']._serialized_end=307
  _globals['_SETPIDCMD']._serialized_start=18
  _globals['_SETPIDCMD']._serialized_end=93
  _globals['_ARMCMD']._serialized_start=95
  _globals['_ARMCMD']._serialized_end=116
  _globals['_COMMAND']._serialized_start=118
  _globals['_COMMAND']._serialized_end=196
# @@protoc_insertion_point(module_scope)
