#ifndef STM32H747I_DISCO_H
#define STM32H747I_DISCO_H

#define BOARD_NAME      "STM32H747I-DISCO"

#define TARG_SPI_1_SCK  PLAT_GPIO_ID_MAKE (A, 5)
#define TARG_SPI_1_MISO PLAT_GPIO_ID_MAKE (A, 6)
#define TARG_SPI_1_MOSI PLAT_GPIO_ID_MAKE (A, 7)

#define TARG_SPI_2_SCK  PLAT_GPIO_ID_MAKE (B, 13)
#define TARG_SPI_2_MISO PLAT_GPIO_ID_MAKE (B, 14)
#define TARG_SPI_2_MOSI PLAT_GPIO_ID_MAKE (B, 15)


#endif // STM32H747I_DISCO_H