/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "flapjack.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SetPidCmd, SetPidCmd, AUTO)


PB_BIND(ArmCmd, ArmCmd, AUTO)


PB_BIND(Command, Command, AUTO)







